<div style="background-color:#3C589D; padding:5px; overflow:auto; max-height:400px;">
	<div style="display:inline-block">
		<img src="/img/icons/newsfeed.png" />
	</div>
	<div style="display:inline-block">
		<img src="/img/icons/leaderboards.png" />
	</div>
	<div style="display:inline-block">
		<img src="/img/icons/profile.png" />
	</div>
	<div style="display:inline-block">
		<img src="/img/icons/rewards.png" />
	</div>
</div>
<ul>
	
</ul>