
						<div class="row">
							<div class="span12">
								<div class="title">
									<div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture"></a></div>
									<div class="title-header"> <h3><?echo $this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name ?>'s Awards</h3> </div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="span12">
								<div class="awards-pic">user's awards pic</div>
							</div>
						</div>
						<div class="row">
							<div class="span12">
								<div class="awards">
									<div>overall awards</div>
									<div class="progress">
										<div class="bar" style="width: 60%;">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							
								<div class="span12">
									<div class="awards">
										<div class="row">
											<div class="span4">
												
													<div>Achievements</div>
													<div class="progress">
														<div class="bar" style="width: 60%;">
														</div>
													</div>
												
											</div>
											<div class="span4">
												<div>metals</div>
												<div class="progress">
													<div class="bar" style="width: 60%;">
													</div>
												</div>
											</div>
											<div class="span4">
												<div>ribbons</div>
												<div class="progress">
													<div class="bar" style="width: 60%;">
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
						</div>
						
						<div class="shadow"></div>
						
						
						<div class="row">
							<div class="span6">
								<div class="text-title gray">Metals ?/?</div>
							</div>
							
							<div class="span6">
								<div class="text-title gray">Ribbons ?/?</div>
								<div>
									hello
								</div>
							</div>
							
						</div>
						
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/post_post_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_post_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_post_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_post_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_post_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_post_100.png" />
										</div>
								</div>
							</div>
							
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/post_comment_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_comment_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_comment_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_comment_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_comment_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_comment_100.png" />
										</div>
								</div>
							</div>
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/post_photo_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_photo_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_photo_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_photo_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_photo_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_photo_100.png" />
										</div>
								</div>
							</div>
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/post_video_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_video_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_video_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_video_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_video_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/post_video_100.png" />
										</div>
								</div>
							</div>
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/like_post_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_post_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_post_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_post_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_post_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_post_100.png" />
										</div>
								</div>
						
							</div>
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/like_comment_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_comment_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_comment_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_comment_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_comment_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_comment_100.png" />
										</div>
								</div>
						
							</div>
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/like_photo_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_photo_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_photo_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_photo_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_photo_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_photo_100.png" />
										</div>
								</div>
						
							</div>
							<div class="row">
								<div class="span6">
										<div class="span1 rb">
											<img src="/img/badges/like_video_1.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_video_5.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_video_10.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_video_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_video_100.png" />
										</div>
										<div class="span1 rb">
											<img src="/img/badges/like_video_100.png" />
										</div>
								</div>
						
							</div>