<script>
selected_badges=  <?= count($this->selected)?>;

</script>

<div class="row">
	<div class="span8">
		<div class="row box notitle">
			
			<div class="post-container noline">
				<div class="user">
					
					<div class="name">
						Pick 3 Badges to Display in your profile!<br/>
						If you don't pick any badges, it will display your most recent badges.<br/>
						Remember to Click Save afterwards 
					</div>
					<input type="button" class="btn-submit" value="Save Badges" onclick="submit_badges_choice()">
				</div>
				<div class="post">
					
					<?php foreach ($this->badges as $b): ?>
						
						<div class="progress cbadges <?= (in_array($b['badge_id'],$this->selected))?'selected':''?> " style="height:50px;width:50px;margin:10px 8px 10px;display:inline-block" 
							 data-id="<?=$b['badge_id']?>">
							<div class="bar" style="width: 100%;height:50px"></div>
							<a data-original-title="<?= $b['name']. '<br/>'.$b['description']?>" 
							 rel="tooltip" data-placement="top" style="float:left; position:relative;top:-50px;" >
								<img src="<?= $b['picture']?>"/>
							</a>
						</div>
						
					<?php endforeach;?>
				</div>
			</div>

		</div>
	</div>
</div>