


<script>
selected_badges=  <?= ($this->selected[0] == 'undefined')?0:count($this->selected)?>;

</script>

<div class="rvrow">
	<div class="rvgrid-11">
		<div class="box">
			<div class="title nopic">
					
					<div class="title-header nopic">
						Display Badges Picker
					</div>
					<a class="display-badges-button" onclick="submit_badges_choice()"><span class="btn fc-edit"  >Save Badges</span></a>
				</div>
			<div class="post-container noline">
				<div class="post">
					
				
						Pick 3 Badges to Display in your profile!<br/>
						If you don't pick any badges, it will display your most recent badges.<br/>
						Remember to Click Save afterwards 
			
					
				</div>
				<div class="post" style="padding-left:20px;">
					
					<?php foreach ($this->badges as $b): ?>
						
						<div class="progress earned-badges cbadges <?= (in_array($b['badge_id'],$this->selected))?'selected':''?> "  
							 data-id="<?=$b['badge_id']?>">
							<div class="bar" ></div>
							<a data-original-title="<?=$b['stylename'].' '.$b['name']. '<br/>'.$b['description']?>" 
							 rel="tooltip" data-placement="top"  >
								<img src="<?= $b['picture']?>"/>
							</a>
						</div>
						
					<?php endforeach;?>
					<!-- <input type="button" class="btn-submit" value="Reset All Choices" onclick="reset_badges_choice()"> -->
				</div>
			</div>

		</div>
	</div>
</div>