

<?php $count = 0?>

<?php if(empty($this->post)){

	echo "Missing Access Token or Empty List";
}?>



<?php foreach ($this->post as $post):?>		

			
	<li class="grey-light" >


	<div class="flag">	
	
			
	<a href="#" 
		<? if (!($this->relation[$count] == 'Fanpage')){?> 
			onclick="userProfile('<?=$post['facebook_user_id']?>')"
			rel="popover" 
			data-content="" 
			data-original-title="" 
			data-placement="right" 
			data-userid="<?=$post['facebook_user_id']?>"
		<?php }?> 
	> 
	
	
	
		<span class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post['facebook_user_id'] ?>/picture" onerror="ImgError(this);"></span>
		
		
		<span class="name">
			<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>
		</span>
	</a> 
	<div class="date"><?=  date("l g:i a, F d Y",strtotime($post['created_time']))?></div>
	
	</div>

		
	
	<div class="post_container">
	<div class="post">
		<? if($post['post_message'] != null ){?><div class="message"><?
				$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/";
	
				
				$m = $this->escape($post['post_message']);
			

				if(preg_match($reg_exUrl, $m, $url)) {
				
		
				       echo preg_replace($reg_exUrl, "<a href=".$url[0]." target=_new >".$url[0]."</a> ", $m);
				
				} else {
				
				       echo $m;
				
				}?></div><?}?>
				
		<div class="pic">
		
			<? if($post['link']!= null) { ?> 
				<?php if($post['post_type'] == 'link') {?>
					<div class="link">
					<div class="link-left"> 
				<?php }?> 
				<a target="new" href="<?echo $this->escape($post['link'])?> "> 
			<?}?>
			
			<? if($post['picture'] != null){?>
				<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post['picture']))?> '/>
			 <? } ?>
			 
			<? if($post['post_type'] == 'link') { ?> 
				</a> </div>
				
				
				<?php if ($post['picture'] != null ){?><div class="link-right"><?php }?>
					<a target="new" href="<?echo $this->escape($post['link'])?> "><?= $this->escape($post['link_name'])?></a>
					
					<?php  if ($post['post_caption']!= null){?></br><?php echo $this->escape($post['post_caption']); ?>:<? }?> 
					<br/>
					
					<?php if ($post['post_description']!= null){?><?=$this->escape($post['post_description'])?><?php }?>
					<?php if ($post['picture']!= null){?></div> <?php }?>
				
			<?}elseif($post['link']!= null){ ?>
				</a><br/></div>
			<?php }?>
			
		</div>
	</div>
	</div>
		
	
	
	<div class="social"> 
		<? if (!($this->relation[$count] == 'Fanpage')){?>
		<? if ($this->relation[$count] != 'You') { ?>
			<? if (($this->relation[$count] != 'Following') /*&& ($this->relation[$count] != 'Friends')*/){?>
					<a href="#" onclick="follow(<?=$post['facebook_user_id']?> , '<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>', 'follow_<?=$post['facebook_user_id']?>')" class ="follow_<?=$post['facebook_user_id']?>" >
				<?}else{?>
					<a href="#" onclick="unfollow(<?=$post['facebook_user_id']?> , '<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>', 'follow_<?=$post['facebook_user_id']?>')" class ="follow_<?=$post['facebook_user_id']?>">
				<?}?>
				
				<div class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></div></a>
			<?php }else{?>
				<div class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></div>
			<?php }?>
	<?}?>	
		<span class="likes">
			<img src="/img/news-feed/icon-likes.png" />
			
			<span class="like_<?= $post['post_id']?>"><? if($post['post_likes_count']!=null){echo $post['post_likes_count'];}else{echo '0';} ?></span>
			
			
			<?php if ($this->likes[$count] == 0) {?>
				<a class="like_control_<?= $post['post_id']?>" href="#post_<?=$post['post_id']?>" onclick="like('<?= $post['post_id']?>', '<?= $post['post_type']?>', '<?=$post['facebook_user_id']?>','<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>' )" >Like</a>   
			<?}else{?>
				<a class="like_control_<?= $post['post_id']?>" href="#post_<?=$post['post_id']?>" onclick="unlike('<?= $post['post_id']?>', '<?= $post['post_type']?>', '<?=$post['facebook_user_id']?>','<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>')">Unlike</a>   
			<?php }?>
		</span>
		<span class="comment">
		<?php if($post['post_comments_count']!= null){
				echo $post['post_comments_count']; //echo  $post['post_comments_count'];
		 	} else {
				echo '0'; 
			}?>
		 <a href="#post_<?=$post['post_id']?>" onclick=" comment_feed('<?= $post['post_id'] ?>','<?= $post['post_type']?>', 5,<?php 
		 		if($post['post_comments_count']!=null){
					echo $post['post_comments_count']; //echo  $post['post_comments_count'];
		 	} else {echo '0';} ?> , true )">Comment</a>
		</span>
		<br/>
		
	</div>

	<ul class="comments" id="post_<?=$post['post_id']?>" ></ul>
	
	</div>
	</li>	

					
<?php $count ++;?>

<li class="feed_spacer">

<div class="feed_spacer_top"></div>

</li>
<?php endforeach; ?>
				
						
	


			