

<?php $count = 0?>

<?php if(empty($this->post)){

	echo "Missing Access Token or Empty List";
}?>



<?php foreach ($this->post as $post):?>		

	<?php if ($count % 2 == 0){?>			
	<li class="grey-light" >
	<?php }else{?>
	<li class="grey-dark" >
	<?php }?>

						
	<div class="photo"><a href="#" <? if (!($this->relation[$count] == 'Fanpage')){?>onclick="userProfile('<?=$post['facebook_user_id']?>')"<?}?>><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post['facebook_user_id'] ?>/picture" onerror="ImgError(this);"></a></div>
	<div class="name">
		<a href="#" <? if (!($this->relation[$count] == 'Fanpage') ){?>onclick="userProfile('<?=$post['facebook_user_id']?>')"<?}?>><?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?></a> 
	
		
	
	</div>
	
	<? if (!($this->relation[$count] == 'Fanpage')){?>
		<? if ($this->relation[$count] != 'You') { ?>
			<? if (($this->relation[$count] != 'Following') /*&& ($this->relation[$count] != 'Friends')*/){?>
					<a href="#" onclick="follow(<?=$post['facebook_user_id']?> , '<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>', 'follow_<?=$post['facebook_user_id']?>')" class ="follow_<?=$post['facebook_user_id']?>" >
				<?}else{?>
					<a href="#" onclick="unfollow(<?=$post['facebook_user_id']?> , '<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>', 'follow_<?=$post['facebook_user_id']?>')" class ="follow_<?=$post['facebook_user_id']?>">
				<?}?>
				
				<div class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></div></a>
			<?php }else{?>
				<div class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></div>
			<?php }?>
	<?}?>		
	

	<div class="post">
	
	<div class="pic">
	
		<? if($post['link']!= null) { ?> 
			<?php if($post['post_type'] == 'link') {?>
				<div class="link-left"> 
			<?php }?> 
			<a target="new" href="<?echo $this->escape($post['link'])?> "> 
		<?}?>
		
		<? if($post['picture'] != null){?>
			<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post['picture']))?> '/>
		 <? } ?>
		 
		<? if($post['post_type'] == 'link') { ?> 
			</a> </div>
			
			
			<?php if ($post['picture'] != null ){?><div class="link-right"><?php }?>
				<a target="new" href="<?echo $this->escape($post['link'])?> "><?= $this->escape($post['link_name'])?></a>
				
				<?php  if ($post['post_caption']!= null){?></br><?php echo $this->escape($post['post_caption']); }?>: 
				<br/>
				<br/>
				
				<?php if ($post['post_description']!= null){?><?=$this->escape($post['post_description'])?><?php }?>
				<?php if ($post['picture']!= null){?></div> <?php }?>
			
		<?}elseif($post['link']!= null){ ?>
			</a>
		<?php }?>
		
		<br/>
	</div>
	
	
	<div class="message"><? if($post['post_message'] != null ){echo $this->escape($post['post_message']);}?></div>
	</div>
	<div class="social"> 
	
		<span class="likes">
			<img src="/img/news-feed/icon-likes.png" />
			
			<span class="like_<?= $post['post_id']?>"><? if($post['post_likes_count']!=null){echo $post['post_likes_count'];}else{echo '0';} ?></span>
			
			
			<?php if ($this->likes[$count] == 0) {?>
				<a class="like_control_<?= $post['post_id']?>" href="#post_<?=$post['post_id']?>" onclick="like('<?= $post['post_id']?>', '<?= $post['post_type']?>', '<?=$post['facebook_user_id']?>','<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>' )" >Like</a>   
			<?}else{?>
				<a class="like_control_<?= $post['post_id']?>" href="#post_<?=$post['post_id']?>" onclick="unlike('<?= $post['post_id']?>', '<?= $post['post_type']?>', '<?=$post['facebook_user_id']?>','<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>')">Unlike</a>   
			<?php }?>
		</span>
		<span class="comment">
		<?php if($post['post_comments_count']!= null){
				echo $post['post_comments_count']; //echo  $post['post_comments_count'];
		 	} else {
				echo '0'; 
			}?>
		 <a href="#post_<?=$post['post_id']?>" onclick=" comment_feed('<?= $post['post_id'] ?>','<?= $post['post_type']?>', 5,<?php 
		 		if($post['post_comments_count']!=null){
					echo $post['post_comments_count']; //echo  $post['post_comments_count'];
		 	} else {echo '0';} ?> , true )">Comment</a>
		</span>
		<br/>
		<span class="date"><?=  date("l, F d, g:i a ",strtotime($post['created_time']))?></span>
	</div>

	<ul class="comments" id="post_<?=$post['post_id']?>" ></ul></li>	

					
<?php $count ++;?>

<li class="feed_spacer">

<div class="feed_spacer_top"></div>

</li>
<?php endforeach; ?>
				
						
	


			