
<?php $count = 0?>

<?php if(empty($this->post)){?>
	
	<li class="post-container">

		
			<div class="post">
				<div class="message">
				No More Posts
				</div>
			</div>
		
	</li>
<?}else{?>



<?php foreach ($this->post as $post):?>		
	<?php if (isset($post->story)){?>
	
	<?php }else{?>
		
	<li class="post-container <?=$post->id?>" >
	
	<div class="user" >		
	
	<div class="user-badge">
		<a rel="tooltip-follow" class ="follow_<?=$post->from->id?>" <?php switch($this->relation[$count]) { 
			case 'Fanpage':?>
				 data-original-title="You can't Follow an Admin"><span class="badge badge-Fanpage">Admin</span>
			<?break;?>
			
			<?case 'You':?>
				 data-original-title="This is You"><span class="badge badge-You">You</span>
			<?break;?>
			
			<?case 'Following':?>
				onclick="unfollow(<?=$post->from->id?> ,'<?=$post->from->name?>')" 
				data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
			<?break;?>
				
			<?default:?>
				onclick="follow(<?=$post->from->id?> , '<?=$post->from->name?>')" 				
				data-original-title="Click to Follow this User"><span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
			<?}?>
		</a>
	</div>
	
	<div class="photo"><a data-toggle="modal"
		<? if (($this->relation[$count] != 'Fanpage')){?> 
			onclick="userProfile('<?=$post->from->id?>')"
			rel="popover" 
			data-content="" 
			data-original-title="" 
			data-placement="right" 
			data-userid="<?=$post->from->id?>"
		<?php }?>
	><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post->from->id ?>/picture" onerror="ImgError(this);">
	</a></div>
	
	<div class="name"><a data-toggle="modal"
		<? if (($this->relation[$count] != 'Fanpage')){?> 
			onclick="userProfile('<?=$post->from->id?>')"
			rel="popover" 
			data-content="" 
			data-original-title="" 
			data-placement="right" 
			data-userid="<?=$post->from->id?>"
		<?php }?>
	><?=  $post->from->name?>
	</a></div>
	
		
	
	</div>
	
			
	

	<div class="post">



			<?php if(isset($post->message)){ ?>
							<div class="message">
							<?php 
							$reg_ex = "/\n/";
							$message = $this->escape($post->message);
							if(preg_match_all($reg_ex, $message, $url)) {
								$message= preg_replace($reg_ex, "<br/>", $message);
							} 
							
							$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
						
							$m = preg_match_all($reg_exUrl, $message, $match); 
							
							if ($m) { 
							    $links=$match[0]; 
							    for ($j=0;$j<$m;$j++) { 
							        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
							    } 
							} 
							
							echo $message; 
								//echo preg_replace($reg_exUrl, "<a href=".$url[0][0]." target=_new>".$url[0][0]."</a> ", $m);
							
							?><br/>
							</div>
			<?}	?>
		<div class="graphical">	
		<?php if ($post->type == 'photo'){?>	
			<a target="new" href="<?echo $this->escape($post->link)?> "> 
						<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
					</a>
		<?php }elseif ($post->type =='video') { ?>
			
				<?php if (strstr($this->escape($post->link), 'youtube.com')){
						$temp=explode("http://www.youtube.com/watch?v=", $this->escape($post->link));?>
						<iframe width="508" height="286" src="http://www.youtube.com/embed/<?= $temp[1]?> "  frameborder="0" allowfullscreen></iframe>
				
				<?php }else if (strstr($this->escape($post->link), 'vimeo.com')){
						$temp=explode("http://vimeo.com/", 	$this->escape($post->link));	?>
						<iframe width="508" height="286" src="http://player.vimeo.com/video/<?= $temp[1]?>"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
			
				<?php }else if (strstr($this->escape($post->link), 'facebook.com')){
						$temp=explode("v=", $this->escape($post->link));?>
					 <object width="508" height="286" > 
					 <param name="allowfullscreen" value="true" /> 
					 <param name="allowscriptaccess" value="always" /> 
					 <param name="movie" value="http://www.facebook.com/v/<?= $temp[1]?>" /> 
					 <embed src="http://www.facebook.com/v/<?= $temp[1]?>" type="application/x-shockwave-flash"  
					   allowscriptaccess="always" allowfullscreen="true" width="508" height="286"> 
					 </embed> 
					</object> 
				<?php }else if (strstr($this->escape($post->link), 'liveleak.com/view')){ 
						$temp=explode("view?i=", $this->escape($post->link));?>
					<iframe width="508" height="286" src="http://www.liveleak.com/ll_embed?f=<?= $temp[1] ?>" frameborder="0" allowfullscreen></iframe>
				<?php }?>
		<?}elseif ($post->type == 'link') {?>
			<div class="link">
			<?php if (isset($post->picture)){?>
				<div class="link-left">
					
					<a target="new" href="<?echo $this->escape($post->link)?> "> 
						<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
					</a>
					
				</div>
			<?php }?>
				<div class="link-right">
					<a target="_new" class="link-title" href="<?echo $this->escape($post->link)?>">
						<?= (isset($post->name)?$this->escape($post->name): $this->escape($post->link))?>
					</a>
					<?php if(isset($post->caption)){?>
						<br/>
						<a target="_new" class="link-caption" href="<?echo $this->escape($post->link)?> ">
							<?php echo $this->escape($post->caption);?>:  
						</a>
					<?php }?>	
				
					<?php if (isset($post->description)){?>
						<a target="_new" class="link-caption" href="<?echo $this->escape($post->link)?> ">	
							<?=$this->escape($post->description)?> 
						</a>
					<?php }?>
						
					
				</div>
			</div>
		<?}?>
		</div>
		
		
		
		
	
	
	</div>
	
	<div class="social">

		<a class="like_control_<?= $post->id?>" data-placement="top-left" rel="tooltip"
		<?php if ($this->likes[$count] == 0) {?> 
			data-original-title="Click to like this" 
			onclick="like('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>' )">Like
			<?}else{?> data-original-title="You like this" 
			onclick="unlike('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>')">Unlike
			<?php }?>
		</a>

		&middot;
		
		<a  onclick=" comment_feed('<?= $post->id ?>',
			 						'<?= $post->type?>', 
			 						10,
			 						<?= (isset($post->comments->count)? $post->comments->count : '0')?> , 
								 	true )"
			class="commenthider_<?= $post->id ?>">Comment</a>
		
		<?php if (isset($post->comments->count) && ($post->comments->count>5 ) ){?>
		&middot;
		
		<a  onclick=" comment_feed_filter('<?= $post->id ?>',
			 						'<?= $post->type?>', 
			 						10,
			 						<?= (isset($post->comments->count)? $post->comments->count : '0')?> , 
								 	true )"
			class="commenthider_<?= $post->id ?>">My Comment</a>
		<?php }?>
		&middot;

		<a rel="tooltip" data-placement="top" class="time" data-original-title="" data-unix-time="<?=  strtotime($post->created_time)?>"></a>

		&middot;
		<?= $this->yourpoints[$count]?> pts earned from this post.
		
	</div>
	<div class="social like <?=$post->id?>"  <?php if(!isset($post->likes->count) || ($post->likes->count == 0)){?>style="display:none"<?php }?>>
		
			<a rel="tooltip" data-placement="top" onclick="getLikesList('<?=$post->id?>',<? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>, true)" data-original-title="
						<?php 	$likeslist = $post->likes->data;
								$countlikes = count($likeslist);
								for($i = 0; $i < $countlikes - 1; $i++){
									echo $likeslist[$i]->name.', ';
								}

								echo $likeslist[$i]->name;
								if ($countlikes < $post->likes->count){
									echo " and ".($post->likes->count - $countlikes)." others";
								}
						?> likes this.
						">
				<img src = "/img/thumbsup.png" />
				<span class="like_<?= $post->id?>" data-like-count =<? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?> ><? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>
					
					<?php if(isset($post->likes->count) && $post->likes->count == 1){?>person<?php }else{?>people<?php }?> 
				
				</span>
				likes this
			</a>		
		
	
	</div>
 
	<div class="social comment <?=$post->id?>" <?php if(!isset($post->comments->count) || ($post->comments->count == 0)){?>style="display:none"<? }?>>
	
			 <a  onclick=" comment_feed('<?= $post->id ?>',
			 							'<?= $post->type?>', 
			 							10,
			 							<?= (isset($post->comments->count)? $post->comments->count : '0')?> , 
								 		true )"> 
					<img src="/img/comment.png" />
			 		<?php if($post->comments->count != 1){?> 
			 		View all <span class="comment_<?= $post->id?>" data-comment-count = <?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>>
			 		<?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>
					</span> 
					comments 
				<?php }else { ?>
					View all<span class="comment_<?= $post->id?>" data-comment-count = <?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>>
			 		
					 
					
					</span>
					comments 
				<?php }?>
				</a>
				
				<?php if (($post->comments->count)>5){?>
				
			&middot;
				
				
				 <a  onclick=" comment_feed_filter('<?= $post->id ?>',
			 							'<?= $post->type?>', 
			 							10,
			 							<?= (isset($post->comments->count)? $post->comments->count : '0')?> , 
								 		true )"> 
					<img src="/img/comment.png" />
			 		View My Comments
				</a>
				
				<?php }?>
	
	</div>

	
	
	
	<div id="post_<?=$post->id?>" ></div>
	</li>	
			

 <?php }?>
<?php $count ++;?>

<?php endforeach; ?>
				
				
<?php  $last_object = $this->post[count($this->post) - 1] ?>

<li id="last_post_time" data-time="
<?=  strtotime($last_object->created_time)?>"></li>
<li id ="more_post"><button  class="btn-more" onclick="getFancrankfeed(setFeed)">MORE POSTS +</button></li>

<?php }?>	