
<?php $count = 0?>

<?php if(!empty($this->comments)){?>



<?php foreach ($this->comments as $post): ?>		

		
	<li class="grey-light" >

	
	
	
	<div class="post_container">
		<span class="comment_badge">
		<? if (($this->relation[$count] != 'Fanpage')){?>
			<? if ($this->relation[$count] != 'You') { ?>
				<? if (($this->relation[$count] != 'Following') /*&& ($this->relation[$count] != 'Friends')*/){?>
						<a onclick="follow(<?=$post->from->id?> , '<?=$post->from->name?>', 'follow_<?=$post->from->id?>')" class ="follow_<?=$post->from->id?>">
					<?}else{?>
						<a onclick="unfollow(<?=$post->from->id?> , '<?=$post->from->name?>', 'follow_<?=$post->from->id?>')" class ="follow_<?=$post->from->id?>">
					<?}?>
						<span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span></a>
				<?php }else{?>
					<span class="badge badge-You">You</span>
				<?php }?>
		<?}else{?>
				<span class="badge badge-Fanpage">Admin</span>
		<?php }?>
		</span>
	<a  
		<? if (!($this->relation[$count] == 'Fanpage')){?> 
			onclick="userProfile('<?=$post->from->id?>')"
			rel="popover" 
			data-content="" 
			data-original-title="" 
			data-placement="right" 
			data-userid="<?=$post->from->id?>"
		<?php }?> 
	> 
	
		
			<span class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post->from->id ?>/picture" onerror="ImgError(this);"></span>
			
			<span class="name">
				<?=  $post->from->name?>
			</span>
			
		</a>
		
		
<div class="post">
	<span class="message">
	
	<? if(isset($post->message)){
		
		$reg_ex = "/\n/";
		$m = $this->escape($post->message);
			
		if(preg_match_all($reg_ex, $m, $url)) {
		
		
			$m= preg_replace($reg_ex, "<br/>", $m);
				
						}
		$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/";
	
				
				

				if(preg_match($reg_exUrl, $m, $url)) {
				
		
				       echo preg_replace($reg_exUrl, "<a href=".$url[0]." target=_new>".$url[0]."</a> ", $m);
				
				} else {
				
				       echo $m;
				
				}}?>
	
	<br/>
	<span class="social"> 
	 	
	
		
		
		
		<!--  <img src="/img/news-feed/icon-likes.png" /> -->
		<span class="likes">
		<span class="like_<?= $post->id?>"><? if(isset($post->likes)){echo $post->likes;}else{echo '0';} ?> </span>
		
		
		<?php if ($this->likes[$count] == 0) {?>
			<a class="like_control_<?= $post->id?>"  onclick="like('<?= $post->id?>', 'comment', '<?=$post->from->id?>','<?=$post->from->name?>')" >Like</a> 
		<?}else{?>
			<a class="like_control_<?= $post->id?>" onclick="unlike('<?= $post->id?>', 'comment', '<?=$post->from->id?>','<?=$post->from->name?>')" >Unlike</a> 
		<?php }?>
		 </span>	 
		 
		 &middot;
		
		 <span class="date"><span class="time" title="<?=  strtotime($post->created_time)?>"><?=  strtotime($post->created_time)?></span></span>
		
	 </span>
	 
	 </span>
	 </div>
	</div>
	</li>
										
<?php $count ++;?>
<?php endforeach; }?>

	
	<?if ($this->total > $this->limit){ ?>
	
		
			<button class="btn-top" onclick="comment_feed<?= ($this->latest == 'true')?'2':''?>('<?= $this->postId ?>','<?= $this->postType?>', <?=$this->limit + 5?> , <?= $this->total?> , false)"> MORE +</button>
		
	
	<?}?>
	<li class="comment_container">
		<div class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->userid?>/picture" onerror="ImgError(this);"></div>
	
		<form action="#" >
		
			<textarea class="comment_box" id="comment_<?= $this->postId ?>" onkeyup="resizeCommentBox(this)"></textarea>
			<input type=button class="btn-submit" value="Submit" onclick="commentSubmit('<?= $this->postId ?>','<?=$this->postType?>' ,'comment_<?= $this->postId ?>','<?=$this->postOwner['user_id']?>','<?=$this->postOwner['user_name']?>', <?= $this->total?>,<?= ($this->latest == 'true')?'true':'false'?> )">
		</form>
	
	</li>
		
						
			