

<?php $count = 0?>

<?php if(empty($this->post)){?>

	<li class="post-container">
		<div class="post">
			<div class="message">
			There are no more posts
			</div>
		</div>
	</li> 
<? }else{?>



<?php foreach ($this->post as $post):?>		

			
	<li class="post-container" >


	<div class="user">	
	<div class="user-badge">
		<a rel="tooltip-follow" class ="follow_<?=$post->from->id?>" <?php switch($this->relation[$count]) { 
			case 'Fanpage':?>
				 data-original-title="You can't Follow an Admin"><span class="badge badge-Fanpage">Admin</span>
			<?break;?>
			<?case 'You':?>
				 data-original-title="This is You"><span class="badge badge-You">You</span>
			<?break;?>
			<?case 'Following':?>
				onclick="unfollow(<?=$post['facebook_user_id']?> ,'<?= ($post['fan_name']!=null)?$post['fan_name']:$post['fanpage_name']?>')" 
				data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
			<?break;?>
				
			<?default:?>
				onclick="follow(<?=$post['facebook_user_id']?> , '<?= ($post['fan_name']!=null)?$post['fan_name']:$post['fanpage_name']?>')" 				
				data-original-title="Click to Follow this User"><span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
			<?}?>
		</a>
	

	</div>
			
	

		<div class="photo">
			<a 
			<? if (!($this->relation[$count] == 'Fanpage')){?> 
				onclick="userProfile('<?=$post['facebook_user_id']?>')"
				rel="popover" 
				data-content="" 
				data-original-title="" 
				data-placement="right" 
				data-userid="<?=$post['facebook_user_id']?>"
			<?php }?> 
		> 
		<img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post['facebook_user_id'] ?>/picture" onerror="ImgError(this);">
		</a>
		</div>
		
		
		<div class="name">
			<a 
			<? if (!($this->relation[$count] == 'Fanpage')){?> 
				onclick="userProfile('<?=$post['facebook_user_id']?>')"
				rel="popover" 
				data-content="" 
				data-original-title="" 
				data-placement="right" 
				data-userid="<?=$post['facebook_user_id']?>"
			<?php }?> 
		> 
			<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>
			</a>
		</div>
	
	
	</div>

	<div class="post">
		<?php if($post['post_message'] != null ){?>
							<div class="message">
							<?php 
							$reg_ex = "/\n/";
							$message = $this->escape($post['post_message']);
							if(preg_match_all($reg_ex, $message, $url)) {
								$message= preg_replace($reg_ex, "<br/>", $message);
							} 
							
							$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
						
							$m = preg_match_all($reg_exUrl, $message, $match); 
							
							if ($m) { 
							    $links=$match[0]; 
							    for ($j=0;$j<$m;$j++) { 
							        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
							    } 
							} 
							
							echo $message; 
								//echo preg_replace($reg_exUrl, "<a href=".$url[0][0]." target=_new>".$url[0][0]."</a> ", $m);
							
							?><br/>
							</div>
					<?}	?>

			<div class="graphical">	
		<?php if (($post['post_type'] == 'photo') ) {?>	
			<a target="new" href="<?echo $this->escape($post['link'])?> "> 
						<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post['picture']))?> '/>
					</a>
		<?php }elseif ($post['post_type'] == 'video') { ?>
			
			<?php if (strstr($this->escape($post['link']), 'youtube.com')){
					$temp=explode("http://www.youtube.com/watch?v=", $this->escape($post['link']));?>
					<iframe width="419" height="236" src="http://www.youtube.com/embed/<?= $temp[1]?> "  frameborder="0" allowfullscreen></iframe>
			
			<?php }else if (strstr($this->escape($post['link']), 'vimeo.com')){
					$temp=explode("http://vimeo.com/", 	$this->escape($post['link']));	?>
					<iframe width="419" height="236" src="http://player.vimeo.com/video/<?= $temp[1]?>"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
		
			<?php }else if (strstr($this->escape($post['link']), 'facebook.com')){
					$temp=explode("v=", $this->escape($post['link']));?>
				 <object width="419" height="236" > 
				 <param name="allowfullscreen" value="true" /> 
				 <param name="allowscriptaccess" value="always" /> 
				 <param name="movie" value="http://www.facebook.com/v/<?= $temp[1]?>" /> 
				 <embed src="http://www.facebook.com/v/<?= $temp[1]?>" type="application/x-shockwave-flash"  
				   allowscriptaccess="always" allowfullscreen="true" width="419" height="236"> 
				 </embed> 
				</object> 
			<?php }else if (strstr($this->escape($post->link), 'liveleak.com/view')){ 
					$temp=explode("view?i=", $this->escape($post['link']));?>
				<iframe width="419" height="236" src="http://www.liveleak.com/ll_embed?f=<?= $temp[1] ?>" frameborder="0" allowfullscreen></iframe>
			<?php }?>	
		<?}elseif ($post['post_type'] == 'link') {?>
			<div class="link">
				<?php if ($post['picture'] != null){?>
				<div class="link-left">
					<a target="new" href="<?echo $this->escape($post['link'])?> "> 
						<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post['picture']))?> '/>
					</a>
				</div>
				<?php }?>
				<div class="link-right">
					<a target="_new" class="link-title" href="<?echo $this->escape($post['link'])?>">
						<?= (($post['link_name']!=null)?$this->escape($post['link_name']): $this->escape($post['link']))?>
					</a>
					<?php if(isset($post->caption)){?>
						<br/>
						<a target="_new" class="link-caption" href="<?echo $this->escape($post['link'])?> ">
							<?php echo $this->escape($post['post_caption']);?>:  
						</a>
					<?php }?>	
				
					<?php if ($post['post_description']!= null){?>
						<a target="_new" class="link-caption" href="<?echo $this->escape($post['link'])?> ">	
							<?=$this->escape($post['post_description'])?> 
						</a>
					<?php }?>
						
					
				</div>
				
			</div>
		<?}?>
	
			
		
	</div>
	</div>
		
	
	<div class="social"> 
	
				<a class="like_control_<?= $post['post_id']?>" rel="tooltip" data-placement="top"
				<?php if ($this->likes[$count] == 0) {?>
					  data-original-title="Click to like this" onclick="like('<?= $post['post_id']?>', '<?= $post['post_type']?>', '<?=$post['facebook_user_id']?>','<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>' )" >Like  
				<?}else{?>
					  data-original-title="You like this"  onclick="unlike('<?= $post['post_id']?>', '<?= $post['post_type']?>', '<?=$post['facebook_user_id']?>','<?if($post['fan_name']!=null){ echo $post['fan_name']; }else{ echo $post['fanpage_name'];}?>')">Unlike
				<?php }?>
				</a>   
		
				 &middot;
				<a  onclick=" comment_feed('<?= $post['post_id'] ?>','<?= $post['post_type']?>', 5,<?php 
			 		if($post['post_comments_count']!=null){
						echo $post['post_comments_count']; 
			 		} else {echo '0';} ?> , true )" class="commenthider_<?= $post['post-id'] ?>">Comment</a>
				&middot;
				
				<?php if ($post['post_comments_count']>5){ ?>
				 <a  onclick=" comment_feed_filter('<?= $post['post_id'] ?>','<?= $post['post_type']?>', 5,<?php 
			 		if($post['post_comments_count']!=null){
						echo $post['post_comments_count']; 
			 		} else {echo '0';} ?> , true )" class="commenthider_<?= $post['post-id'] ?>">My Comment</a>
				&middot;
				<?php }?>
				<a rel="tooltip" data-placement="top" class="time"  data-original-title="" data-unix-time="<?= strtotime($post['created_time'])?>"></a>
			
			<br/>
	</div>
	<div class="social like <?=$post['post_id']?>"  <?php if(($post['post_likes_count']==null) || ($post['post_likes_count'] == 0)){?>style="display:none"<?php }?>>
		
		
				<!--  <img src="/img/news-feed/icon-likes.png" />-->
			<a>
				<img src = "/img/thumbsup.png" />
				<span class="like_<?= $post['post_id']?>" data-like-count = <? if($post['post_likes_count']!=null){echo $post['post_likes_count'];}else{echo '0';} ?>><? if($post['post_likes_count']!=null){echo $post['post_likes_count'];}else{echo '0';} ?>
					
					<?php if($post['post_likes_count'] == 1){?>person<?php }else{?>people<?php }?> 
				
				</span>
				likes this.
			</a>		
		
	
	</div>
	
	<div class="social comment <?=$post['post_id']?>" <?php if(($post['post_comments_count']== null) || ($post['post_comments_count'] == 0)){?> style="display:none" <?}?>>
	
			 <a  onclick=" comment_feed('<?= $post['post_id'] ?>','<?= $post['post_type']?>', 5,<?php 
			 		if($post['post_comments_count']!= null){
						echo $post['post_comments_count']; //echo  $post->comments->count;
			 	} else {echo '0';} ?> , true )"> <img src="/img/comment.png" />
			 	<?php if($post['post_comments_count'] != 1){?> 
			 		View all <span class="comment_<?= $post['post_id']?>" data-comment-count = <?php if(isset($post['post_comments_count'])){
						echo $post['post_comments_count']; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>>
			 		<?php if(isset($post['post_comments_count'])){
						echo $post['post_comments_count']; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>
					</span> 
					comments 
				<?php }else { ?>
					View all<span class="comment_<?= $post['post_id']?>" data-comment-count = <?php if(isset($post['post_comments_count'])){
						echo $post['post_comments_count']; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>>
			 		
					 
					
					</span>
					comments 
				<?php }?>
				</a>
				
				<?php if ($post['post_comments_count'] > 5){?>
				
			&middot;
				 <a  onclick=" comment_feed_filter('<?= $post['post_id'] ?>','<?= $post['post_type']?>', 5,<?php 
			 		if($post['post_comments_count']!= null){
						echo $post['post_comments_count']; //echo  $post->comments->count;
			 	} else {echo '0';} ?> , true )"> <img src="/img/comment.png" />
			 		View My Comments
				</a>
				<?php }?>
	</div>

	

	<ul id="post_<?=$post['post_id']?>" ></ul>
	
	
	</li>	

					
<?php $count ++;?>

<?php endforeach; }?>
				
<?php if ($this->myfeedcount > 9){?>					
	<li><button id ="more_post" class="btn-more" onclick="getFancrankfeed(setFeed)">MORE POSTS +</button></li>
	<?php }?>


			