
 <br/>
<?php $count = 0?>

<?php if(empty($this->comments)){

	//echo "Missing Access Token";
	
}else{?>



<?php foreach ($this->comments as $post):?>		

	<?php if ($count % 2 == 0){?>			
	<li class="grey-light" >
	<?php }else{?>
	<li class="grey-dark" >
	<?php }?>

	<div class="photo"><a href="#" onclick="userProfile('<?=$post->from->id?>')"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post->from->id ?>/picture"></a></div>
	<div class="post"><div class="name"><a href="#" onclick="userProfile('<?=$post->from->id?>')"><?=  $post->from->name?></a></div>
	<?=  $post->message?></div>
	<div class="social"> <img src="/img/news-feed/icon-likes.png" /> 
	<? if(isset($post->likes)){echo $post->likes;}else{echo '0';} ?> 
	
	
	<?php if ($this->likes[$count] == 0) {?>
		<a href="#" onclick="like('<?= $post->id?>', 'comment', '<?=$post->from->id?>','<?=$post->from->name?>')" class="likes"> Like</a> 
	<?}else{?>
		<a href="#" onclick="unlike('<?= $post->id?>', 'comment', '<?=$post->from->id?>','<?=$post->from->name?>')" class="likes"> Unlike</a> 
	<?php }?>
	 

	
	 <span class="date"><?=  date("l, F d, g:i a ",strtotime($post->created_time))?></span></div>
	
	</li>
										
<?php $count ++;?>
<?php endforeach; }?>

	
	<?if ($this->total > $this->limit){ ?>
		<div class="feed_moreComments" onclick="comment_feed('<?= $this->postId ?>', <?=$this->limit + 5?> , <?= $this->total?> , false)"> MORE +</div>
	<?}?>
	<li class="comment_container">

		<form action="#">
			<textarea class="comment_box" id="comment_<?= $this->postId ?>" onkeyup="resizeCommentBox(this)"></textarea>
			<input type=button class="btn-submit" value="Submit" onclick="commentSubmit('<?= $this->postId ?>','comment_<?= $this->postId ?>','<?=$this->postOwner['user_id']?>','<?=$this->postOwner['user_name']?>' )">
		</form>
	
	</li>
						
						
			