
<!-- not used anymore -->
<?php $count = 0?>
											<?php foreach($this->latest_post as $latestPost): ?>
											
											<?php if ($count % 2 == 0){?>
											<li class="chat-right">
											<?php }else{?>
											<li class="chat-left">
											<?php }?>
												
												<div class="post">
													<a href="#" onclick="comment_bubble('<?= $latestPost['post_id']?>' , 5)"><?= $latestPost['post_message'] ?><br /><span class="date"><?=date("F d Y", strtotime( $latestPost['updated_time']))?></span></a>
           
												</div>
													
													<div class="info">
														<div class="name"><a href=""><?= $latestPost['fan_first_name'] ?> <?= $latestPost['fan_last_name'] ?></a><br /><img src="/img/news-feed/icon-likes.png" /> <?= $latestPost['post_likes_count']?>
														
														 <?php if ($this->likes[$count] == 0) {?>
																<a href="#" onclick="like('<?= $latestPost['post_id']?>', '<?= $latestPost['post_type']?>')" class="likes"> Like</a> 
															<?}else{?>
																<a href="#" onclick="unlike('<?= $latestPost['post_id']?>', '<?= $latestPost['post_type']?>')" class="likes"> Unlike</a> 
															<?php }?>
														 
														 
														 </div>
														 
														 
														<div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $latestPost['facebook_user_id'] ?>/picture"></a></div>
														
													</div>
												
											</li>

											<?php $count ++;?>
											<?php endforeach; ?>
						
				