<?php $count = 0?>
<?php foreach($this->top_post as $topPost): ?>
											
	<?php if ($count % 2 == 0){?>
		<li class="chat-right">
	<?php }else{?>
		<li class="chat-left">
	<?php }?>
												
	<div class="post">
		<a href="#" onclick="comment_bubble('<?= $topPost['post_id']?>', 5)"><?= $topPost['post_message'] ?><br /><span class="date"><?= date("F d Y", strtotime($topPost['updated_time']))?></span></a>  
	</div>
													
	<div class="info">
	<div class="name"><a href=""><?= $topPost['fan_first_name'] ?> <?= $topPost['fan_last_name'] ?></a><br /><img src="/img/news-feed/icon-likes.png" /> <?= $topPost['post_likes_count']?> <a href="" class="likes"> Like</a></div>
	<div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $topPost['facebook_user_id'] ?>/picture"></a></div>
														
	</div>
												
	</li>

<?php $count ++;?>
<?php endforeach; ?>
						

		