<?php $count = 0?>
<?php $count2 = 0?>
<?php if (empty($this->top_post)) {?>
		<li class="box post-container noline" >
			<div class="post">
				<div class="message">
						There are no Top Posts this week
				</div>							
			</div>
		</li>				
<?php }else{?>

		
	<?php foreach($this->top_post as $post): ?>
										
		<?php	$displayname= $post->from->name;
// 				$name = explode(" ", $displayname);
// 				$displayname = $name[0] .' '. end($name);
		
// 				if (strlen($displayname)>16){			
// 					if (strlen($name[0] > 16)){
// 						$displayname = substr($name[0], 0, 16);
// 					}else if(strlen($name[0]) > 14){
// 						$displayname = $name[0].' '.substr(end($name),0,1).'.';
// 					}else if (strlen($name[0]) + strlen (end($name)) < 16){
// 						$displayname = $name[0].' '.end($name);
// 					}
// 				}
		?>
		<li class="box post-container <?=$post->id?>" >
			<div class="user">
				<div class="user-badge">
						<a rel="tooltip-follow"  <?php switch($this->relation[$count]) { 
						case 'You':?>
							 class="noclick" data-original-title="This is You"><span class="btn fc-You">You</span>
						<?break;?>
						
						<?case 'Following'?>
							class ="follow_<?=$post->from->id?>"
							onclick="unfollow(<?=$post->from->id?> ,'<?=$post->from->name?>')" 
							data-original-title="Click to Unfollow this User"><span class="btn fc-Following">Following</span>
						<?break;?>
							
						<?default:?>
							class ="follow_<?=$post->from->id?>"
							onclick="follow(<?=$post->from->id?> ,'<?=$post->from->name?>')" 
							data-original-title="Click to Follow this User"><span class="btn fc-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
						<?}?>
					</a>		
				</div> 
				<div class="photo">
					<a data-toggle="modal"
						
							onclick="userProfile('<?=$post->from->id?>')"
							rel="popover" 
							data-content="" 
							data-original-title="" 
							data-placement="toppost" 
							data-userid="<?=$post->from->id?>"
					
						>
						<img class="small-face" src="https://graph.facebook.com/<?=$post->from->id?>/picture" onerror="ImgError(this);">
					</a>
				</div>
				<div class="name">
					<a data-toggle="modal"
						
							onclick="userProfile('<?=$post->from->id?>')"
							rel="popover" 
							data-content="" 
							data-original-title="" 
							data-placement="toppost" 
							data-userid="<?=$post->from->id?>>"
					>
						<?=$displayname?>
					</a>
				</div>
			</div>
			<div class="post">
				<?php if(isset($post->message)){ ?>
				<div class="message">
					<?php 	$reg_ex = "/\n/";
							$message = $this->escape($post->message);
							if(preg_match_all($reg_ex, $message, $url)) {
								$message= preg_replace($reg_ex, "<br/>", $message);
							} 
							$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
							$m = preg_match_all($reg_exUrl, $message, $match); 
							
							if ($m) { 
							    $links=$match[0]; 
							    for ($j=0;$j<$m;$j++) { 
							        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
							    } 
							} 
							echo $message; 
								//echo preg_replace($reg_exUrl, "<a href=".$url[0][0]." target=_new>".$url[0][0]."</a> ", $m);
					?>
					<br/>
				</div>
				<?}	?>
				<div class="graphical">	
					<?if ($post->type == 'photo'){?>	
						<a onclick="popup_post('<?=$post->id?>', true)"> 
							<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
						</a>
					<?}elseif ($post->type =='video') { ?>
				
						<?if (strstr($this->escape($post->link), 'youtube.com')){
							$temp=explode("http://www.youtube.com/watch?v=", $this->escape($post->link));?>
							<?php $temp=explode("&", $this->escape($temp[1]));?>
							<iframe width="262" height="147" src="http://www.youtube.com/embed/<?= $temp[0]?> "  frameborder="0" allowfullscreen></iframe>
					
						<? }else if (strstr($this->escape($post->link), 'vimeo.com')){
							$temp=explode("http://vimeo.com/", 	$this->escape($post->link));	?>
							<iframe width="262" height="147" src="http://player.vimeo.com/video/<?= $temp[1]?>"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
				
						<? }else if (strstr($this->escape($post->link), 'facebook.com')){
							$temp=explode("v=", $this->escape($post->link));?>
							<object width="262" height="147" > 
								 <param name="allowfullscreen" value="true" /> 
								 <param name="allowscriptaccess" value="always" /> 
								 <param name="movie" value="http://www.facebook.com/v/<?= $temp[1]?>" /> 
								 <embed src="http://www.facebook.com/v/<?= $temp[1]?>" type="application/x-shockwave-flash"  
								   allowscriptaccess="always" allowfullscreen="true" width="262" height="147"> 
								 </embed> 
							</object> 
						<? }else if (strstr($this->escape($post->link), 'liveleak.com/view')){ 
							$temp=explode("view?i=", $this->escape($post->link));?>
							<iframe width="262" height="147" src="http://www.liveleak.com/ll_embed?f=<?= $temp[1] ?>" frameborder="0" allowfullscreen></iframe>
						<? }?>
					<?}elseif ($post->type == 'link') {?>
					<div class="link">
						<?php if (isset($post->picture)){?>
						<div class="link-left">
						
							<a target="new" href="<?echo $this->escape($post->link)?> "> 
								<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
							</a>
						
						</div>
						<?php }?>
						<div class="link-right">
							<a target="_new" class="link-title" href="<?echo $this->escape($post->link)?>">
								<?= (isset($post->name)?$this->escape($post->name): $this->escape($post->link))?>
							</a>
							<?php if(isset($post->caption)){?>
							<br/>
							<a target="_new" class="link-caption" href="<?echo $this->escape($post->link)?> ">
								<?php echo $this->escape($post->caption);?>:  
							</a>
							<?php }?>	
					
							<?php if (isset($post->description)){?>
								<a target="_new" class="link-caption" href="<?echo $this->escape($post->link)?> ">	
									<?=$this->escape($post->description)?> 
								</a>
							<?php }?>
						</div>
					</div>
					<?}?>
				</div>
			</div>
			<div class="social">
	
				<a class="like-control like_control_<?= $post->id?>" data-placement="top-left" rel="tooltip"
				<?php if ($this->likes[$count] == 0) {?> 
					data-original-title="Click to like this" 
					onclick="like('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>' )">Like
					<?}else{?> data-original-title="You like this" 
					onclick="unlike('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>')">Unlike
					<?php }?>
				</a>
	
				&middot; 
			
				<a  onclick=" popup_post('<?= $post->id ?>',true )"
					class="commenthider_<?= $post->id ?>">Comment</a>
			
				&middot;
	
				<a rel="tooltip" data-placement="top" class="time noclick" data-original-title="" data-unix-time="<?=  strtotime($post->created_time)?>"></a>
			
				<?if ($this->yourpoints[$count] !=0){?>
					<a class="point-display noclick"><?= $this->yourpoints[$count]?>Pts</a>
				<?}?>
			
			</div>
			<div class="social like <?=$post->id?>"  <?php if(!isset($post->likes->count) || ($post->likes->count == 0)){?>style="display:none"<?php }?>>
			
				<a rel="tooltip" data-placement="top" onclick="getLikesList('<?=$post->id?>',<? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>, true)" data-original-title="
							<?php 	$likeslist = $post->likes->data;
									$countlikes = count($likeslist);
									for($i = 0; $i < $countlikes - 1; $i++){
										echo $likeslist[$i]->name.', ';
									}
	
									echo $likeslist[$i]->name;
									if ($countlikes < $post->likes->count){
										echo " and ".($post->likes->count - $countlikes)." others";
									}
							?> likes this.
							">
					<img src = "/img/thumbsup.png" />
					<span class="like_<?= $post->id?>" data-like-count =<? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?> ><? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>
						
						<?php if(isset($post->likes->count) && $post->likes->count == 1){?>person<?php }else{?>people<?php }?> 
					
					</span>
					likes this
				</a>		
			</div>
	 		<?php if (isset($post->comments->count) && ($post->comments->count < 5)){?>
	 		<div class="social comment <?=$post->id?>">
		
 		<div id="post_<?=$post->id?>"  data-comment-count = <?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>> 
 			<ul class="comments">
 				

				
				<?php if(!empty($post->comments->data)){?>
				
				<?php foreach ($post->comments->data as $comments): ?>		
				
					<li class="comment-container <?= $comments->id?>" >
				
						<div class="photo"><a  
							<? if (!($this->comment_relation[$count2] == 'Fanpage')){?> 
								onclick="userProfile('<?=$comments->from->id?>')"
								rel="popover" 
								data-content="" 
								data-original-title="" 
								data-placement="right" 
								data-userid="<?=$comments->from->id?>"
							<?php }?> 
						><img class="small-face" src="https://graph.facebook.com/<?= $comments->from->id ?>/picture" onerror="ImgError(this);"></a></div>
						
					
					
					
						
						<div class="user-badge">
							<a rel="tooltip-follow" class ="follow_<?=$comments->from->id?>" <?php switch($this->comment_relation[$count2]) { 
								case 'Fanpage':?>
									 class="noclick" data-original-title="You can't Follow an Admin"><span class="btn fc-Fanpage">Admin</span>
								<?break;?>
								<?case 'You':?>
									 class="noclick" data-original-title="This is You"><span class="btn fc-You">You</span>
								<?break;?>
								<?case 'Following':?>
									onclick="unfollow(<?=$comments->from->id?> ,'<?=$comments->from->name?>')" 
									data-original-title="Click to Unfollow this User"><span class="btn fc-Following">Following</span>
								<?break;?>
									
								<?default:?>
									onclick="follow(<?=$comments->from->id?> , '<?=$comments->from->name?>')" 				
									data-original-title="Click to Follow this User"><span class="btn fc-<?= $this->comment_relation[$count2]?>"><?= $this->comment_relation[$count2]?></span>
								<?}?>
							</a>
						</div>	
					

				
					<div class="message">
						<span class="name"><a  
							<? if (!($this->comment_relation[$count2] == 'Fanpage')){?> 
								onclick="userProfile('<?=$comments->from->id?>')"
								rel="popover" 
								data-content="" 
								data-original-title="" 
								data-placement="right" 
								data-userid="<?=$comments->from->id?>"
							<?php }else{?>
								class="noclick"
							<?}?> 
						><?=  $comments->from->name?></a></span>
					<?php if(isset($comments->message)){  
											$reg_ex = "/\n/";
											$message = $this->escape($comments->message);
											if(preg_match_all($reg_ex, $message, $url)) {
												$message= preg_replace($reg_ex, "<br/>", $message);
											} 
											
											$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
										 
											$m = preg_match_all($reg_exUrl, $message, $match); 
											
											if ($m) { 
											    $links=$match[0]; 
											    for ($j=0;$j<$m;$j++) { 
											        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
											    } 
											} 
											
											echo $message; 
												//echo preg_replace($reg_exUrl, "<a href=".$url[0][0]." target=_new>".$url[0][0]."</a> ", $m);
											
										
								}?>
					
			
					</div>
					<div class="social"> 
					 	
						<a rel="tooltip" data-placement="top" class="time noclick" data-original-title="" data-unix-time="<?=  strtotime($comments->created_time)?>"></a>
						
						&middot;
						
						<!--  <img src="/img/news-feed/icon-likes.png" /> -->
						<span class="likes">
					
						<a class="like_<?= $comments->id?>" data-like-count=<?=isset($comments->likes)?$comments->likes:'0'?>  onclick="getLikesList('<?=$comments->id?>',<?=isset($comments->likes)?$comments->likes:'0'?>, true)" rel="tooltip" data-placement="top" data-original-title="Click to See who likes this"><?=isset($comments->likes)?$comments->likes:'0'?></a>
						 
						<a class="like-control like_control_<?= $comments->id?>" rel="tooltip" data-placement="top"
							<?php if ($this->commentlikes[$count2] == 0) {?>
								 data-original-title="Click to like this" onclick="like('<?= $comments->id?>', '<?=$post->type?>_comment', '<?=$comments->from->id?>','<?=$comments->from->name?>')">Like 
							<?}else{?>
								 data-original-title="You like this" onclick="unlike('<?= $comments->id?>', '<?=$post->type?>_comment', '<?=$comments->from->id?>','<?=$comments->from->name?>')">Unlike
							<?php }?>
						</a>
						 </span>	 
				
					 </div>
				
					</li>
							
				<?php $count2 ++;?>
				<?php endforeach; }?>
				
				
				</ul>
				<div class="comment-container">
					<div class="photo"><img class="small-face"  src="https://graph.facebook.com/<?= $this->user_id?>/picture" onerror="ImgError(this);"></div>
				
					<form action="#" class="submit-form" >
					
						<textarea class="comment-box" id="comment_box_<?= $post->id?>" ></textarea>
						<input type=button class="btn-submit" value="Comment" onclick="commentSubmit(this,'<?= $post->id?>','<?= $post->type?>' ,'<?=$post->from->id?>','<?=$post->from->name?>',<?= ($this->latest == 'true')?'true':'false'?> )">
					</form>	
				</div>
				<!-- 
				
					<div class="comment-container">
						<div class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->user_id?>/picture" onerror="ImgError(this);"></div>
					
						<form action="#" class="submit-form" >
						
							<textarea class="comment-box" id="comment_box_<?= $this->postId ?>" ></textarea>
							<input type=button class="btn-submit" value="Comment" onclick="commentSubmit(this,'<?= $this->postId ?>','<?=$this->postType?>' ,'<?=$this->postOwner['user_id']?>','<?=$this->postOwner['user_name']?>',<?= ($this->latest == 'true')?'true':'false'?> )">
						</form>	
					</div>
 				 -->
 		
 			</div>		
 		</div>
 	<?php }else{?>
			<div class="social comment <?=$post->id?>" <?php if(!isset($post->comments->count) || ($post->comments->count == 0)){?>style="display:none"<? }?>>
		
				 <a  onclick="popup_post('<?= $post->id ?>',true )"> 
						<img src="/img/comment.png" />
				 		<span class="comment_<?= $post->id?>">View all Comments</span>
				 		<!-- 
				 		<?//php if($post->comments->count != 1){?> 
					 		View all <span class="comment_<?//= $post->id?>" data-comment-count = <?//php if(isset($post->comments->count)){
							//	echo $post->comments->count; 
							// 	} else {
							//		echo '0'; 
							//	}?>>
					 		<?//php if(isset($post->comments->count)){
							//	echo $post->comments->count; 
							// 	} else {
							//		echo '0'; 
							//	}?>
							</span> 
							comments 
						<?//php }else { ?>
							View all<span class="comment_<?//= $post->id?>" data-comment-count = <?//php if(isset($post->comments->count)){
						//	echo $post->comments->count; 
						// 	} else {
						//		echo '0'; 
						//	}?>>

							</span>
							comments 
					<?//php }?>
					 -->
				</a>
			</div>
			
				<?php }?>
		</li>	
								
		<?php $count ++;?>
		
	<?php endforeach; ?>
		
<?php }?>

<script>
	$('#toppost .comments').enscroll({
	showOnHover: true,
	clickTrackToScroll: false,
	verticalTrackClass: 'track3 popup',
	verticalHandleClass: 'handle3 popup'
	});
</script>