<?php $count = 0?>
<?php foreach($this->top_post as $topPost): ?>
											
		
		<li class="post-container" >
	
			<div class="user">
				<div class="user-badge">
					<a  <? if ($this->relation[$count] != 'You') { ?>
						<? if (($this->relation[$count] != 'Following') /*&& ($this->relation[$count] != 'Friends')*/){?>
								onclick="follow(<?=$topPost['facebook_user_id']?> , '<?= $topPost['fan_first_name'] ?> <?= $topPost['fan_last_name'] ?>', 'follow_<?=$topPost['facebook_user_id']?>')" class ="follow_<?=$topPost['facebook_user_id']?>" 
							<?}else{?>
								 onclick="unfollow(<?=$topPost['facebook_user_id']?> , '<?= $topPost['fan_first_name'] ?> <?= $topPost['fan_last_name'] ?>', 'follow_<?=$topPost['facebook_user_id']?>')" class ="follow_<?=$topPost['facebook_user_id']?>"
							<?}?>
								><span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
							<?php }else{?>
								> <span class="badge badge-You">You</span>
							<?php }?>
							</a>
					
							
				
					</div> 
				<div class="photo"><a data-toggle="modal"
					<? if (!($this->relation[$count] == 'Fanpage')){?> 
						onclick="userProfile('<?=$topPost['facebook_user_id']?>')"
						rel="popover" 
						data-content="" 
						data-original-title="" 
						data-placement="toppost" 
						data-userid="<?=$topPost['facebook_user_id']?>"
					<?php }?>><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $topPost['facebook_user_id']?>/picture" onerror="ImgError(this);">
					</a></div>
					<div class="name"><a data-toggle="modal"
					<? if (!($this->relation[$count] == 'Fanpage')){?> 
						onclick="userProfile('<?=$topPost['facebook_user_id']?>')"
						rel="popover" 
						data-content="" 
						data-original-title="" 
						data-placement="toppost" 
						data-userid="<?=$topPost['facebook_user_id']?>"
					<?php }?>><?= $topPost['fan_first_name'] ?> <?= $topPost['fan_last_name'] ?></a></div>
			</div>
			
			
			
			<div class="post">
				
				<div class="message">
				<? if($topPost['post_message']){
					$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/";
	
				
					$m = $this->escape($topPost['post_message']);
			

					if(preg_match($reg_exUrl, $m, $url)) {
				
		
				       echo preg_replace($reg_exUrl, "<a href=".$url[0]." target=_new>".$url[0]."</a> ", $m);
				
					} else {
				
				       echo $m;
				
					}
				}?>
				</div>							
				<div class="graphical">	
						<?php if (($topPost['post_type'] == 'photo') || ($topPost['post_type']  =='video')) {?>	
							
								<a target="new" href="<?echo $this->escape($topPost['link'])?> "> 
										<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $topPost['picture']))?> '/>
								</a>
							
						<?}elseif ($topPost['post_type']  == 'link') {?>
							<div class="link">
								<div class="link-left">
									<a target="new" href="<?echo $this->escape($topPost['link'])?> "> 
										<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $topPost['picture']))?> '/>
									</a>
								</div>
							
								<div class="link-right">
									<a target="new" href="<?echo $this->escape($topPost['link'])?> ">
										<?= (isset($topPost['name'])?$this->escape($topPost['name']): $this->escape($topPost['link']))?>
										<?php  if (isset($topPost['caption'])){?>
										</br>
										<?php echo $this->escape($topPost['caption']);?>: <?php }?> 
										
										
										<?php if (isset($topPost['description'])){?>
										<?=$this->escape($topPost['description'])?> 
										<?php }?>
										
									</a>
								</div>
							</div>
						<?}?>
				</div>
			
				
			</div>
				
				
		 <div class="social"> 
			
			
				<?php if ($this->likes[$count] == 0) {?>
					<a class="like_control_<?= $topPost['post_id']?>"  onclick="like('<?= $topPost['post_id']?>', '<?= $topPost['post_type']?>', '<?=$topPost['facebook_user_id']?>','<?= $topPost['fan_first_name'] ?> <?= $topPost['fan_last_name'] ?>' )" >Like</a>   
				<?}else{?>
					<a class="like_control_<?= $topPost['post_id']?>"  onclick="unlike('<?= $topPost['post_id']?>', '<?= $topPost['post_type']?>', '<?=$topPost['facebook_user_id']?>','<?= $topPost['fan_first_name'] ?> <?= $topPost['fan_last_name'] ?>')">Unlike</a>   
				<?php }?>
		
				 &middot;
		
				 <a  onclick=" comment_popup('<?= $topPost['post_id']?>', 10, true)">Comment </a>
		
				&middot;
				
				<span class="time" title="<?= strtotime($topPost['created_time'])?>"><?=strtotime($topPost['created_time'])?> </span>
			<br/>
		</div>
			
	<div class="social like <?=$topPost['post_id']?>"  <?php if(!isset($topPost['post_likes_count']) || ($topPost['post_likes_count'] == 0)){?>style="display:none"<?php }?>>
		
		
				<!--  <img src="/img/news-feed/icon-likes.png" />-->
			<a>
				<img src = "/img/thumbsup.png" />
				<span class="like_<?= $topPost['post_id']?>"><? if(isset($topPost['post_likes_count'])){echo $topPost['post_likes_count'];}else{echo '0';} ?>
					
					<?php if($topPost['post_likes_count'] == 1){?>person<?php }else{?>people<?php }?> 
				
				</span>
				likes this.
			</a>		
		
	
	</div>

	<?php if(isset($topPost['post_comments_count']) && ($topPost['post_comments_count'] != 0)){?>
	<div class="social comment <?=$topPost['post_id']?>">
	
			 <a   onclick=" comment_popup('<?= $topPost['post_id']?>', 10, true)">
			 	<?php if($topPost['post_comments_count'] != 1){?> <img src="/img/comment.png" />
			 		View all <span class="comment_<?= $topPost['post_id']?>">
			 		<?php if(isset($topPost['post_comments_count'])){
						echo $topPost['post_comments_count']; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>
					</span> 
					comments 
				<?php }else { ?>
					View all<span class="comment_<?= $topPost['post_id']?>">
			 		
					 
					
					</span>
					comments 
				<?php }?>
				</a>
			
	
	
	</div>
	<?php }?>
				
	
			
											
										
	</li>

<?php $count ++;?>
<?php endforeach; ?>

<?php if (!($this->top_post)) {?>
	
		<li class="post-container" >

			<div class="user">
	
			</div>
			
				<div class="post">
					<div class="message">
						There are no Top Posts this week
					</div>							
				</div>

						
	</li>				
<?php }?>
		