
	<div class="row">
		<div class="span12">
			<div class="top-fan">
				
				
			
					<div class="row box">
					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/top-fan-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Top Fans this Week
						</div>
						<div class="tip2">
							The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!
						</div>
						<!--  <div class="tip">
								<a rel="tooltip" title="The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!">?</a>
							</div>-->
					</div>
						<?php $count = 0; ?> 
						<?php foreach($this->top_fans as $top_fan):  ?>
						
						<?php $username= $top_fan['fan_first_name'].' '.$top_fan['fan_last_name'];?>
						<?php $displayname= $username;?>
							
						<?php 
							if (strlen($username)>16){
								if(strlen($top_fan['fan_first_name'])>16){
									$displayname = substr($top_fan['fan_first_name'], 0, 13).'...'	;
								}else if (strlen($top_fan['fan_first_name'])>13){
									$displayname = $top_fan['fan_first_name'];
								}else{
									$displayname = $top_fan['fan_first_name'] .' '. substr($top_fan['fan_last_name'], 0,1) .'.';
								}
						}?>
						
						
						
						
						<?php if ($count == 0){?>
						
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>

									<div class="user">
										<div class="photo">
											<a  data-userid="<?= $top_fan['facebook_user_id'] ?>"
										
												onclick="userProfile('<?= $top_fan['facebook_user_id'] ?>')"
												 rel="popover" data-content="" data-original-title=""
												data-placement="top-left">
												<img class="face"
												width="35" height="35"
												src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"
												onerror="ImgError(this);">
											</a>
										</div>		
												
										<div class="name first">		
											<a  data-userid="<?= $top_fan['facebook_user_id'] ?>"
											
												onclick="userProfile('<?= $top_fan['facebook_user_id'] ?>')"
												rel="popover" data-content="" data-original-title=""
												data-placement="top-left"><?= $displayname ?>						
											</a>
										</div>
									</div>
			
    								<ul class="stats">
										<li >
											<div class="stats-block"><img src="/img/post.png" /><h5><?= $this->top_fans_stat[0]['total_posts']?></h5>	
											</div>
										</li>
										<li >
											<div class="stats-block"><img src="/img/thumbsup.png" /><h5><?= $this->top_fans_stat[0]['total_likes']?></h5>
											</div>
										</li>
										<li>
											<div class="stats-block"><img src="/img/comment.png" /><h5><?= $this->top_fans_stat[0]['total_comments']?></h5>
											</div>
										</li>
										<li >
											<div class="stats-block"><img src="/img/rthumbsup.png" /><h5><?= $this->top_fans_stat[0]['total_get_comments']?></h5>
											</div>
										</li>
										<li  >
											<div class="stats-block"><img src="/img/rcomment.png" /><h5><?= $this->top_fans_stat[0]['total_get_likes']?></h5>
											</div> 
										</li>
									
									</ul>
							
									
									
									<div class="points">
										<h3>
											<?= $top_fan['number_of_posts'] ?>
										</h3>
										<span>Points <br/>
										</span>
										<a rel="tooltip-follow" class ="follow_<?=$top_fan['facebook_user_id']?>"<?php switch($this->topFanArray[$count]) { 
											case 'You':?>
												 data-original-title="This is You"><span class="badge badge-You">You</span>
											<?break;?>
											<?case 'Following'?>
												onclick="unfollow(<?= $top_fan['facebook_user_id']?> ,'<?= $top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>')" 
												data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
											<?break;?>
												
											<?default:?>
												onclick="follow(<?= $top_fan['facebook_user_id']?> , '<?= $top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>')" 
												data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->topFanArray[$count]?>"><?=$this->topFanArray[$count]?></span>
											<?}?>
										</a>
								
									</div>
								</div>
							</li>

						</ul>
						<?php }else{ ?>
							<?php if ($count == 1){?>
							<ul id="top-fans-collapse" class="top-list">
							<?php }?>
								<li>
									<div class="ranker ">
										<div class="rank">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
											<div class="photo"><a  data-userid="<?= $top_fan['facebook_user_id'] ?>"
									
												onclick="userProfile('<?= $top_fan['facebook_user_id'] ?>')"
												rel="popover" data-content="" data-original-title=""
												data-placement="top-left"><img class="face"
													width="35" height="35"
													src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"
													onerror="ImgError(this);">
												</a></div>	
													
													
												<div class="name"><a  data-userid="<?= $top_fan['facebook_user_id'] ?>"
											
												onclick="userProfile('<?= $top_fan['facebook_user_id'] ?>')"
												rel="popover" data-content="" data-original-title=""
												data-placement="top-left"><?= $displayname ?>
											</a></div>
											
										</div>
										
										<ul class="stats">
											<li >
												<div class="stats-block"><img src="/img/post.png" /><h5><?= $this->top_fans_stat[$count]['total_posts']?></h5>	
												</div>
											</li>
											<li >
												<div class="stats-block"><img src="/img/thumbsup.png" /><h5><?= $this->top_fans_stat[$count]['total_likes']?></h5>
												</div>
											</li>
											<li>
												<div class="stats-block"><img src="/img/comment.png" /><h5><?= $this->top_fans_stat[$count]['total_comments']?></h5>
												</div>
											</li>
											<li >
												<div class="stats-block"><img src="/img/rthumbsup.png" /><h5><?= $this->top_fans_stat[$count]['total_get_comments']?></h5>
												</div>
											</li>
											<li  >
												<div class="stats-block"><img src="/img/rcomment.png" /><h5><?= $this->top_fans_stat[$count]['total_get_likes']?></h5>
												</div> 
											</li>
										
										</ul>
										
										<div class="points">
											<h3>
												<?= $top_fan['number_of_posts'] ?>
											</h3>
											<span>Points <br/>
											</span>
											<a rel="tooltip-follow" class ="follow_<?=$top_fan['facebook_user_id']?>"<?php switch($this->topFanArray[$count]) { 
												case 'You':?>
													 data-original-title="This is You"><span class="badge badge-You">You</span>
												<?break;?>
												<?case 'Following'?>
													onclick="unfollow(<?= $top_fan['facebook_user_id']?> ,'<?= $top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>')" 
													data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
												<?break;?>
													
												<?default:?>
													onclick="follow(<?= $top_fan['facebook_user_id']?> , '<?= $top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>')" 
													data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->topFanArray[$count]?>"><?=$this->topFanArray[$count]?></span>
												<?}?>
											</a>
					
									
										</div>
									</div>
								</li>
	
							<?php }?>
							
							<?php $count ++; ?>
					
							<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
							<ul class="top-list first">
								<li>
									<div class="ranker first">
										<div class="rank first">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
										<div class="points"></div>
									</div>
								</li>
								<?php $count++;?>
							</ul>
						<?php }?>
						
						
						<?php for ( ;$count<5; $count++){ ?>
						
							<?php if ($count == 1){?>
							<ul  id="top-fans-collapse" class="top-list ">		
							<?php }?>
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
										<div class="points"></div>
									</div>
								</li>
								
							
						<?}?>
						<?}?>		
							</ul>
						
							<ul class="top-list">
								<li>
									<div class="ranker">
										<div class="rank">
											<? if (strlen($this->topFanYou['my_rank'])== 1){?>
											<h1>
												<?= $this->topFanYou['my_rank']?>
											</h1>
											<?php }elseif (strlen($this->topFanYou['my_rank'])== 2) { ?>
											<h2>
												<?= $this->topFanYou['my_rank']?>
											</h2>
											<?php }elseif (strlen($this->topFanYou['my_rank'])== 3) { ?>
											<h3>
												<?= $this->topFanYou['my_rank']?>
											</h3>
											<?php }else{?>
											<h1>*</h1>
											<?php }?>
										</div>
										
										<div class="user">
											<div class="photo">
												<img class="face" width="35" height="35"
													src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
													onerror="ImgError(this);">
											</div>
											<div class="name">
												YOU
											</div>
										</div>
										<ul class="stats">
											<li >
												<div class="stats-block"><img src="/img/post.png" /><h5><?= $this->your_stat[0]['total_posts']?></h5>	
												</div>
											</li>
											<li >
												<div class="stats-block"><img src="/img/thumbsup.png" /><h5><?= $this->your_stat[0]['total_likes']?></h5>
												</div>
											</li>
											<li>
												<div class="stats-block"><img src="/img/comment.png" /><h5><?=$this->your_stat[0]['total_comments']?></h5>
												</div>
											</li>
											<li >
												<div class="stats-block"><img src="/img/rthumbsup.png" /><h5><?= $this->your_stat[0]['total_get_comments']?></h5>
												</div>
											</li>
											<li  >
												<div class="stats-block"><img src="/img/rcomment.png" /><h5><?= $this->your_stat[0]['total_get_likes']?></h5>
												</div> 
											</li>
										
										</ul>
										<div class="points">
											<h3>
												<?= isset( $this->topFanYou['number_of_posts'])?$this->topFanYou['number_of_posts']:'?'?>
											</h3>
											<span>Points<br />
											</span>
											<a rel="tooltip-follow" data-original-title="This is You">
											<span class="badge badge-You">
												You
											</span></a>
										</div>
									</div>
								</li>
							</ul>
						
				</div>

			</div><!-- topfan -->
		</div><!-- span -->
	</div><!-- row -->
	<div class= "row">
		<div class="span6">
			<div class="fan-favorite">
				
				<div class="row box">
				
					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/fan-fav-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Fan Favorites this Week 
							
						</div>
						<div class="tip2">
							This list of fans represents the people who have garnered the most activity from others on the page.  Other fans love talking to them!
						</div>
						<!--  <div class="tip">
								<a rel="tooltip" title="This list of fans represents the people who have garnered the most activity from others on the page.  Other fans love talking to them!">?</a>
						</div>-->
					</div>
					<?php $count = 0; ?>
					<?php foreach($this->most_popular as $popular):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list first" >
						<li>
							<div class="ranker first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="user">
									<div class="photo"><a  data-userid="<?= $popular['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $popular['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
											
											
											<div class="name first"><a  data-userid="<?= $popular['facebook_user_id'] ?>"
					
										onclick="userProfile('<?= $popular['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left">
											<?= $popular['fan_first_name'] ?></a>
									</div>
									
								</div>

								<div class="points">
									<h3>
										<?= $popular['count'] ?>
									</h3>
									<span>Props<br/>
									</span>
									<a rel="tooltip-follow" class ="follow_<?=$popular['facebook_user_id']?>"<?php switch($this->popularArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $popular['facebook_user_id']?> ,'<?= $popular['fan_first_name'].' '.$popular['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $popular['facebook_user_id']?> , '<?= $popular['fan_first_name'].' '.$popular['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->popularArray[$count]?>"><?=$this->popularArray[$count]?></span>
										<?}?>
									</a>
								
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="fan-favorite-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="ranker ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="user">
									<div class="photo"><a data-userid="<?= $popular['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $popular['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
											
											
											<div class="name"><a data-userid="<?= $popular['facebook_user_id'] ?>"
								
										onclick="userProfile('<?= $popular['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><?= $popular['fan_first_name'] ?></a></div>
									
								</div>
								<div class="points">
									<h3>
										<?= $popular['count'] ?>
									</h3>
									<span>Props<br/>
										</span>
									<a rel="tooltip-follow" class ="follow_<?=$popular['facebook_user_id']?>"<?php switch($this->popularArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										
										<?case 'Following'?>
											onclick="unfollow(<?= $popular['facebook_user_id']?> ,'<?= $popular['fan_first_name'].' '.$popular['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $popular['facebook_user_id']?> , '<?= $popular['fan_first_name'].' '.$popular['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->popularArray[$count]?>"><?=$this->popularArray[$count]?></span>
										<?}?>
									</a>
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="fan-favorite-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->popularYou['my_rank'])== 1){?>
										<h1>
											<?= $this->popularYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->popularYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->popularYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="user">
									<div class="photo">
										<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);">
									</div>
									<div class="name">
										YOU
									</div>
									</div>
									<div class="points">
										<h3>
											<?= isset($this->popularYou['count'])? $this->popularYou['count']:'?'?>
										</h3>
										<span>Props<br/>
										</span>
										<a rel="tooltip-follow" data-original-title="This is You">
										<span class="badge badge-You">
											You
										</span></a>
									</div>
								</div>
							</li>
						</ul>
				<button class="btn-more" id="fan-favorite-btn" data-toggle="collapse"
						data-target="#fan-favorite-collapse">More +</button>
				</div>
			
			</div><!-- fanfav -->
		</div><!-- span -->
		<div class="span6">
			<div class="top-talker">
				
				<div class="row box">
					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/top-talker-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
						Top Talkers this Week 
							
						</div>
						<!--  <div class="tip">
								<a rel="tooltip" title="These people have posted the most on the page.  Do they talk too much?  You decide!">?</a>
							</div>-->
						<div class="tip2">
							These people have posted the most on the page.  Do they talk too much?  You decide!
						</div>
					</div>
					<?php $count = 0; ?>
					<?php foreach($this->top_talker as $talker):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list first">
						<li>
							<div class="ranker first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="user">
									<div class="photo"><a  data-userid="<?= $talker['facebook_user_id'] ?>"
								
										onclick="userProfile('<?= $talker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
											
											<div class="name first"><a  data-userid="<?= $talker['facebook_user_id'] ?>"
							
										onclick="userProfile('<?= $talker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><?= $talker['fan_first_name'] ?>
									</a></div>
									
								</div>

								<div class="points">
									<h3>
										<?= $talker['number_of_posts'] ?>
									</h3>
									<span>Posts</span>
									<br/>
									<a rel="tooltip-follow" class ="follow_<?=$talker['facebook_user_id']?>"<?php switch($this->talkerArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $talker['facebook_user_id']?> ,'<?= $talker['fan_first_name'].' '.$talker['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $talker['facebook_user_id']?> , '<?= $talker['fan_first_name'].' '.$talker['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->talkerArray[$count]?>"><?=$this->talkerArray[$count]?></span>
										<?}?>
									</a>
							
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="top-talker-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="ranker ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="user">
									<div class="photo"><a data-userid="<?= $talker['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $talker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
											
											<div class="name"><a data-userid="<?= $talker['facebook_user_id'] ?>"
									<? if (!($this->relation[$count] == 'Fanpage')){?>
										onclick="userProfile('<?= $talker['facebook_user_id'] ?>')"
										<?}?> rel="popover" data-content="" data-original-title=""
										data-placement="top"><?= $talker['fan_first_name'] ?></a>
									</div>
									
								</div>
								<div class="points">
									<h3>
										<?= $talker['number_of_posts'] ?>
									</h3>
									<span>Posts</span>
									<br/>
									<a rel="tooltip-follow" class ="follow_<?=$talker['facebook_user_id']?>"<?php switch($this->talkerArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $talker['facebook_user_id']?> ,'<?= $talker['fan_first_name'].' '.$talker['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $talker['facebook_user_id']?> , '<?= $talker['fan_first_name'].' '.$talker['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->talkerArray[$count]?>"><?=$this->talkerArray[$count]?></span>
										<?}?>
									</a>
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
						<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="top-talker-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->talkerYou['my_rank'])== 1){?>
										<h1>
											<?= $this->talkerYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->talkerYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->talkerYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->talkerYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->talkerYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="user">
									<div class="photo">
										<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);"> 
									</div>
									<div class="name">
										YOU
									</div>
									</div>
									<div class="points">
										<h3>
											<?= isset($this->talkerYou['number_of_posts'])?$this->talkerYou['number_of_posts']:'?'?>
										</h3>
										<span>Posts</span> <br/>
										<a rel="tooltip-follow" data-original-title="This is You">
										<span class="badge badge-You">
											You
										</span></a>
									</div>
								</div>
							</li>
						</ul>
						
						
				<button class="btn-more" id="top-talker-btn" data-toggle="collapse" data-target="#top-talker-collapse">More +</button>
				</div>

			</div><!-- toptalker -->
		</div><!-- span -->
	</div><!-- row -->

	
	
	<div class="row">
		<div class="span6">
			<div class="top-clicker">
				
				<div class="row box">
					<div class="title nopic">
						<!-- <div class="title-icon">
							<img src="/img/news-feed/top-clicker-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
						Top Clickers this Week
							
						</div>
						<!-- <div class="tip">
								<a rel="tooltip" title="Like, like, and like!  These people have clicked Like the most!">?</a>
							</div> -->
						<div class="tip2">
							Like, like, and like!  These people have clicked Like the most!
						
						</div>
					</div>
					<?php $count = 0; ?>
					<?php foreach($this->top_clicker as $clicker):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list first">
						<li>
							<div class="ranker first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="user">
									<div class="photo"><a  data-userid="<?= $clicker['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $clicker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
											
											<div class="name first"><a  data-userid="<?= $clicker['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $clicker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><?= $clicker['fan_first_name'] ?></a>
									</div>
									
								</div>

								<div class="points">
									<h3>
										<?= $clicker['number_of_likes'] ?>
									</h3>
									<span>Likes</span> <br/>
									<a rel="tooltip-follow" class ="follow_<?=$clicker['facebook_user_id']?>"<?php switch($this->clickerArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $clicker['facebook_user_id']?> ,'<?= $clicker['fan_first_name'].' '.$clicker['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $clicker['facebook_user_id']?> , '<?= $clicker['fan_first_name'].' '.$clicker['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->clickerArray[$count]?>"><?=$this->clickerArray[$count]?></span>
										<?}?>
									</a>
									
									
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="top-clicker-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="ranker ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="user">
									<div class="photo"><a  data-userid="<?= $clicker['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $clicker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
										<div class="name"><a  data-userid="<?= $clicker['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $clicker['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top-left"><?= $clicker['fan_first_name'] ?></a></div>
									
								</div>
								<div class="points">
									<h3>
										<?= $clicker['number_of_likes'] ?>
									</h3>
									<span>Likes</span><br/>
									<a rel="tooltip-follow" class ="follow_<?=$clicker['facebook_user_id']?>"<?php switch($this->clickerArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $clicker['facebook_user_id']?> ,'<?= $clicker['fan_first_name'].' '.$clicker['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $clicker['facebook_user_id']?> , '<?= $clicker['fan_first_name'].' '.$clicker['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->clickerArray[$count]?>"><?=$this->clickerArray[$count]?></span>
										<?}?>
									</a>
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="top-clicker-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
									<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->clickerYou['my_rank'])== 1){?>
										<h1>
											<?= $this->clickerYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->clickerYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->clickerYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->clickerYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->clickerYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="user">
									<div class="photo">
										<img class="face" width="35" height="35"
												src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
												onerror="ImgError(this);">
									</div>
									<div class="name">
										YOU
									</div>
									</div>
									<div class="points">
										<h3>
											<?= (isset($this->clickerYou['number_of_likes']))?$this->clickerYou['number_of_likes']:'?'?>
										</h3>
										<span>Likes</span><br/>
										<a rel="tooltip-follow" data-original-title="This is You"><span class="badge badge-You">
											You
										</span></a>
									</div>
								</div>
							</li>
						</ul>
				<button class="btn-more" id="top-clicker-btn" data-toggle="collapse"
						data-target="#top-clicker-collapse">More +</button>
				</div>
		
					
			
			</div><!-- topclicker -->
		</div>
		<div class="span6">
			<div class="top-followed">
				
				<div class="row box">
					<div class="title nopic">
						<!-- <div class="title-icon">
							<img src="/img/news-feed/fan-fav-icon.jpg" />
						</div> -->
						<div class="title-header nopic">
						Top Followed
							
						</div>
						
						<div class="tip2">
							These people have got the most followers!  Talk about being popular!
						</div>
						
						<!--  <div class="tip">
								<a rel="tooltip" title="These people have got the most followers!  Talk about being popular!">?</a>
						</div>-->
					</div>
					<?php $count = 0; ?>
					<?php foreach($this->top_followed as $followed):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list first">
						<li>
							<div class="ranker first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="user">
									<div class="photo"><a data-userid="<?= $followed['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $followed['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $followed['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
											
											<div class="name first"><a data-userid="<?= $followed['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $followed['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><?= $followed['fan_first_name'] ?></a>
									</div>
									
								</div>

								<div class="points">
									<h3>
										<?= $followed['count'] ?>
									</h3>
									<span>Followers</span> <br />
									<a rel="tooltip-follow" class ="follow_<?=$followed['facebook_user_id']?>"<?php switch($this->followedArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $followed['facebook_user_id']?> ,'<?= $followed['fan_first_name'].' '.$followed['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $followed['facebook_user_id']?> , '<?= $followed['fan_first_name'].' '.$followed['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->followedArray[$count]?>"><?=$this->followedArray[$count]?></span>
										<?}?>
									</a>
								
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="top-followed-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="ranker ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="user">
									<div class="photo"><a  data-userid="<?= $followed['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $followed['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $followed['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"></a></div>
											
									<div class="name"><a  data-userid="<?= $followed['facebook_user_id'] ?>"
									
										onclick="userProfile('<?= $followed['facebook_user_id'] ?>')"
										rel="popover" data-content="" data-original-title=""
										data-placement="top"><?= $followed['fan_first_name'] ?></a></div>
									
								</div>
								<div class="points">
									<h3>
										<?= $followed['count'] ?>
									</h3>
									<span>Followers</span>
									<br/>
									<a rel="tooltip-follow" class ="follow_<?=$followed['facebook_user_id']?>"<?php switch($this->followedArray[$count]) { 
										case 'You':?>
											 data-original-title="This is You"><span class="badge badge-You">You</span>
										<?break;?>
										<?case 'Following'?>
											onclick="unfollow(<?= $followed['facebook_user_id']?> ,'<?= $followed['fan_first_name'].' '.$followed['fan_last_name']?>')" 
											data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
										<?break;?>
											
										<?default:?>
											onclick="follow(<?= $followed['facebook_user_id']?> , '<?= $followed['fan_first_name'].' '.$followed['fan_last_name']?>')" 
											data-original-title="Click to Follow this User"><span class="badge badge-<?=$this->followedArray[$count]?>"><?=$this->followedArray[$count]?></span>
										<?}?>
									</a>
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="top-followed-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
										<div class="photo"></div>
										<div class="name"></div>
									</div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>
						</ul>
						
						<ul class="top-list">
							<li>
								<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->followedYou['my_rank'])== 1){?>
										<h1>
											<?= $this->followedYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->followedYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->followedYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->followedYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->followedYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="user">
									<div class="photo">
										<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);">
									</div>
									<div class="name">
										YOU
									</div>
									</div>
									<div class="points">
										<h3>
											<?= isset($this->followedYou['count'])?$this->followedYou['count']:'?'?>
										</h3>
										<span>Followers</span><br/>
										<a rel="tooltip-follow" data-original-title="This is You">
										<span class="badge badge-You">
											You
										</span></a>
									</div>
								</div>
							</li>
						</ul>
						
						<button class="btn-more" id="top-followed-btn" data-toggle="collapse"
						data-target="#top-followed-collapse">More +</button>
				</div>
			
					
		
			</div><!-- topfollowed -->
		</div>
	</div><!-- row -->
