<?php $count=0;?>
<ul class="followlist">
<?php if(count($this->result)==0){?>
	<li class="border-dark" >

	<div class="name">No users</div>

	</li>
	<?php $count++;?>
<?php }?>



<?php foreach ($this->result as $user):?>	
	

		<li class="border-light" >

		<div class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $user['facebook_user_id'] ?>/picture"></div>
		<div class="name">
			<a href="#" onclick="userProfile('<?= $user['facebook_user_id']?>', true)"><?= $user['facebook_user_first_name'] .' '. $user['facebook_user_last_name'] ?></a>
			
		</div>
	
		
	
	</li>
<?php $count++;?>
<?php endforeach; ?>

	<?php if ($count < 5){?>

	<?php for (;$count<5; $count++){ ?>
	<?php if ($count == 1){?>
	<ul class="followlist">
		<?php }?>
		<li>
			<div class="border-dark">
			
				
				</div>
		
		</li>
		<?}

		?>
		<?}
		?>
	</ul>