<div class="row">
	<div class="span7">
	<div id="myprofile">
		<div id="general-stats-container">
		<div class="title">
			<div class="title-icon">
				<a href="">
					<img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture" onerror="ImgError(this);">
				</a>
			</div>
			<div class="title-header">
				<?echo $this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name ?>'s Profile
			</div>
			<div class="tip">
				<a rel="tooltip" data-original-title='This is your FanCrank Profile! Check out your points, experience, badges, and other statistics here.'>
					?
				</a>
			</div>
		</div>
		
		<div class="row box">
			<div class="stats" >
					<div class="post-container">
						<div class="profile-block" id="level-container">
							<h3>Level</h3>
							<div class="level">
								<?= $this->fan->fan_level?>
							</div>
						</div>
						<div class="profile-block vertical-center" id="points-container">
							<h3><?= $this->fan->fan_currency?></h3>
							Points
						</div>
						<div class="profile-block" id="exp-container">
							<h4>Fan Experience</h4>
							<div class="progress">
								<div class="bar" style="width: <?= $this->fan_exp_percentage?>%;"></div>
							</div>
							<h5>
								<?=$this->fan_exp?>/<?=$this->fan_level_exp?>
								<br />
								<?=$this->fan_exp_required?>
								Until Next Level
							</h5>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id ="upcoming-badges-container">
		<div class="title nopic">
	
			<div class="title-header nopic">
				Upcoming Badges
			</div>
			<div class="tip">
				<a rel="tooltip" data-original-title='These are your upcoming badges'>
					?
				</a>
			</div>
		</div>
		<div class="row box">
			<div class="post-container">
					<?php $badge = $this->badges?>
					
					<? function cmp($a, $b){
						
							if ($a['percentage'] == $b['percentage']){
								return 0;
							}
							if ($a['percentage'] > $b['percentage']){
								return -1;
							}
							return 1;
						}?>
					
					
					<? usort($badge, 'cmp')?>
					
					<? $j=0; $i=0?>
					<? while ($i < 5){
						if($badge[$j]['percentage']!=1){
							Zend_Debug::dump($badge[$j]);
							$i++;
						}
						$j++;
					}?>
				
					<!--
					<?php $badgeName = array_keys($this->badges)?>
					
					<?php for($i = 0 ; $i < count($badgeName); $i++){?> 
					
						<?php $badgeQuantity = array_keys($badge[$badgeName[$i]]);?> 
							<?php for($j = 0 ; $j < count($badgeQuantity); $j++){?>
							
							<?php if (($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] != 0 ) && ($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] != 1 )){?>
							<a class="badge_container" rel="tooltip" data-placement="top" 
							data-original-title="<img src='<?= $badge[$badgeName[$i]][$badgeQuantity[$j]]['picture']?>' >
							<?= str_replace('[quantity]',  $badgeQuantity[$j], $badge[$badgeName[$i]][$badgeQuantity[$j]]['description'])?>">
							
							<img src="<?= $badge[$badgeName[$i]][$badgeQuantity[$j]]['picture']?>"
							<?php if ($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] != 1){?> style="opacity:0.5" <?php }?>/>
							
							<?php if ($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] != 1){?>
							<span><?= $badgeName[$i]?>-<?=$badgeQuantity[$j]?> <?= round($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] *100)?>% Completed</span>
							<?php $j = count($badgeQuantity) +1;?><?php }?>
							</a><br/>
							
						<?}?>
					
					
				<?}?><?}?>
				-->
			</div>
		</div></div>
		<div id="follow-list-container">		
			<div class="half" >	
				<div class="title nopic">
					<div class="title-header nopic">
						Followed by	<?= $this->follower['0']['Follower']?> Fans
					</div>
				</div>
				<div class="row box">
					<div id="followerslist"></div>
					<button class="btn-more" onclick="getFollowersList('<?=$this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name?>', '<?=$this->facebook_user->facebook_user_id?>', 0)">
						View Full List
					</button>	
				</div>
					
			</div>			
						
			<div class="half" >
				<div class="title nopic">
					<div class="title-header nopic">
						Following <?= $this->following['0']['Following']?> Fans
					</div>
				</div>
				<div class="row box">
					<div id="followinglist"></div>
					<button class="btn-more" onclick="getFollowingList('<?=$this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name?>', '<?=$this->facebook_user->facebook_user_id?>', 0)">
						View Full List
					</button>	
				</div>				
			</div>
		</div>	
		<div id="other-stats-container">
			<div class="title nopic">
	
				<div class="title-header nopic">
					Other Statistics
				</div>
				<div class="tip">
					<a rel="tooltip" data-original-title="These are some of your other statistics. Such as how many posts, comments and likes you've given and likes and comment's you've recieved.">
						?
					</a>
				</div>
			</div>
			<div class="row box">
				<div class="post-container">
					<div class="half" >
						<h4>Fancrank User Since:</h4>
						<?= date("F d Y", strtotime($this->fan->first_login_time))?>
						<br />
						<br />
						<h4>Location</h4>
						<?php if (isset($this->fan->fan_country)) {?>
							<?php if (isset($this->fan->fan_location)){?>
								<?= $this->fan->fan_location?>,
							<?php }?>
							<?= $this->fan->fan_country?>
						<?php }else{?>
							Unknown
						<?php }?>							
					</div>
					<div class="half">
						<h4>Other Statistics:</h4>
						<img src="/img/post.png" />Total Posts Made: <?=$this->stat_post?>
						<br />
						<img src="/img/thumbsup.png" />Total Likes Made: <?=$this->stat_like?>
						<br />
						<img src="/img/comment.png" />Total Comments Made: <?=$this->stat_comment?>
						<br />
						<img src="/img/rthumbsup.png" />Total Recieved Likes: <?=$this->stat_get_like?>
						<br />
						<img src="/img/rcomment.png" />Total Recieved Comments: <?=$this->stat_get_comment?>
						<br />
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	<div class="span5">
	
		<div id = "recent-activities-container">
		<div class="title">
			<div class="title-header nopic">
				Recent Activities
			</div>
			<div class="tip">
				<a rel="tooltip" data-original-title='This is your list of recent actitivies, remember that it may not be accurate as it does require time for it to sync up with Facebook'>?</a>
			</div>
		</div>
		<div class="row box">
			<div class="scrollbox">
				<ul id="recent_activities"></ul>
			</div>
		</div>
	</div></div>
</div>

<script>
	$('#recent_activities').enscroll({
		showOnHover: true,
		clickTrackToScroll: false,
		verticalTrackClass: 'track3',
		verticalHandleClass: 'handle3'
	});
</script>
