<style>
/****************************/

.notification .mini {
  margin-top: 12px;
  float: right;
  list-style-type: none;
  padding: 0;
}

.notification .mini > li {
  float: left;
  margin-left: 20px;
  background: white;
  position: relative;
  -webkit-border-radius: 3px 3px 3px 3px;
  -moz-border-radius: 3px 3px 3px 3px;
  border-radius: 3px 3px 3px 3px;
  -webkit-box-shadow: 1px 1px 1px #4b4b4b, inset 1px 1px 0px 1px #222222;
  -moz-box-shadow: 1px 1px 1px #4b4b4b, inset 1px 1px 0px 1px #222222;
  box-shadow: 1px 1px 1px #4b4b4b, inset 1px 1px 0px 1px #222222;
}

.notification .mini > li:hover {
  background: #222222;
}
.notification .mini > li.open {
  margin-left: 18px;
}
.notification .mini > li.open > a {
  color: #080808;
  background: #ffffff;
  border: 1px solid #222222;
  border-bottom: 0;
}

.notification .mini > li.open > a img {
  opacity: 1;
  filter: alpha(opacity=1);
}
.notification .mini > li.open > a:hover {
  color: #080808;
}
.notification .mini > li > a {
  color: #888888;
  font-size: 12px;
  line-height: 20px;
  padding: 5px 8px 3px 8px;
  display: block;
  position: relative;
  z-index: 1001;
}

.notification .mini > li > a img {
  margin-bottom: 2px;
  margin-right: 2px;
  opacity: 0.3;
  filter: alpha(opacity=3);
}

.notification .mini > li > a .label {
  position: absolute;
  top: -5px;
  left: 93%;
}
.notification .mini > li > a:hover {
  text-decoration: none;
  color: #ffffff;
}
.notification .mini > li > a:hover img {
  opacity: 1;
  filter: alpha(opacity=1);
}
</style>
<div class="row">
	<div class="notification">
		<ul class="mini widget">
			<li class="dropdown pendingContainer">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-exclamation-sign"></i>
						Badge Notification: </a><div class="label label-important"><span id="badge-notification-count">0</span></div>
				</li>
		</ul>					
	</div>
	<div class="span8">
	<div id="myprofile">
		<div id="general-stats-container">
		
		
			<div class="row box">
				<div class="title nopic">
					
					<div class="title-header nopic">
						Your Profile
					</div>
					<!--  <div class="tip">
						<a rel="tooltip" data-original-title='This is your FanCrank Profile! Check out your points, experience, badges, and other statistics here.'>
							?
						</a>
					</div>-->
				</div>
				<div class="row-fluid">
					<div class="span6 post-container noline">
						<div class="user noline">
						
								<div class="photo">
									<a><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture" onerror="ImgError(this);"></a>
						
								</div>
								<div class="level">
									<?= $this->fan->fan_level?>
								</div>
								<div class="name">
									<a><?echo $this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name ?></a>
								
								</div>	
								
								<div class="user-description tip2 italic" onkeyup="charcheck()">
							
								<?= substr($this->fan->message, 0, 160)?>
								
								</div><a class="user-description-button" onclick="editdescription()">Edit</a>	
								
						</div>
					
					</div>
					<div class="span6">
						<div style="padding:5px; margin-top:29px">
							<div class="progress" style="height:50px;width:50px;margin:10px 11px 10px;display:inline-block">
								<div class="bar" style="width: 100%;height:50px"></div>
								<a data-original-title="Some Badge" 
								rel="tooltip" data-placement="top-left" style="float:left; position:relative;top:-50px;" >
									<img src="/img/badges/generic.png"/>
								</a>
							</div>
							<div class="progress" style="height:50px;width:50px;margin:10px 11px 10px;display:inline-block">
								<div class="bar" style="width: 100%;height:50px"></div>
								<a data-original-title="Some Badge" 
								rel="tooltip" data-placement="top-left" style="float:left; position:relative;top:-50px;" >
									<img src="/img/badges/generic.png"/>
								</a>
							</div>
							<div class="progress" style="height:50px;width:50px;margin:10px 11px 10px;display:inline-block">
								<div class="bar" style="width: 100%;height:50px"></div>
								<a data-original-title="Some Badge" 
								rel="tooltip" data-placement="top-left" style="float:left; position:relative;top:-50px;" >
									<img src="/img/badges/generic.png"/>
								</a>
							</div>
						
						</div>
					</div>
				</div>
				
				<div class="post-container noline">
					<div class="row-fluid ">
						
						<div class="span12" id="exp-container" style="text-align:center">
							<h4>Fan Experience</h4>
							<div class="progress">
								<div class="bar" style="width: <?= $this->fan_exp_percentage?>%;"></div>
								
							</div>
							
								<h5><?=$this->fan_exp?>/<?=$this->fan_level_exp?></h5>
								<?=$this->fan_exp_required?> Until Next Level
							
						</div>
					</div>
				</div>
				<div class="post-container noline">
					<ul class="stats">
					<li >
						<div class="stats-block"><img src="/img/coins.png" /><h3><?= $this->fan->fan_currency?></h3>	<br/>
						Points</div>
					</li>
					<li >
						<div class="stats-block"><img src="/img/post.png" /><h3><?=$this->stat_post?></h3>	<br/>
						Posts</div>
					</li>
					<li >
						<div class="stats-block"><img src="/img/thumbsup.png" /><h3><?=$this->stat_like?></h3><br/>
						Likes</div>
					</li>
					<li >
						<div class="stats-block"><img src="/img/comment.png" /><h3><?=$this->stat_comment?></h3><br/>
						Comments</div>
					</li>
					<li >
						<div class="stats-block"><img src="/img/rthumbsup.png" /><h3><?=$this->stat_get_like?></h3><br/>
						Recieved Likes</div>
					</li>
					<li style="border:0px">
						<div class="stats-block"><img src="/img/rcomment.png" /><h3><?=$this->stat_get_comment?></h3><br/>
						Recieved Comments </div> 
					</li>
					</ul>
				</div>	
		
			
				
				
			
			
			</div>
		</div>
		<div id ="upcoming-badges-container">
			
			<div class="row box">
				<div class="title nopic">
		
					<div class="title-header nopic">
						Upcoming Badges
					</div>
					<!--  <div class="tip">
						<a rel="tooltip" data-original-title='These are your upcoming badges'>
							?
						</a>
					</div>-->
				</div>
				<div class="post-container noline">
					<div class="row-fluid post">
						<?php foreach ($this->badges as $b){?>
							<div class="span2 upcoming-badges">
								<div class="progress">
									<div class="bar" style="width: <?= $b['percentage']?>%;"></div>
									<a data-original-title="<?= $b['name']. '<br/>'.$b['description'].'<br/>'.$b['percentage'].'% Completed'?>" 
									rel="tooltip" data-placement="top-left" style="float:left; position:relative;top:-50px;" >
										
										<img src="<?= $b['picture']?>" style="opacity:<?= $b['percentage']/100?>"/>
									</a>
								</div>
							</div>
						<?php }?>
					</div>
				</div>
			</div>
		</div>
		<div class="row-fluid" id="follow-list-container">		
			<div class="row box">
				<div class="span6" >	
				
				
					<div class="title nopic">
						<div class="title-header nopic">
							 <div class="follow-title"><a onclick="getFollowersList('<?=$this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name?>', '<?=$this->facebook_user->facebook_user_id?>', 0)"><img src="/img/eye_arrow.png" /><span class="h3"><?= $this->follower['0']['Follower']?></span><br/>
							Followers</a></div>
						</div>
					</div>
					<div id="followerslist"></div>
					
				</div>
					
						
						
				<div class="span6" >
			
			
					<div class="title nopic">
						<div class="title-header nopic">
							 <div class="follow-title"><a onclick="getFollowingList('<?=$this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name?>', '<?=$this->facebook_user->facebook_user_id?>', 0)"><img src="/img/eye_arrow2.png" /><span class="h3"><?= $this->following['0']['Following']?></span><br/>
						Following</a></div>
						</div>
					</div>
					<div id="followinglist"></div>
				
				</div>				
			</div>
		</div>	
		
	</div>
	</div>
	<div class="span4">
	
		<div id = "recent-activities-container">
		
			<div class="row box">
				<div class="title nopic">
					<div class="title-header nopic">
						Recent Activities
					</div>
					<!--  <div class="tip">
						<a rel="tooltip" data-original-title='This is your list of recent actitivies, remember that it may not be accurate as it does require time for it to sync up with Facebook'>?</a>
					</div>-->
				</div>
				<div class="scrollbox">
					<ul id="recent_activities"></ul>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$('#recent_activities').enscroll({
		showOnHover: true,
		clickTrackToScroll: false,
		verticalTrackClass: 'track3',
		verticalHandleClass: 'handle3'
	});
</script>
