	
				
					
						<div class="row">
							<div class="span12">
								<div class="title">
									<div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture"></a> </div>

									<div class="title-header"> <h3><?echo $this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name ?>'s News Feed</h3> </div>

								</div>
							</div>
						</div>
					
						<div class="row" >
						<div class="span8">
									<div class="subtitle">
										<div class="title-header"> <h3>Fancrank Feed</h3>
										 <span>[<a href="#" onclick="getFancrankfeed('all')">All</a> | <a href="#" onclick="getFancrankfeed('admin')">Admin</a> | <a href="#" onclick="getFancrankfeed('user')">User</a> ]</span></div>
									</div>
									
									<form action="#" class="submit_box">
													<textarea id="post_box" onkeyup="resizeCommentBox(this)"></textarea>
													<input type=button class="btn-submit" value="Submit" id="post_button" onclick="post('<?= $this->fanpage_id?>', '<?= $this->fanpage_name?>' )">
									</form>
									
									<ul class="post-list" id ="fancrankfeed">
										
									</ul>
							</div>
							<div class="span4">
									<div class="subtitle">
										<div class="title-header-dark"> <h3> Top Posts</h3> </div>
									</div>
									
										<ul class="bubble" id="toppost">
											
											
										</ul>
									
							</div>
							
						</div>
				
    			
    				

    
    	
     
        


<!--


<hr />


<p>top talkers</p>

<pre>
<?= print_r($this->top_talkers) ?>
</pre>

<p>top clickers</p>

<pre>
<?= print_r($this->top_clickers) ?>
</pre>

<p>top fans</p>

<pre>
<?= print_r($this->top_fans) ?>
</pre>

<p>most popular</p>

<pre>
<?= print_r($this->most_popular) ?>
</pre>

-->

