<div class="row">
	<div class="span7">
		<div class="title">
			
			<div class="title-header nopic">
				Latest Post From
				<?= $this->fanpage_name?>

			</div>
			<div class="tip">
				<a rel="tooltip"
					data-original-title="This is <?=$this->fanpage_name?>'s latest post!">?</a>
			</div>
		</div>
		
		<div class="row box">
			<ul id="latestpost">
				<?php $count = 0?>

				<?php if(empty($this->latest)){?>

				<li class="post-container">
					<div class="user"></div>

					<div class="post">
						<div class="message">Feed Empty/Feed not Available</div>
					</div>

				</li>
				<?}else{?>



				<?php  $post = $this->latest[0];?>


				<li class="post-container">


					<div class="user">
						<div class="user-badge">
							<a rel="tooltip-follow" data-original-title="You can't Follow an Admin" data-placement="top">
								<span class="badge badge-Fanpage">Admin</span>
							</a>
						</div>

						<div class="photo"><a> <img class="face" width="30" height="30"
								src="https://graph.facebook.com/<?= $post->from->id ?>/picture"
								onerror="ImgError(this);"></a> </div> 
								
						<div class="name"><a><?=  $post->from->name?></a> 
						</div>
					</div>




					<div class="post">



					<?php if(isset($post->message)){ ?>
							<div class="message">
							<?php 
							$reg_ex = "/\n/";
							$message = $this->escape($post->message);
							if(preg_match_all($reg_ex, $message, $url)) {
								$message= preg_replace($reg_ex, "<br/>", $message);
							} 
							
							$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
						
							$m = preg_match_all($reg_exUrl, $message, $match); 
							
							if ($m) { 
							    $links=$match[0]; 
							    for ($j=0;$j<$m;$j++) { 
							        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="new">'.$links[$j].'</a>',$message); 
							    } 
							} 
							
							echo trim($message); 
								//echo preg_replace($reg_exUrl, "<a href=".$url[0][0]." target=_new>".$url[0][0]."</a> ", $m);
							
							?><br/>
							</div>
					<?}	?>


						<div class="graphical">
							<?php if (($post->type == 'photo') || ($post->type =='video')) {?>
							<a target="new" href="<?echo $this->escape($post->link)?> "> <img
								src='<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> ' />
							</a>

							<?}elseif ($post->type == 'link') {?>
								<div class="link">
									<?php if (isset($post->picture)){?>
										<div class="link-left">
										
											<a target="new" href="<?echo $this->escape($post->link)?> "> 
												<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
											</a>
										
										</div>
									<?php }?>
									<div class="link-right">
										<a target="new" class="link-title" href="<?echo $this->escape($post->link)?>">
											<?= (isset($post->name)?$this->escape($post->name): $this->escape($post->link))?>
										</a>
										<?php if(isset($post->caption)){?>
											<br/>
											<a target="new" class="link-caption" href="<?echo $this->escape($post->link)?> ">
												<?php echo $this->escape($post->caption);?>:  
											</a>
										<?php }?>	
									
										<?php if (isset($post->description)){?>
												<?=$this->escape($post->description)?> 
											
										<?php }?>
											
										
									</div>
								</div>
							<?}?>
						</div>

					</div>

					<div class="social">
						<a class="like_control_<?= $post->id?>"  data-placement="top" rel="tooltip" 
							
						<?php if ($this->latestlike == 0) {?>
						   data-original-title="Click to like this" onclick="like('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>' )">Like
						<?}else{?>
						   data-original-title="You like this" onclick="unlike('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>')">Unlike
						<?php }?></a>

						&middot; <a
							onclick=" comment_feed2('<?= $post->id ?>','<?= $post->type?>', 10,<?php 
			 		if(isset($post->comments->count)){
						echo $post->comments->count; 
			 		} else {echo '0';} ?> , true )"
							class="commenthidern_<?= $post->id ?>">Comment </a> 
							&middot;
							<a rel="tooltip" data-placement="right" class="time" data-original-title="" data-unix-time="<?= strtotime($post->created_time)?>"> </a> <br />
					</div>

					<div class="social like <?=$post->id?>"
					<?php if(!isset($post->likes->count) || ($post->likes->count == 0)){?>
						style="display: none" <?php }?>>

						<a rel="tooltip" data-placement="top" onclick="getLikesList('<?=$post->id?>', true)" data-original-title=" 
						<?php 	$likeslist = $post->likes->data;
								$countlikes = count($likeslist);
								for($i = 0; $i < $countlikes - 1; $i++){
									echo $likeslist[$i]->name.', ';
								}

								echo $likeslist[$i]->name;
								if ($countlikes < $post->likes->count){
									echo " and ".($post->likes->count - $countlikes)." others";
								}
						?> likes this.
						"> <img src = "/img/thumbsup.png" /> <span class="like_<?= $post->id?>" data-like-count = <? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>><? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>

								<?php if($post->likes->count == 1){?>person<?php }else{?>people<?php }?>

						</span> likes this.
						</a>
					</div> 
					<div class="social commentn <?=$post->id?>" <?php if(!isset($post->comments->count) || ($post->comments->count == 0)){?>style="display:none"<? }?> >

						<a
							onclick=" comment_feed2('<?= $post->id ?>','<?= $post->type?>', 10,<?php 
			 		if(isset($post->comments->count)){
						echo $post->comments->count; //echo  $post->comments->count;
			 	} else {echo '0';} ?> , true )"> <img src="/img/comment.png" /><?php if($post->comments->count != 1){?>
							View all <span class="comment_<?= $post->id?>" data-comment-count = <?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>><?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>
						</span> comments <?php }else { ?> View all<span
							class="comment_<?= $post->id?> "data-comment-count = <?php if(isset($post->comments->count)){
						echo $post->comments->count; 
					 	} else {
							echo '0'; 
						}?>> </span> comments <?php }?>
						</a>



					</div> 
					<ul class="comments" id="postn_<?=$post->id?>"></ul>
				</li>



			


				<?php }?>


			</ul>

		</div>

		<div class="title">
			<div class="title-icon">
				<img src="/img/news-feed/top-fan-icon.jpg" />
			</div>

			<div class="title-header">FanCrank Feed</div>
			<div class="tip">
				<a rel="tooltip"
					data-original-title='The FanCrank Feed is a customized news feed of all the activity on the page.  Choose "All" to see all posts on the page.  Choose "My Feed" to only show posts by the page owner and the people you follow.  choose "Page Posts" to see posts from the page owner.'>?</a>
			</div>
		</div>

		<!-- 
												<ul class="nav nav-tabs" id="postingTab">
												  <li class="active"><a href="#post_post" data-toggle="tab" id="post_post_tab">Posts</a></li>
												  <li><a href="#post_photo" data-toggle="tab" id="post_photo_tab">Photo/Video</a></li>
												</ul>
												 -->
		<!--  <div class="tab-content" id="postingContent">
													<div class="tab-pane active" id="post_post">-->


		<div class="row box">




			<ul id="submitfeed">
				<li class="post-container">
					<div class="post">
						<span>[ <a rel="tooltip"
								data-original-title='See all posts on the page.' data-placement='top'
									onclick="getFancrankfeed('all')">All</a> | 
								<a rel="tooltip" data-placement='top'
								data-original-title='Only show posts by the page owner and the people you follow.'
							 onclick="getFancrankfeed('myfeed')">My Feed</a> | 
							 	<a  rel="tooltip" data-placement='top'
								data-original-title='Only show posts from the page owner'
							 onclick="getFancrankfeed('admin')">Page Posts</a> ]
						</span>
					</div>
				</li>

				<li class="post-container">

					<div class="post">

						<form action="#" class="submit-form">
							<textarea id="post_box" class="post-box" onkeyup="resizeCommentBox(this)" onclick="PostBox()"></textarea>
							
							<div class="post-button-container">
								<input type=button class="btn-submit" value="Share"
									id="post_button"
									onclick="post('<?= $this->fanpage_name?>' )">
							</div>
						</form>
					</div>
				</li>

			</ul>


	<!-- </div>
												 
 <div class="tab-pane" id="post_photo">
<form action="#" class="submit_box">
<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
<span class="control-label">Select an image</span>
<input type="file" name="datafile" />
<input type="button" value="Upload"
onClick="upload(this.form,'/app/user/<?=$this->fanpage_id?>/upload?fanpage_id=<?= $this->fanpage_id?>','upload','<?= $this->fanpage_id?>', '<?= $this->fanpage_name?>'); return false;" >
<div id="upload"></div>
														
<textarea id="post_box" onkeyup="resizeCommentBox(this)"></textarea>
<input type=button class="btn-submit" value=" Post "  id="post_button" onclick="post('<?= $this->fanpage_id?>', '<?= $this->fanpage_name?>' )">
</form>
												 
</div>
												  
												  
</div>-->

<ul id="fancrankfeed">

			
<?php $count = 0?>

<?php if(empty($this->post)){?>
	
	<li class="post-container">
	<div class="user">
	
	</div>
	<div class="post_container">
		<div class="post">
			<div class="message">
			Feed Empty/Feed not Available
			</div>
		</div>
		</div>
	</li>
<?}else{?>



<?php foreach ($this->post as $post):?>		

		
	<li class="post-container <?=$post->id?>" >
	
	<div class="user" >		
	
	<div class="user-badge">
	<a  <? if (($this->relation[$count] != 'Fanpage')){?>
					<? if ($this->relation[$count] != 'You') { ?>
						<? if (($this->relation[$count] != 'Following') /*&& ($this->relation[$count] != 'Friends')*/){?>
								 onclick="follow(<?=$post->from->id?> , '<?=$post->from->name?>', 'follow_<?=$post->from->id?>')" class ="follow_<?=$post->from->id?>" 
						<?}else{?>
								onclick="unfollow(<?=$post->from->id?> , '<?=$post->from->name?>', 'follow_<?=$post->from->id?>')" class ="follow_<?=$post->from->id?>"
						<?}?>
						>
							
						<span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
					<?php }else{?>
						><span class="badge badge-You">You</span>
					<?php }?>
					
				<?}else{?>
					rel="tooltip-follow" data-original-title="You can't Follow an Admin" data-placement="top"><span class="badge badge-Fanpage">Admin</span>
				<?php }?> </a></div>
	
	<div class="photo"><a data-toggle="modal"
		<? if (!($this->relation[$count] == 'Fanpage')){?> 
			onclick="userProfile('<?=$post->from->id?>')"
			rel="popover" 
			data-content="" 
			data-original-title="" 
			data-placement="right" 
			data-userid="<?=$post->from->id?>"
		<?php }?>
	><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post->from->id ?>/picture" onerror="ImgError(this);">
	</a></div>
	
	<div class="name"><a data-toggle="modal"
		<? if (!($this->relation[$count] == 'Fanpage')){?> 
			onclick="userProfile('<?=$post->from->id?>')"
			rel="popover" 
			data-content="" 
			data-original-title="" 
			data-placement="right" 
			data-userid="<?=$post->from->id?>"
		<?php }?>
	><?=  $post->from->name?>
	</a></div>
	
	</div>

	<div class="post">
		<?php if(isset($post->message)){ ?>
			<div class="message">
							<?php 
							$reg_ex = "/\n/";
							$message = $this->escape($post->message);
							if(preg_match_all($reg_ex, $message, $url)) {
								$message= preg_replace($reg_ex, "<br/>", $message);
							} 
							
							$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
						
							$m = preg_match_all($reg_exUrl, $message, $match); 
							
							if ($m) { 
							    $links=$match[0]; 
							    for ($j=0;$j<$m;$j++) { 
							        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="new">'.$links[$j].'</a>',$message); 
							    } 
							} 
							
							echo trim($message); 
								//echo preg_replace($reg_exUrl, "<a href=".$url[0][0]." target=_new>".$url[0][0]."</a> ", $m);
							
							?><br/>
			</div>
		<?}	?>
		<div class="graphical">	
		<?php if (($post->type == 'photo') || ($post->type =='video')) {?>	
			<a target="new" href="<?echo $this->escape($post->link)?> "> 
						<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
					</a>
			
		<?}elseif ($post->type == 'link') {?>
			<div class="link">
				<?php if (isset($post->picture)){?>
					<div class="link-left">
					
						<a target="new" href="<?echo $this->escape($post->link)?> "> 
							<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $post->picture))?> '/>
						</a>
					
					</div>
				<?php }?>
				<div class="link-right">
					<a target="new" class="link-title" href="<?echo $this->escape($post->link)?>">
						<?= (isset($post->name)?$this->escape($post->name): $this->escape($post->link))?>
					</a>
					<?php if(isset($post->caption)){?>
						<br/>
						<a target="new" class="link-caption" href="<?echo $this->escape($post->link)?> ">
							<?php echo $this->escape($post->caption);?>:  
						</a>
					<?php }?>	
				
					<?php if (isset($post->description)){?>
							<?=$this->escape($post->description)?> 
						
					<?php }?>
						
					
				</div>
			</div>
		<?}?>
		</div>
</div>
	
	<div class="social"> 
			
			
		<a class="like_control_<?= $post->id?>"  rel="tooltip" data-placement="top"
							
						<?php if ($this->likes[$count] == 0) {?>
						  data-original-title="Click to like this"  onclick="like('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>' )">Like
						<?}else{?>
						  data-original-title="You like this"  onclick="unlike('<?= $post->id?>', '<?= $post->type?>', '<?=$post->from->id?>','<?=$post->from->name?>')">Unlike
						<?php }?></a>
		
		 &middot;
		
		<a  onclick=" comment_feed('<?= $post->id ?>',
			 						'<?= $post->type?>', 
			 						10,
			 						<?= (isset($post->comments->count)? $post->comments->count : '0')?> , 
								 	true )"
			class="commenthider_<?= $post->id ?>">Comment</a>
				
		&middot;

		<a rel="tooltip" data-placement="right" class="time" data-original-title="" data-unix-time="<?=  strtotime($post->created_time)?>"></a>
			
		<br/>
	</div>
	<div class="social like <?=$post->id?>"  <?php if(!isset($post->likes->count) || ($post->likes->count == 0)){?>style="display:none"<?php }?>>
		
			<a rel="tooltip" data-placement="top" onclick="getLikesList('<?=$post->id?>', true)" data-original-title="
						<?php 	$likeslist = $post->likes->data;
								$countlikes = count($likeslist);
								for($i = 0; $i < $countlikes - 1; $i++){
									echo $likeslist[$i]->name.', ';
								}

								echo $likeslist[$i]->name;
								if ($countlikes < $post->likes->count){
									echo " and ".($post->likes->count - $countlikes)." others";
								}
						?> likes this.
						">
				<img src = "/img/thumbsup.png" />
				<span class="like_<?= $post->id?>" data-like-count= <? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>><? if(isset($post->likes->count)){echo $post->likes->count;}else{echo '0';} ?>
					
					<?php if(isset($post->likes->count) && $post->likes->count == 1){?>person<?php }else{?>people<?php }?> 
				
				</span>
				likes this.
			</a>		
		
	
	</div>
 
	
	<div class="social comment <?=$post->id?>" <?php if(!isset($post->comments->count) || ($post->comments->count == 0)){?>style="display:none"<? }?>>
	
			 <a  onclick=" comment_feed('<?= $post->id ?>',
			 							'<?= $post->type?>', 
			 							10,
			 							<?= (isset($post->comments->count)? $post->comments->count : '0')?> , 
								 		true )"> 
					<img src="/img/comment.png" />
			 		<?php if($post->comments->count != 1){?> 
			 		View all <span class="comment_<?= $post->id?>" data-comment-count=<?php if(isset($post->comments->count)){
						echo $post->comments->count; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>>
			 		<?php if(isset($post->comments->count)){
						echo $post->comments->count; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>
					</span> 
					comments 
				<?php }else { ?>
					View all<span class="comment_<?= $post->id?>" data-comment-count=<?php if(isset($post->comments->count)){
						echo $post->comments->count; //echo  $post->comments->count;
					 	} else {
							echo '0'; 
						}?>>
			 		
					 
					
					</span>
					comments 
				<?php }?>
				</a>
			
	
	
	</div>
	
	
	
	
	<ul class="comments" id="post_<?=$post->id?>" ></ul>
	</li>	
			
			<?php $count ++;?>
			 
			
			
			<?php endforeach; ?>
							
			<?php }?>					
			<?php $last_object = $this->post[count($this->post) - 1] ?>
			<li id="last_post_time" data-time="
			<?=  strtotime($last_object->created_time)?>"></li>
			
			
			<li><button id ="more_post" class="btn-more" onclick="getFancrankfeed(setFeed)">MORE POSTS +</button></li>
			</ul>


			

		</div>
	</div>


	<div class="span5">
		<div class="row">
			<div class="span5">
				<div class="title">
					<div class="title-icon">
						<img src="/img/news-feed/top-fan-icon.jpg" />
					</div>
					<div class="title-header"><span id="topfan-tour">Top Fans This Week</span></div>
					<div class="tip">
						<a rel="tooltip"
							data-original-title="These 5 fans have liked, commented, and interacted the most on the page.  This ranking changes every week.  Prizes are awarded to the top fan every week!">?</a>
					</div>
				</div>
				<div class="row box" id="topfan"></div>
			</div>

		</div>

		<div class="row">
			<div class="span5">

				<div class="title nopic">


					<div class="title-header nopic"><span id="toppost-tour">Top Posts This Week</span></div>
					<div class="tip">
						<a rel="tooltip"
							data-original-title="The posts listed below are the posts that have gotten the most likes and comments!  This list is updated regularly.">?</a>
					</div>
				</div>

				<div class="row box">

					<ul id="toppost">


					</ul>
				</div>
			</div>
		</div>
	</div>

</div>	