<div class="row">
<div class="span8">
<div class="row box notitle">

<?php 
$currentdate = null;
$currentpost = null;
$total=0;
$totalAll = 0;
if ($this->point_log == 'x'){?>
	<div class="post-container noline">
		<div class="user">
			<div class="user-badge">

				<a class="noclick" rel="tooltip-follow" data-original-title="You can't Follow an Admin" >

					<span class="badge badge-Fanpage">Admin</span>
				</a>
			</div>

			<div class="photo"><a class="noclick" > <img class="face" width="30" height="30"
					src="https://graph.facebook.com/<?= $this->fanpage_id?>/picture"
					onerror="ImgError(this);"></a> </div> 
					
			<div class="name"><a class="noclick"><?=   $this->fanpage_name?></a> 
			</div>
		
		</div>
		<div class="post">
			
			<div class="message">
				Points are not available for this fanpage
			</div>
		</div>
	</div>
<?php 	
}else{?>
<div class="post-container noline">
		<div class="user">
			<div class="user-badge">

				<a class="noclick" rel="tooltip-follow" data-original-title="You can't Follow an Admin" >

					<span class="badge badge-Fanpage">Admin</span>
				</a>
			</div>

			<div class="photo"><a class="noclick" > <img class="face" width="30" height="30"
					src="https://graph.facebook.com/<?= $this->fanpage_id?>/picture"
					onerror="ImgError(this);"></a> </div> 
					
			<div class="name"><a class="noclick"><?=   $this->fanpage_name?></a> 
			</div>
		
		</div>
		<div class="post">
			
			<div class="message">
				Here's your points break down for the previous 3 days.
				<br/><br/>
			
				<table class="pointlog">
				<?php 
				foreach ($this->point_log as $points){
					
					if ($currentdate != $points['created_time']){
						echo '<tr><td class="no-border" colspan="3">&nbsp;</td></tr>';
						$currentdate = $points['created_time'];
						$date = new Zend_Date($currentdate);
						
						echo '<tr><th colspan="3">';
						echo $date->toString(Zend_Date::WEEKDAY).', '.$date->toString(Zend_Date::MONTH_NAME).' '.$date->toString('dd, yyyy');
						echo '</th></tr>';
						$currentpost = null;
					}
					echo '<tr>';
					
						echo '<td >'.$points['object_id'] . '</td>';
					
					
					echo '<td>'.$points['note'] . '</td><td class="points">' . $points['sum'] . '</td>';
				
					$totalAll +=$points['giving_points'];
					echo '</tr>';
				}
				echo '<tr><td class="no-border" colspan="3">&nbsp;</td></tr>';
				echo '<tr><th>Total for the Past 3 Days</th><td></td><td class="points"> '.$totalAll . '</td></tr>';
				?>
				</table>
			</div>
		</div>
	</div>
<?}?>

</div></div></div>