<?php if(count($this->activities)==0){?>
	<li class="post-container" >
	<div class="post">
		<div class="message">
	No Recent Activities for this Fanpage.
	</div>
	</div>
	</li>
<?php }?>

	<?php
	$count = 0;
	foreach ($this->activities as $act):	
	?>
		<li class="post-container" >
	
		<div class="post">
		<div class="message">

		
		<?switch($act['activity_type']){ 
		
			case 'follow': ?>
				You followed <a href="#" onclick="userProfile('<?=$act['event_object']?>')"><?=$act['target_user_name']?></a> 
				<?break;
			case 'unfollow' :?>
				You unfollowed <a href="#" onclick="userProfile('<?=$act['event_object']?>')"><?=$act['target_user_name']?></a> 
				<?break;	
			case 'like-status':?>
				You liked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">status post </a> 
				<?break;
			case 'unlike-status':?>
				You unliked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>' , 10, true)">status post</a> 
				<?break;
			case 'like-photo':?>
				You liked <?=$act['target_user_name']?>'s <a onclick="popup_post('<?=$act['event_object']?>', 10, true)">photo post </a> 
				<?break;
			case 'unlike-photo':?>
				You unliked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>' , 10, true)">photo post</a> 
				<?break;	
			case 'like-video':?>
				You liked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">video post </a> 
				<?break;
			case 'unlike-video':?>
				You unliked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>' , 10, true)">video post</a> 
				<?break;
			case 'like-link':?>
				You liked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">link post </a> 
				<?break;
			case 'unlike-link':?>
				You unliked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>' , 10, true)">link post</a> 
				<?break;
			case 'like-comment':?>
				You liked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?$temp = explode("_", $act['event_object']); echo $temp[0].'_'.$temp[1];?>' , 10, true)">comment</a> 
				<?break;
			case 'unlike-comment':?>
				You unliked <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?$temp = explode("_", $act['event_object']); echo $temp[0].'_'.$temp[1];?>' , 10, true)">comment</a> 
				<?break;
			case 'comment-status':?>
				You posted a comment on <?=$act['target_user_name']?>'s <a onclick="popup_post('<?=$act['event_object']?>', 10, true)">status post</a> 
				<?break;
			case 'comment-photo':?>
				You posted a comment on <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">photo post</a> 
				<?break;
			case 'comment-video':?>
				You posted a comment on <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">video post</a> 
				<?break;
			case 'comment-link':?>
				You posted a comment on <?=$act['target_user_name']?>'s <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">link post</a> 
				<?break;
			case 'post-status':?>
				You made a <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">status post</a> on <?=$act['target_user_name']?>'s Fanpage 
				<?break;
			case 'post-photo':?>
				You made a <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">photo post</a> on <?=$act['target_user_name']?>'s Fanpage 
				<?break;
			case 'post-link':?>
				You made a <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">link post</a> on <?=$act['target_user_name']?>'s Fanpage 
				<?break;
			case 'post-video':?>
				You made a <a  onclick="popup_post('<?=$act['event_object']?>', 10, true)">video post</a> on <?=$act['target_user_name']?>'s Fanpage 
				<?break;
			default:
		}?><a rel="tooltip" data-placement="top" class="time" data-original-title="" data-unix-time="<?=strtotime($act['created_time'])?>"></a>.
		</div>
		</div>
	</li>

		<?endforeach; ?>

