
<div class="row">
	<div class="span12">
		<div class="title">
			<div class="title-icon">
				<a href=""><img class="face" width="50" height="50"
					src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture"
					onerror="ImgError(this);"> </a>
			</div>
			<div class="title-header">
		
				Redemption
				
			</div>
		</div>
		<div class="row box">
			<div class="post-container">
				<span>Badge List:</span>
				<div class="item-section"></div>
				<ul>
					<?php foreach ($this->itemList as $item) {?>
						<li class="item_<?=$item['id']?>"><span><?=$item['name']?></span><img class="item" width="50" height="50" src="<?=$item['picture']?>"/>
						<a href="#" onclick="redeem(<?=$item['id']?>); return false;">Redeem</a></li>
					<? }?>
				</ul>
			</div>
		</div>
	</div>
</div>

<script>
function redeem(itemId) {

	$.ajax({
		type : "GET",
		url : serverUrl + '/app/redeem/confirm?itemId='+itemId,
		cache : false,
		async : true,
		success : function(data) {
			if($.trim(data) == 'ok') {
				alert('you redeem an item');
				$(".item_"+itemId).remove();
			}
			//getLatestPost();
		},
		error : function(xhr, errorMessage, thrownErro) {
			console.log(xhr.statusText, errorMessage);
		}
	});
}
</script>
