
<div class="row">
	<div class="span12">
		<div class="title">
			<div class="title-icon">
				<a href=""><img class="face" width="50" height="50"
					src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture"
					onerror="ImgError(this);"> </a>
			</div>
			<div class="title-header">
		
					Redemption
				
			</div>
		</div>
		<div class="row box">
			<div class="post-container">
				Want to use your points to get cool stuff related to this Fanpage?
				<br/>
				<br/>
				Our minions are working non-stop so you can redeem stuff as fast as possible, so go and collect more points!
				
			</div>
		</div>
	</div>
</div>

