<div class="row">
							<div class="span8">
								<div class="top-fan">
									<div class="title">
										<div class="photo"> <img src="/img/news-feed/top-fan-icon.jpg" /> </div>
										<div class="title-header"> <h2><i class="icon-star icon-white"></i> Top Fans <i class="icon-star icon-white"></i></h2>
											<div class="tip"><a title="You are awesome and nobody can touch you!<br /><br />But <i>seriously</i>, your ranking is determined by the amount of posts, comments and likes you make to the page.<br /><br />If you're top 5 that means you interact with our brand the most!">?</a></div>
										 </div>
									</div>
									<?php $count = 0; ?> 
									<?php foreach($this->top_fans as $top_fan): ?>
									
									<?php if ($count == 0){?>
								
										<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a   target="_blank" href="https://facebook.com/<?= $top_fan['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" target="_blank" href="https://facebook.com/<?= $top_fan['facebook_user_id'] ?>"><?= $top_fan['fan_first_name'] ?></a>
															<br/>
															<span class="badge badge-follow">Follow</span>
														</div>
														<div class="points">
															<h2><?= $top_fan['number_of_posts'] ?></h2> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="top-fans-collapse" class="top-list in">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a   target="_blank" href="https://facebook.com/<?= $top_fan['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first')<?php }?> target="_blank" href="https://facebook.com/<?= $top_fan['facebook_user_id'] ?>"><?= $top_fan['fan_first_name'] ?></a>
														<br/>
														<span class="badge badge-follow">Follow</span>
													</div>
													<div class="points">
														<h2><?= $top_fan['number_of_posts'] ?> </h2> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									</ul>
									
									<div class="shadow">
										<button class="btn" id="top-fans-btn" data-toggle="collapse" data-target="#top-fans-collapse">
												- Close
										</button>
									</div>
								</div>
								
								<div class="fan-favorite">
									<div class="title">
										<div class="photo"> <img src="/img/news-feed/fan-fav-icon.jpg" /> </div>
										<div class="title-header"> <h2><i class="icon-star icon-white"></i> Fan Favorite <i class="icon-star icon-white"></i></h2>
											<div class="tip"><a title="People like you. Your mom was right!<br /><br />But <i>seriously</i>, your contribution is well regarded within the community. People like your posts and interact with you a lot.<br /><br />Keep up the good work!">?</a></div>
										</div>
									</div>
									<?php $count = 0; ?> 
									<?php foreach($this->most_popular as $popular): ?>
									<?php if ($count == 0){?>
									<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a   target="_blank" href="https://facebook.com/<?= $popular['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" target="_blank" href="https://facebook.com/<?= $popular['facebook_user_id'] ?>"><?= $popular['fan_first_name'] ?></a>
															<br/>
															<span class="badge badge-follow">Follow</span>
														</div>
														<div class="points">
															<h2><?= $popular['count'] ?> </h2> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
									</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="fan-favorite-collapse" class="top-list in">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a   target="_blank" href="https://facebook.com/<?= $popular['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first')<?php }?> target="_blank" href="https://facebook.com/<?= $popular['facebook_user_id'] ?>"><?= $popular['fan_first_name'] ?></a>
														<br/>
														<span class="badge badge-follow">Follow</span>
													</div>
													<div class="points">
														<h2><?= $popular['count'] ?> </h2> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									</ul>
																
								
									<div class="shadow">
										<button class="btn" id="fan-favorite-btn" data-toggle="collapse" data-target="#fan-favorite-collapse">
												- Close
										</button>
									</div>
								</div>
							
								<div class="top-talker">
									<div class="title">
										<div class="photo"> <img src="/img/news-feed/top-talker-icon.jpg" /> </div>
										<div class="title-header"> <h2><i class="icon-star icon-white"></i> Top Talker <i class="icon-star icon-white"></i></h2> 
											<div class="tip"><a title="Loud and proud! You don't care what time of the night it is, you keep barking!<br /><br />But <i>seriously</i>, your posts and comments help shape the conversations.<br /><br />Keep it loud. Keep it proud.">?</a></div>
										</div>
									</div>
									<?php $count = 0; ?> 
									<?php foreach($this->top_talker as $talker): ?>
									<?php if ($count == 0){?>
									<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a   target="_blank" href="https://facebook.com/<?= $talker['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" target="_blank" href="https://facebook.com/<?= $talker['facebook_user_id'] ?>"><?= $talker['fan_first_name'] ?></a>
															<br/>
															<span class="badge badge-following">Following</span>
														</div>
														<div class="points">
															<h2><?= $talker['number_of_posts'] ?> </h2> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="top-talker-collapse" class="top-list in">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a   target="_blank" href="https://facebook.com/<?= $talker['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first')<?php }?> target="_blank" href="https://facebook.com/<?= $talker['facebook_user_id'] ?>"><?= $talker['fan_first_name'] ?></a>
														<br/>
														<span class="badge badge-friends">Friends</span>
													</div>
													<div class="points">
														<h2><?= $talker['number_of_posts'] ?> </h2> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									</ul>
									<div class="shadow">
										<button class="btn" id="top-talker-btn" data-toggle="collapse" data-target="#top-talker-collapse">
												 - Close
										</button>
									</div>
								</div>
							
								<div class="top clicker">
										<div class="title">
											<div class="photo"> <img src="/img/news-feed/top-clicker-icon.jpg" /> </div>
											<div class="title-header"> <h2><i class="icon-star icon-white"></i> Top Clicker <i class="icon-star icon-white"></i></h2> 
												<div class="tip"><a title="Is there anything you don't like? Even Lindsey Lohan has standards --insert chuckle--.<br /><br />But <i>seriously</i>, we're glad you take interest in your peers.<br /><br />Happy clicking!.">?</a></div>
											</div>
										</div>
										
										<?php $count = 0; ?> 
									<?php foreach($this->top_clicker as $clicker): ?>
									<?php if ($count == 0){?>
									<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a   target="_blank" href="https://facebook.com/<?= $clicker['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" target="_blank" href="https://facebook.com/<?= $clicker['facebook_user_id'] ?>"><?= $clicker['fan_first_name'] ?></a>
															<br/>
															<span class="badge badge-follow">Follow</span>
														</div>
														<div class="points">
															<h2><?= $clicker['number_of_likes'] ?></h2> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="top-clicker-collapse" class="top-list in">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a   target="_blank" href="https://facebook.com/<?= $clicker['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first')<?php }?> target="_blank" href="https://facebook.com/<?= $clicker['facebook_user_id'] ?>"><?= $clicker['fan_first_name'] ?></a>
														<br/>
														<span class="badge badge-follower">Follower</span>
													</div>
													<div class="points">
														<h2><?= $clicker['number_of_likes'] ?> </h2> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									</ul>
										
									 
										<div class="shadow">
											<button class="btn" id="top-clicker-btn" data-toggle="collapse" data-target="#top-clicker-collapse">
													- Close
											</button>
										</div>
									</div>
								
							</div>
						
							<div class="span4">
									<div class="subtitle">
											<div class="title-header-dark"> <h2><i class="icon-star icon-white"></i> Last Top Box <i class="icon-star icon-white"></i></h2> </div>
									</div>
									<ul class="bubble">
											<?php $count = 0?>
											<?php foreach($this->latest_post as $latestPost): ?>
											
											<?php if ($count % 2 == 0){?>
											<li class="chat-right">
											<?php }else{?>
											<li class="chat-left">
											<?php }?>
												
												<div class="post">
													<a href=""><?= $latestPost['post_message'] ?><br /><span class="date"><?=date("F d Y", strtotime( $latestPost['updated_time']))?></span></a>
           
												</div>
													
													<div class="info">
														<div class="name"><a href=""><?= $latestPost['fan_first_name'] ?> <?= $latestPost['fan_last_name'] ?></a><br /><img src="/img/news-feed/icon-likes.png" /> <?= $latestPost['post_likes_count']?> <a href="" class="likes"> Like</a></div>
														<div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $latestPost['facebook_user_id'] ?>/picture"></a></div>
														
													</div>
												
											</li>

											<?php $count ++;?>
											<?php endforeach; ?>
											
										</ul>
							</div>

<!--


<hr />


<p>top talkers</p>

<pre>
<?= print_r($this->top_talkers) ?>
</pre>

<p>top clickers</p>

<pre>
<?= print_r($this->top_clickers) ?>
</pre>

<p>top fans</p>

<pre>
<?= print_r($this->top_fans) ?>
</pre>

<p>most popular</p>

<pre>
<?= print_r($this->most_popular) ?>
</pre>

-->

<script src="text/javascript">
window.onload = function() {
	  FB.Canvas.setAutoGrow(91);
	  setTimeout('autoGrowTimer();', 1000); //This is for demonstration
	};

function autoGrowTimer() { //Can be removed.
  paragraphs_added++; //Increase the count
  autoGrowDiv = document.getElementById('autoGrow');
  //autoGrowDiv.innerHTML = autoGrowDiv.innerHTML + "<p>This is making the iframe taller.</p>";
  //Stop after 50 paragraphs aded
  if (paragraphs_added > 50) return;

  setTimeout('autoGrowTimer();', 1000);
}
</script>