
								<div class="top-fan">
									<div class="row profile_background">

									<?php $count = 0; ?> 
									<?php foreach($this->top_fans as $top_fan): ?>
									
									<?php if ($count == 0){?>
									
										<ul class="top-list mini">
											<li>
												<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="flag">
														<a data-userid="<?= $top_fan['facebook_user_id'] ?>" <? if (!($this->relation[$count] == 'Fanpage')){?>onclick="userProfile('<?= $top_fan['facebook_user_id'] ?>')"<?}?> 
														rel="popover" data-content="" data-original-title="" data-placement="left"> 
														
															<span class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture" onerror="ImgError(this);"></span>
															
															
															<span class="name first">
																<?= $top_fan['fan_first_name'] ?>
															</span>
														</a> 
														</div>
												
														<div class="follow">
														<?php if ($this->topFanArray[$count] != 'You'){?>
														
														<a <?if (($this->topFanArray[$count] != 'Following') /*&& ($this->topFanArray[$count] != 'Friends') */) {?>
																onclick="follow(<?=$top_fan['facebook_user_id']?> , '<?=$top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>', 'topfan_follow_<?=$top_fan['facebook_user_id']?>')" class = "topfan_follow_<?=$top_fan['facebook_user_id']?>"
																<?}else{ ?>
																onclick="unfollow(<?=$top_fan['facebook_user_id']?> , '<?=$top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>', 'topfan_follow_<?=$top_fan['facebook_user_id']?>')" class = "topfan_follow_<?=$top_fan['facebook_user_id']?>"
																<?}?>
															>
															<span class="badge badge-<?= $this->topFanArray[$count]?>"><?= $this->topFanArray[$count]?></span>
														</a>
														<?php }else{?>
															<span class="badge badge-You">You</span>
														
														<?php }?>	</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="mini-top-fans" class="top-list mini">
										<?php }?>
											<li>
								
													<div class="border-dark">
											
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="flag">
														<a data-userid="<?= $top_fan['facebook_user_id'] ?>" <? if (!($this->relation[$count] == 'Fanpage')){?>onclick="userProfile('<?= $top_fan['facebook_user_id'] ?>')"<?}?> 
															rel="popover" data-content="" data-original-title="" data-placement="left"> 
															
																<span class="photo"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture" onerror="ImgError(this);"></span>
																
																
																<span class="name">
																	<?= $top_fan['fan_first_name'] ?>
																</span>
														</a> 
													</div>
													<div class="follow">
													<?php if ($this->topFanArray[$count] != 'You'){?>
														
														<a <?if (($this->topFanArray[$count] != 'Following')/* && ($this->topFanArray[$count] != 'Friends')*/) {?>
																onclick="follow(<?=$top_fan['facebook_user_id']?> , '<?=$top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>', 'topfan_follow_<?=$top_fan['facebook_user_id']?>')" id = "topfan_follow_<?=$top_fan['facebook_user_id']?>"
																<?}else{ ?>
																onclick="unfollow(<?=$top_fan['facebook_user_id']?> , '<?=$top_fan['fan_first_name'].' '.$top_fan['fan_last_name']?>', 'topfan_follow_<?=$top_fan['facebook_user_id']?>')" id = "topfan_follow_<?=$top_fan['facebook_user_id']?>"
																<?}?>
															>
															<span class="badge badge-<?= $this->topFanArray[$count]?>"><?= $this->topFanArray[$count]?></span></a>
														<?php }else{?>
															<span class="badge badge-You">You</span>
														
														<?php }?> </div>
												</div>
											</li>
											
									<?php }?>
									
									<?php $count ++; ?>
									<?php endforeach; ?>
										
									<?php if ($count < 5){?>
										<?php if ($count == 0){?>
											<ul class="top-list mini">
												<li>
													<div class="border-dark first">
														<div class="rank first">
															<h1>
																<?= $count + 1 ?>
															</h1>
														</div>
														<div class="photo"></div>
														<div class="name"></div>
														<div class="points"></div>
													</div>
												</li>
												<?php $count++;?>
											</ul>
										<?php }?>
										<?php for ( ;$count<5; $count++){ ?>
											<?php if ($count == 1){?>
												<ul  id="mini-top-fans" class="top-list mini">
											<?php }?>
											<li>
													<div class="border-dark">
											
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														</div>
													<div class="name">
															</div>
													<div class="points">
														
													</div>
												</div>
											</li>
										<?}?>
									<?}?>
									</ul>
									
									<?php $count ++; ?>
									<ul class="top-list mini">
										<li>
								
													<div class="border-dark">
											
													<div class="rank">
														
														<? if (strlen($this->topFanYou['my_rank'])== 1){?>
															<h1><?= $this->topFanYou['my_rank']?></h1>
														<?php }elseif (strlen($this->topFanYou['my_rank'])== 2) { ?>
															<h2><?= $this->topFanYou['my_rank']?></h2>
														<?php }elseif (strlen($this->topFanYou['my_rank'])== 3) { ?>
															<h3><?= $this->topFanYou['my_rank']?></h3>
														<?php }else{?>
															<h1>*</h1>
														<?php }?>
														
															
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->user_id ?>/picture" onerror="ImgError(this);"></a>	
													</div>
													<div class="name">
														<a href="#" >YOU</a>
														<br/>
													</div>
													<div class="follow">
														<div class="badge badge-You">You</div>
													
													</div>
												</div>	
										</li>
									</ul>
									
								</div>
							</div>
							
						</div>
						
