<div id="wrapper">

	<div id="header">
    
    	<div id="logo"></div>
        
    </div><!--/end header -->
    
    <div id="content">
    
        <div id="ranking">
        
			<div id="top_fans">
		
				<div class="tip"><a title="You are awesome and nobody can touch you!<br /><br />But <i>seriously</i>, your ranking is determined by the amount of posts, comments and likes you make to the page.<br /><br />If you're top 5 that means you interact with our brand the most!">?</a></div>
				
				<h2>Top Fan <span>|&nbsp;&nbsp;Most Active Fan</span></h2>
				

				<?php $count = 0; ?> 
				
				<div class="panel up">

				<?php foreach($this->top_fans as $top_fan): ?>
			
					<div class="border<?= ($count == 0 ? ' first' : '') ?>">
					
						<div class="rank"><h2><?= $count + 1 ?></h2></div>
						
						<div class="photo">
						
							<a target="_blank" href="https://facebook.com/<?= $top_fan['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"></a>
						
						</div>
						
						<div class="name"><a target="_blank" href="https://facebook.com/<?= $top_fan['facebook_user_id'] ?>"><?= $top_fan['fan_name'] ?></a></div>
						
						<div class="points"><p><?= $top_fan['num_likes'] ?><span>Points<br>this Week</span></p></div>
						
						<div class="clearfix"></div>
					
					</div><!--end border -->
					<?php $count ++; ?>
				<?php endforeach; ?>

				</div>
				
				<div class="shadow"><p class="toggle flip">+ More</p></div>
			
			</div><!--end top_fans -->
			
			
			<div id="fan_favorite">
			
				<div class="tip"><a title="People like you. Your mom was right!<br /><br />But <i>seriously</i>, your contribution is well regarded within the community. People like your posts and interact with you a lot.<br /><br />Keep up the good work!">?</a></div>
			
				<h2>Fan Favorite <span>|&nbsp;&nbsp;Received most likes</span></h2>
				
		  		<div class="panel up">	

		  			<?php if (!count($this->most_popular)): ?>
		  				<div class="border<?= ($count == 0 ? ' first' : '') ?>">
							<div class="name">NO FANS</div>
		  				</div>
		  			<?php endif; ?>

		  			<?php $count = 0; ?>

		  			<?php foreach($this->most_popular as $popular): ?>

		  				<div class="border<?= ($count == 0 ? ' first' : '') ?>">

	  						<div class="rank"><h2><?= $count + 1 ?></h2></div>

	  						<div class="photo">
							
								<a target="_blank" href="https://facebook.com/<?= $popular['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"></a>
							
							</div>
							
							<div class="name"><a target="_blank" href="https://facebook.com/<?= $popular['facebook_user_id'] ?>"><?= $popular['fan_name'] ?></a></div>
							
							<div class="points"><p><?= $popular['count'] ?><span>Got Liked<br />this Week</span></p></div>
							
							<div class="clearfix"></div>
							<?php $count++; ?>
		  				</div>
		  			<?php endforeach; ?>
			
				</div><!--end panel -->
			
				<div class="shadow"><p class="toggle flip">+ More</p></div>
			
			</div><!--/end fans favorite -->
		
			<div id="top_talker">
				
				<div class="tip"><a title="Loud and proud! You don't care what time of the night it is, you keep barking!<br /><br />But <i>seriously</i>, your posts and comments help shape the conversations.<br /><br />Keep it loud. Keep it proud.">?</a></div>
				
				<h2>Top Talker <span>|&nbsp;&nbsp;Most Comments</span></h2>
				
				<div class="panel up">
					
					<?php if (!count($this->top_talker)): ?>
		  				<div class="border<?= ($count == 0 ? ' first' : '') ?>">
							<div class="name">NO TALKER</div>
		  				</div>
		  			<?php endif; ?>

		  			<?php $count = 0; ?>

		  			<?php foreach($this->top_talker as $talker): ?>
		  				<div class="border<?= ($count == 0 ? ' first' : '') ?>">

	  						<div class="rank"><h2><?= $count + 1 ?></h2></div>

	  						<div class="photo">
							
								<a target="_blank" href="https://facebook.com/<?= $talker['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"></a>
							
							</div>
							
							<div class="name"><a target="_blank" href="https://facebook.com/<?= $talker['facebook_user_id'] ?>"><?= $talker['fan_name'] ?></a></div>
							
							<div class="points"><p><?= $talker['number_of_posts'] ?><span>Got Liked<br />this Week</span></p></div>
							
							<div class="clearfix"></div>
							<?php $count++; ?>

		  				</div>
		  			<?php endforeach; ?>
				
				</div><!--end panel -->
				
				<div class="shadow"><p class="toggle flip">+ More</p></div>
				
			</div><!--end top_talker -->

			
			<div id="top_clicker">
			
				<div class="tip"><a title="Is there anything you don't like? Even Lindsey Lohan has standards --insert chuckle--.<br /><br />But <i>seriously</i>, we're glad you take interest in your peers.<br /><br />Happy clicking!.">?</a></div>
				
				<h2>Top Clicker <span>|&nbsp;&nbsp;Liked most items</span></h2>
				
				<div class="panel up">
				
					<?php if (!count($this->top_clicker)): ?>
		  				<div class="border<?= ($count == 0 ? ' first' : '') ?>">
							<div class="name">NO TALKER</div>
		  				</div>
		  			<?php endif; ?>

		  			<?php $count = 0; ?>

		  			<?php foreach($this->top_clicker as $clicker): ?>
		  				<div class="border<?= ($count == 0 ? ' first' : '') ?>">

	  						<div class="rank"><h2><?= $count + 1 ?></h2></div>

	  						<div class="photo">
							
								<a target="_blank" href="https://facebook.com/<?= $clicker['facebook_user_id'] ?>"><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"></a>
							
							</div>
							
							<div class="name"><a target="_blank" href="https://facebook.com/<?= $clicker['facebook_user_id'] ?>"><?= $clicker['fan_name'] ?></a></div>
							
							<div class="points"><p><?= $clicker['number_of_likes'] ?><span>Got Liked<br />this Week</span></p></div>
							
							<div class="clearfix"></div>
							<?php $count++; ?>

		  				</div>
		  			<?php endforeach; ?>
				
				</div><!--end panel -->
				
				<div class="shadow"><p class="toggle flip">+ More</p></div>
			
			</div><!--end top_clicker -->
	                
	    </div><!--/end ranking -->
	        
	    <div class="clear"></div>
	        
	</div><!--/end content -->

</div><!--/end wrapper -->


<!--


<hr />


<p>top talkers</p>

<pre>
<?= print_r($this->top_talkers) ?>
</pre>

<p>top clickers</p>

<pre>
<?= print_r($this->top_clickers) ?>
</pre>

<p>top fans</p>

<pre>
<?= print_r($this->top_fans) ?>
</pre>

<p>most popular</p>

<pre>
<?= print_r($this->most_popular) ?>
</pre>

-->