<?php foreach ($this->upcoming as $b){?>
	<div class="span2 upcoming-badges">
		<div class="progress">
			<div class="bar" style="width: <?= $b['percentage']?>%;"></div>
			<a class="noclick" data-original-title="<?= $b['name']. '<br/>'.$b['description'].'<br/>'.$b['percentage'].'% Completed'?>" 
			rel="tooltip" data-placement="top-left"  >
				
				<img src="<?= $b['picture']?>" style="opacity:<?= $b['percentage']/100?>"/>
			</a>
		</div>
	</div>
<?php }?> 
