<div class="row">
<div class="span7">

<div class="title">
	
	<div class="title-icon">
		<img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $this->user_id ?>/picture">
	</div>
	
	<div class="title-header">
		<?=$this->user_name?>'s <?= $this->title?> List
	
	</div>
	
</div>

<div class="link-back">Go back to <a onclick="userProfile('<?= $this->user_id?>', false)"><?= $this->user_name?></a>'s Profile</div>

<div class="row box" id="user_list">
	<ul class="top-list">
	<?php if(count($this->result)==0){?>
		<li >
			<div class="ranker">
				<div class="user">
					<div class="photo"><img class="face" width="30" height="30" src="/img/profile-picture.png" onerror="ImgError(this);"></div>
				
					<div class="name">No users</div>
				
				</div>
			
			</div>
		</li>
	<?php }?>
	
	
	<?php $count=0;?>
	<?php foreach ($this->result as $user):?>	
		<li>

			<div class="ranker" >
		
				<div class="user">
					<div class="photo">
						<a  data-userid="<?= $user['facebook_user_id'] ?>"
											<? if (!($this->relation[$count] == 'Fanpage')){?>
												onclick="userProfile('<?= $user['facebook_user_id'] ?>', false)"
												<?}?> rel="popover" data-content="" data-original-title=""
												data-placement="top">
						<img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $user['facebook_user_id'] ?>/picture">
						</a>
					</div>
					
					<div class="name">
						<a  data-userid="<?= $user['facebook_user_id'] ?>"
											<? if (!($this->relation[$count] == 'Fanpage')){?>
												onclick="userProfile('<?= $user['facebook_user_id'] ?>' , false)"
												<?}?> rel="popover" data-content="" data-original-title=""
												data-placement="top"><?= $user['facebook_user_first_name'] .' '. $user['facebook_user_last_name'] ?></a>
						
					</div>
					<!--   <br/><?if($this->title == 'Followers') {echo "Followed";}else{ echo "Following";} ?>  since <span class="time"
									title="" data-unix-time="<?= strtotime($user['created_time'])?>"></span>	-->
				</div>
				
				<div class="badge-profile">
					
						<a <?php if ($this->relation != 'You') {?>
								<? if (($this->relation != 'Following') /*&& ($this->relation[$count] != 'Friends')*/){?>
								onclick="follow(<?= $user['facebook_user_id'] ?>, '<?= $user['facebook_user_first_name'].' '.$user['facebook_user_last_name'] ?>')">
								<?}else{?> 
								onclick="unfollow(<?= $user['facebook_user_id'] ?>, '<?= $user['facebook_user_first_name'].' '.$user['facebook_user_last_name'] ?>')">
								<?}	?> 
							<span class="badge badge-<?= $this->relation[$count]?> big"><?= $this->relation[$count]?>
							<?}else{?> 
							<span class="badge badge-You?> big">You</span>
							<?}?>
					 	</a>

				</div>
				
				
			</div>
		</li>
	<?php $count++;?>
	<?php endforeach; ?>
	
	
	</ul>
</div>
<?php if ($count > 14){?>

	<button class="btn-more" onclick="
	<?php if ($this->title == 'Followers') { 
		echo'getFollowersList('.$this->user_name.','.$this->user_id.',0, false)'; 
	}elseif ($this->title =='Friends'){ 
		echo 'getFriendsList('.$this->user_name.','.$this->user_id.',0, false)'; 
	}else{ 
		echo 'getFollowingList('.$this->user_name.','.$this->user_id.',0, false)';
	}?>"> 
		+ More
	</button>


<?php }?>
</div>
</div>