<div class="panel">
	<div class="rvrow">
		<div class="rvgrid-9">
			
			<div class="box">
				<div class="title nopic">
					
					<div class="title-header nopic">What is Fancrank?</div>
					
				</div>
				<div id="whatisfancrank">
					<a class='fancrank_login' href="/app/login/<?= $this->fanpage_id ?>"><img src="/img/whatisfancrank.jpg"/></a>
				</div>
			</div>
		</div>
		<div class="rvgrid-9">
			<div class="top-fan" id="login">
				
				
			
					<div class="box">
						<div class="title nopic">
							
							<div class="title-header nopic">
								Top Fans Last Week
							</div>
							<div class="tip2">
								The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!
							</div>
						</div>
							
						<?php foreach($this->top_fans_last_week as $top_fan):  ?>
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?=$top_fan['rank']?>
										</h1>
									</div>

									<div class="user">
										
										<div class="photo">
											<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
												<img class="small-face"  src="https://graph.facebook.com/<?=$top_fan['facebook_user_id'] ?>/picture"
												onerror="ImgError(this);">
											</a>
										</div>
												
										<div class="name first">
											<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
												<?=$top_fan['fan_first_name']?>
											</a>
										</div>
									</div>

									<div class="points">
									
									</div>
								</div>
							</li>

						</ul>
					
							<?php endforeach; ?>

							<ul class="top-list bottom">
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank">
											<? if (strlen($this->popularYou['my_rank'])== 1){?>
											<h1>
												<?= $this->popularYou['my_rank']?>
											</h1>
											<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
											<h2>
												<?= $this->popularYou['my_rank']?>
											</h2>
											<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
											<h3>
												<?= $this->popularYou['my_rank']?>
											</h3>
											<?php }else{?>
											<h1>*</h1>
											<?php }?>
										</div>
										<div class="user">
											<div class="photo">
												<img class="small-face"
													src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
													onerror="ImgError(this);">
											</div>
											<div class="name">
												<a class="noclick">YOU</a>
											</div>
										</div>
										
										<div class="points">
											<h1><a class='fancrank_login' href="/app/login/<?= $this->fanpage_id ?>">LOGIN</a>
											</h1>
											<div class="seerank">TO SEE YOUR RANK!</div>
										</div>
									
									</div>
								</li>
							</ul>
							
				</div>
			
			</div><!-- topfan -->
		</div><!-- span -->
	</div><!-- row -->

	<div class="rvrow">

			<div class="top-fan-all rvgrid-18 box">

					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/top-fan-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Top Fans This Time
						</div>
						<div class="tip2">
							The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!
						</div>
						<!--  <div class="tip">
								<a rel="tooltip" title="The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!">?</a>
							</div>-->
					</div>
					
						<?php $count = 0; ?> 
						<?php foreach($this->top_fans as $top_fan):  ?>
						<?php if ($count == 0){?>
						
					
						<ul class="top-list first">
							<li>
								<div class="ranker first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>

									<div class="user">
										
										<div class="photo">
											<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
												<img class="small-face"  src="https://graph.facebook.com/<?=$top_fan['facebook_user_id'] ?>/picture"
												onerror="ImgError(this);">
											</a>
										</div>
												
										<div class="name first">
											<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
												<?=$top_fan['fan_first_name']?>
											</a>
										</div>
									</div>

									<div class="points">
										<h3>
											<?= $top_fan['count'] ?>
										</h3>
										<span>Points</span>
									
									</div>
								</div>
							</li>

						</ul>
						<?php }else{ ?>
							<?php if ($count == 1){?>
							<ul id="top-fans-collapse" class="top-list">
							<?php }?>
								<li>
									<div class="ranker ">
										<div class="rank">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
											
												<div class="photo">
													<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
													<img class="small-face" 
													src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"
													onerror="ImgError(this);">
													</a>
												</div>
												<div class="name">
													<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
														<?=$top_fan['fan_first_name'] ?>
													</a>
												</div>
										</div>
										<div class="points">
											<h3>
												<?= $top_fan['count'] ?>
											</h3>
											<span>Points</span>
											
										</div>
									</div>
								</li>
	
							<?php }?>
							
							<?php $count ++; ?>
					
							<?php endforeach; ?>

						<?php if ($count < 5){?>
							<?php if ($count == 0){?>
							<ul class="top-list <?= ($count == 0 ? ' first' : '') ?>">
								<li>
									<div class="ranker first">
										<div class="rank first">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
											<div class="photo"></div>
											<div class="name"></div>
										</div>
										<div class="points"></div>
									</div>
								</li>
								<?php $count++;?>
							</ul>
							<?php }?>
						
						
							<?php for ( ;$count<5; $count++){ ?>
						
							<?php if ($count == 1){?>
							<ul  id="top-fans-collapse" class="top-list collapse in">		
							<?php }?>
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="user">
											<div class="photo"></div>
											<div class="name"></div>
										</div>
										<div class="points"></div>
									</div>
								</li>
								
							
							<?}?>
						<?}?>		
							</ul>
						
							<ul class="top-list bottom">
								<li>
									<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank">
											<? if (strlen($this->popularYou['my_rank'])== 1){?>
											<h1>
												<?= $this->popularYou['my_rank']?>
											</h1>
											<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
											<h2>
												<?= $this->popularYou['my_rank']?>
											</h2>
											<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
											<h3>
												<?= $this->popularYou['my_rank']?>
											</h3>
											<?php }else{?>
											<h1>*</h1>
											<?php }?>
										</div>
										<div class="user">
											<div class="photo">
												<img class="small-face"
													src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
													onerror="ImgError(this);">
											</div>
											<div class="name">
												<a class="noclick">YOU</a>
											</div>
										</div>
										
										<div class="points">
											<h1><a class='fancrank_login' href="/app/login/<?= $this->fanpage_id ?>">LOGIN</a>
											</h1>
											<div class="seerank">TO SEE YOUR RANK!</div>
										</div>
									
									</div>
								</li>
							</ul>
			</div><!-- topfan -->

	</div><!-- row -->
</div><!-- panel -->