<div class="panel">
						<div class="row">
							<div class="span6">
								<div class="top-fan">
									<div class="title">
										<div class="photo"> <img src="/img/news-feed/top-fan-icon.jpg" /> </div>
										<div class="title-header"> <h3> Top Fans  </h3>
											<div class="tip"><a title="You are awesome and nobody can touch you! <br /><br />But <i>seriously</i>, your ranking is determined by the amount of posts, comments and likes you make to the page.<br /><br />If you're top 5 that means you interact with our brand the most!">?</a></div>
										 </div>
									</div>
									
								
									
									<?php $count = 0; ?> 
									<?php foreach($this->top_fans as $top_fan): ?>
									
									<?php if ($count == 0){?>
									
										<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" href="#" ><?= $top_fan['fan_first_name'] ?></a>
															<br/>
														</div>
														<div class="points">
															<h3><?= $top_fan['number_of_posts'] ?></h3> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="top-fans-collapse" class="top-list collapse">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?> href="#"><?= $top_fan['fan_first_name'] ?></a>
														<br/>
													</div>
													<div class="points">
														<h3><?= $top_fan['number_of_posts'] ?> </h3> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
										
									<?php if ($count < 5){?>
										
										<?php for ( ;$count<5; $count++){ ?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														</div>
													<div class="name">
															</div>
													<div class="points">
														
													</div>
												</div>
											</li>
										<?}?>
									<?}?>
									
									
									</ul>
									<?php $count ++; ?>
									<ul class="top-list">
										<li>
												<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1>*</h1>
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $this->user_id ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?> href="#" >YOU</a>
														<br/>
													</div>
													<div class="points">
														<span class="align-right"><h3>LOGIN</h3><br/> TO SEE YOUR RANK!</span> 
													</div>
												</div>
										</li>
									</ul>
									<div class="shadow">
										<button class="btn-top" id="top-fans-btn" data-toggle="collapse" data-target="#top-fans-collapse">
												+ More
										</button>
									</div>
								</div>
								
								<div class="fan-favorite">
									<div class="title">
										<div class="photo"> <img src="/img/news-feed/fan-fav-icon.jpg" /> </div>
										<div class="title-header"> <h3>Fan Favorite</h3>
											<div class="tip"><a title="People like you. Your mom was right!<br /><br />But <i>seriously</i>, your contribution is well regarded within the community. People like your posts and interact with you a lot.<br /><br />Keep up the good work!">?</a></div>
										</div>
									</div>
									<?php $count = 0; ?> 
									<?php foreach($this->most_popular as $popular): ?>
									<?php if ($count == 0){?>
									<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a   href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" href="#" ><?= $popular['fan_first_name'] ?></a>
															<br/>
														</div>
														<div class="points">
															<h3><?= $popular['count'] ?> </h3> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
									</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="fan-favorite-collapse" class="top-list collapse">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a   href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  href="#" ><?= $popular['fan_first_name'] ?></a>
														<br/>
													</div>
													<div class="points">
														<h3><?= $popular['count'] ?> </h3> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									<?php if ($count < 5){?>
										
										<?php for ( ;$count<5; $count++){ ?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														</div>
													<div class="name">
															</div>
													<div class="points">
														
													</div>
												</div>
											</li>
										<?}?>
									<?}?>
									</ul>
									<?php $count ++; ?>
									<ul class="top-list">
										<li>
												<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1>*</h1>
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $this->user_id ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?> href="#" >YOU</a>
														<br/>
													</div>
													<div class="points">
														<span class="align-right"><h3>LOGIN</h3><br/> TO SEE YOUR RANK!</span> 
													</div>
												</div>
										</li>
									</ul>							
								
									<div class="shadow">
										<button class="btn-top" id="fan-favorite-btn" data-toggle="collapse" data-target="#fan-favorite-collapse">
												+ More
										</button>
									</div>
								</div>
							
							</div>
							
							<div class="span6">
								<div class="top-talker">
									<div class="title">
										<div class="photo"> <img src="/img/news-feed/top-talker-icon.jpg" /> </div>
										<div class="title-header"> <h3>   Top Talker   </h3> 
											<div class="tip"><a title="Loud and proud! You don't care what time of the night it is, you keep barking!<br /><br />But <i>seriously</i>, your posts and comments help shape the conversations.<br /><br />Keep it loud. Keep it proud.">?</a></div>
										</div>
									</div>
									<?php $count = 0; ?> 
									<?php foreach($this->top_talker as $talker): ?>
									<?php if ($count == 0){?>
									<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" href="#" ><?= $talker['fan_first_name'] ?></a>
															<br/>
														</div>
														<div class="points">
															<h3><?= $talker['number_of_posts'] ?> </h3> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="top-talker-collapse" class="top-list collapse">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?> href="#" ><?= $talker['fan_first_name'] ?></a>
														<br/>
													</div>
													<div class="points">
														<h3><?= $talker['number_of_posts'] ?> </h3> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									<?php if ($count < 5){?>
										
										<?php for ( ;$count<5; $count++){ ?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														</div>
													<div class="name">
															</div>
													<div class="points">
														
													</div>
												</div>
											</li>
										<?}?>
									<?}?>
									</ul>
									<?php $count ++; ?>
									<ul class="top-list">
										<li>
												<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1>*</h1>
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $this->user_id ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?> href="#" >YOU</a>
														<br/>
													</div>
													<div class="points">
														<span class="align-right"><h3>LOGIN</h3><br/> TO SEE YOUR RANK!</span> 
													</div>
												</div>
										</li>
									</ul>
									<div class="shadow">
										<button class="btn-top" id="top-talker-btn" data-toggle="collapse" data-target="#top-talker-collapse">
												 + More
										</button>
									</div>
								</div>
							
								<div class="top clicker">
										<div class="title">
											<div class="photo"> <img src="/img/news-feed/top-clicker-icon.jpg" /> </div>
											<div class="title-header"> <h3>   Top Clicker   </h3> 
												<div class="tip"><a title="Is there anything you don't like? Even Lindsey Lohan has standards --insert chuckle--.<br /><br />But <i>seriously</i>, we're glad you take interest in your peers.<br /><br />Happy clicking!.">?</a></div>
											</div>
										</div>
										
										<?php $count = 0; ?> 
									<?php foreach($this->top_clicker as $clicker): ?>
									<?php if ($count == 0){?>
									<ul class="top-list">
											<li>
												<div class="border-dark">
												
														<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
															<h1><?= $count + 1 ?></h1>
														</div>
														<div class="photo">
															<a  href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"></a>	
														</div>
														<div class="name">
															<a class="first" href="#" ><?= $clicker['fan_first_name'] ?></a>
															<br/>
														</div>
														<div class="points">
															<h3><?= $clicker['number_of_likes'] ?></h3> <span>Points <br/>This Week</span>
														</div>
													</div>
											</li>
											
										</ul>
									<?php }else{ ?>
										<?php if ($count == 1){?>
											<ul  id="top-clicker-collapse" class="top-list collapse">
										<?php }?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
												<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														<a  href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?>  href="#" ><?= $clicker['fan_first_name'] ?></a>
														<br/>
													</div>
													<div class="points">
														<h3><?= $clicker['number_of_likes'] ?> </h3> <span>Points <br/>This Week</span>
													</div>
												</div>
											</li>
											
									<?php }?>
									<?php $count ++; ?>
									<?php endforeach; ?>
									<?php if ($count < 5){?>
										
										<?php for ( ;$count<5; $count++){ ?>
											<li>
											<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1><?= $count + 1 ?></h1>
													</div>
													<div class="photo">
														</div>
													<div class="name">
															</div>
													<div class="points">
														
													</div>
												</div>
											</li>
										<?}?>
									<?}?>
									</ul>
									<?php $count ++; ?>
									<ul class="top-list">
										<li>
												<?php if ($count % 2 == 0) {?>
													<div class="border-dark">
												<?php  }else{  ?>
													<div class="border-light">
												<?php }?>
													<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
														<h1>*</h1>
													</div>
													<div class="photo">
														<a href="#" ><img class="face" width="50" height="50" src="https://graph.facebook.com/<?= $this->user_id ?>/picture"></a>	
													</div>
													<div class="name">
														<a  <?php if ($count == 0){?>class='first'<?php }?> href="#" >YOU</a>
														<br/>
													</div>
													<div class="points">
														<span class="align-right"><h3>LOGIN</h3><br/> TO SEE YOUR RANK!</span> 
													</div>
												</div>
										</li>
									</ul>	
									 
										<div class="shadow">
											<button class="btn-top" id="top-clicker-btn" data-toggle="collapse" data-target="#top-clicker-collapse">
													+ More
											</button>
										</div>
									</div>
								
							</div>
						
						
						
							<!-- REDUNDANT YOU CAN GET THIS INFORMATION ON THE FEED -->
							<!-- 
							<div class="span4">
									<div class="subtitle">
											<div class="title-header-dark"> <h3> </i> Latest Post  </i></h3> </div>
									</div>
									<ul class="bubble" id="latestpost">
											
											
										</ul>
							</div>
							-->
						</div>

				
				
</div>		


