<!--  pre login page -->
<div class="padding">
<div class="box" style="text-align:center">
<img src="/img/logo-noline.png">
</div>
<br/><br/>
<div class = "box" style="text-align:center">

<h3>Welcome to the FanCrank Admin Page</h3>
<br/>
Before getting started, please take note that we'll need to take some of your Facebook Information inorder for this process to work.
<br/>
We'll be taking your Basic Information (Your Name, Facebook Id, Gende, Locale), Your Email, and we're also going to be looking at what pages you're an admin of.

<br/>
<br/>
<button class="login" >Login</button>
</div>

<br/>
<br/>
</div>