<div class="center failure">
    <div>
        <h1>Sorry</h1>
        <p><?= $this->error ?></p>
        <p><a href="#">Close this Window</a></p>
    </div>
</div>
<script type="text/javascript">
    window.addEvent('domready', function() {
        this.focus();

        document.getElement('a').addEvent('click', function(event) {
            event.preventDefault();
            self.close();
        });

        if (window.opener != null) {
            // tell the opener window that we're done
            window.opener.document.fireEvent('authFailure');
            self.close.delay(7000);
        }
    });

    jQuery(document).ready(function($){

        $('a').click(function(event){
            event.preventDefault();
            self.close();
        });

        if (window.opener != null) {
            self.close();
        }
    });
</script>
