<div class="center failure">
    <div>
        <h1>Sorry</h1>
        <p><?= $this->error ?></p>
        <p><a href="#">Close this Window</a></p>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){

        $('a').click(function(event){
            event.preventDefault();
            self.close();
        });

        if (window.opener != null) {
            self.close();
        }
    });
</script>
