<!--  pre login page -->
<input id="print-button" type="button" value="Print this page" onclick="printpage()">
<div class="row-fluid">
	<div class="span6">
		<h3>Fans Info</h3>

		Fan Name: <?=$this->redeemDetail['fan_first_name'] . ' ' . $this->redeemDetail['fan_first_name']?>
		<br/>
		Email:<?=$this->shippingInfo['email']?>
		<br/>
		<img src="<?=$this->redeemDetail['fan_user_avatar']?>" />
	
	</div>

	<div class="span6">
		<h3>Shipping Information</h3>
	
		
		<?=strtoupper($this->shippingInfo['name'])?>
		<br/>
		<?=strtoupper($this->shippingInfo['address'])?>
		<br/>
		<?=strtoupper($this->shippingInfo['city'])?>, <?=strtoupper($this->shippingInfo['region'])?> 
		<br/>
		<?=strtoupper($this->shippingInfo['country'])?>
		<br/>
		<?=strtoupper($this->shippingInfo['postcode'])?>
	
	</div>
</div>	
<div class="row-fluid">
	<div class="span6">
		<h3>Item</h3>

		
		Item Name: <?=$this->redeemDetail['name']?>
		<br/>
	
		Item Description: <?=$this->redeemDetail['description']?>
		<br/>
		<img src="/img/item/<?=$this->redeemDetail['picture']?>" style="width:100px">
			

	
	</div>
	<div class="span6">
			
		<h3>Redeem By Badge</h3>
	
	
		Badge Name:<?=$this->badgeDetail['name']?>
		<br/>
		
		<div class="progress" >
			<div class="bar" style="width:100%"></div>
			<a>
				<img src="<?=$this->badgeDetail['picture']?>" alt=""/>
			</a>
		</div>
		
		
	
	</div>
</div>
	
	

<script>
function printpage()
  {
	w=window.open();
	$('#print-button').hide();
	w.document.write('<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>');
	w.document.write('<link href="/css/new_admin.css" rel="stylesheet" type="text/css"" />');
	w.document.write($('#redeemDetailModal').html());
	w.print();
	$('#print-button').show();
	w.close();
  }
</script>

