
						<div class="row">
							<div class="span12">
								<div class="title">
									<div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->facebook_user->facebook_user_id ?>/picture" onerror="ImgError(this);"></a></div>
									<div class="title-header"> <h3><?echo $this->facebook_user->facebook_user_first_name .' '. $this->facebook_user->facebook_user_last_name ?>'s Awards</h3> </div>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="span12">
							<div class="row profile_background">
									<div class="span12">
				<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////// -->
										
												<div class="profile-block">
													<h4>Corkboard</h4>
														
												</div>
										
				<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////// -->
									</div>
								</div>
							</div>
								
						</div>
						<div class="feed_spacer_top"></div>
						
						
						<div class="row">
						<div class="span12">
							<div class="row profile_background">
							
				<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////// -->
									
									
										<div class="span12">
										

											<div class="profile-block">
											<h4>Overall Achievement</h4>
											<div class="progress">
												<div class="bar" style="width: <?= $this->overall_achievement?>%;">
												</div>
												
											</div>
											<h5><?=$this->user_badge?>/<?=$this->all_badge?> </h5>
											</div>
										</div>
									
									
										
									
											
											<div class="span6">
											
										
													<div class="profile-block">
														<h4>Personal Achievement</h4>
														<div class="progress">
															<div class="bar" style="width: 60%;"></div>
														</div>
													</div>
												</div>
									
											<div class="span6">
												
											
													<div class="profile-block">
														<h4>Social Achievement</h4>
														<div class="progress">
															<div class="bar" style="width: 60%;"></div>
														</div>
													</div>
											</div>
											
									
				<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////// -->
									</div>
								</div>
						</div>
						
						<div class="feed_spacer_top"></div>
						<div class="row">
							<div class="span12">
								
								<div class="row profile_background">
									<div class="profile-block">
														<h4>Badges</h4>
										</div>
									<div class="span12" id="badges">
									
				<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////// -->
												<?php $badge = $this->badges?>
												<?php $badgeName = array_keys($this->badges)?>
												
												<?php for($i = 0 ; $i < count($badgeName); $i++){?> 
												<div class="row">
													
													<div class="profile-block">
													<?php $badgeQuantity = array_keys($badge[$badgeName[$i]]);?> 
														<?php for($j = 0 ; $j < count($badgeQuantity); $j++){?>
														<a class="badge_container" rel="tooltip" data-placement="top" 
														data-original-title="<img src='<?= $badge[$badgeName[$i]][$badgeQuantity[$j]]['picture']?>' >
														<?= str_replace('[quantity]',  $badgeQuantity[$j], $badge[$badgeName[$i]][$badgeQuantity[$j]]['description'])?>"><img src="<?= $badge[$badgeName[$i]][$badgeQuantity[$j]]['picture']?>"<?php if ($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] !== 1){?> style="opacity:0.5" <?php }?>/><?php if ($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] !== 1){?><span class="badge_text"><?= $badgeName[$i]?>-<?=$badgeQuantity[$j]?><br/><?= round($badge[$badgeName[$i]][$badgeQuantity[$j]]['percentage'] *100)?>% Completed</span><?php $j = count($badgeQuantity) +1;?><?php }?></a>
													<?}?>
												</div></div>
											<?}?>
										
				<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////// -->
									</div>
								</div>
						</div>
						</div>
						<div class="feed_spacer_top"></div>
						
						
						
					
							
							