
	<div class="rvrow">
		<div class="rvgrid-18">
			<div class="top-fan box">
			
					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/top-fan-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Top Fans for <?= date("F") ?>
						</div>
						<?php if ($this->fanpage_level >2){?>
						<div class="tip2">
							The following list of fans have earned the most points this Month!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!
						</div>
						<?php }else{?>
						<div class="tip2">
							The following list of fans have the highest score this Month!  Increase your score by liking, commenting, and posting on this Facebook page.  Further increase your score when others like your comments or reply to your posts!
						</div>
						<?php }?>
						<!--  <div class="tip">
								<a rel="tooltip" title="The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!">?</a>
							</div>-->
					</div>
			</div><!-- topfan -->
		</div><!-- span -->
	</div><!-- row -->
	
<?php if ($this->fanpage_level > 2){?>
	<div class= "rvrow">
		<div class="rvgrid-9">
			<div class="fan-favorite box">
				
				
				
					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/fan-fav-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Fan Favorites this Week 
							
						</div>
						<div class="tip2">
							This list of fans represents the people who have garnered the most activity from others on the page.  Other fans love talking to them!
						</div>
						<!--  <div class="tip">
								<a rel="tooltip" title="This list of fans represents the people who have garnered the most activity from others on the page.  Other fans love talking to them!">?</a>
						</div>-->
					</div>
					
			
			</div><!-- fanfav -->
		</div><!-- span -->
		<div class="rvgrid-9">
			<div class="top-talker box">
				
			
					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/top-talker-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Top Talkers this Week 
							
						</div>
						<!--  <div class="tip">
								<a rel="tooltip" title="These people have posted the most on the page.  Do they talk too much?  You decide!">?</a>
							</div>-->
						<div class="tip2">
							These people have posted the most on the page.  Do they talk too much?  You decide!
						</div>
					</div>
			

			</div><!-- toptalker -->
		</div><!-- span -->
	</div><!-- row -->

	
	
	<div class="rvrow">
		<div class="rvgrid-9">
			<div class="top-clicker box">
				
			
					<div class="title nopic">
						<!-- <div class="title-icon">
							<img src="/img/news-feed/top-clicker-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
						Top Clickers this Week
							
						</div>
						<!-- <div class="tip">
								<a rel="tooltip" title="Like, like, and like!  These people have clicked Like the most!">?</a>
							</div> -->
						<div class="tip2">
							Like, like, and like!  These people have clicked Like the most!
						
						</div>
					</div>

			</div><!-- topclicker -->
		</div>
		<div class="rvgrid-9">
			<div class="top-followed box">
				
		
					<div class="title nopic">
						<!-- <div class="title-icon">
							<img src="/img/news-feed/fan-fav-icon.jpg" />
						</div> -->
						<div class="title-header nopic">
						Top Followed
							
						</div>
						
						<div class="tip2">
							These people have got the most followers!  Talk about being popular!
						</div>
						
						<!--  <div class="tip">
								<a rel="tooltip" title="These people have got the most followers!  Talk about being popular!">?</a>
						</div>-->
					</div>
					
	
			
					
		
			</div><!-- topfollowed -->
		</div>
	</div><!-- row -->
<?php }?>
<div class="rvrow">
		<div class="rvgrid-18">
			<div class="top-fan-all  box">

					<div class="title nopic">
						<!--  <div class="title-icon">
							<img src="/img/news-feed/top-fan-icon.jpg" />
						</div>-->
						<div class="title-header nopic">
							Top Fans of All Time
						</div>
						<?php if ($this->fanpage_level >2){?>
						<div class="tip2">
							The following list of fans have earned the most points for all time!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!
						</div>
						<?php }else{?>
						<div class="tip2">
							The following list of fans have the highest score for all time!  Increase your score by liking, commenting, and posting on this Facebook page.  You can further increase your score when others like your comments or reply to your posts!
						</div>
						<?php }?>
						
						<!--  <div class="tip">
								<a rel="tooltip" title="The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!">?</a>
							</div>-->
					</div>
					
						
		

			</div><!-- topfan -->
		</div>
	</div><!-- row -->
