<div class="row"> 
	<div class="span8">
		<div class="row box notitle">
			<?php $count = 0?>
			<ul id="popup_post">
				<li class="post-container noline" >
				<div class="user" >		
					<div class="user-badge">
						<a rel="tooltip-follow" class ="follow_<?=$this->post->from->id?>"
							<?php switch($this->relation[$count]) { 
								case 'Fanpage':?>
									class="noclick" data-original-title="You can't Follow an Admin">
										<span class="badge badge-Fanpage">Admin</span>
								<?break;?> 
								<?case 'You':?>
									class="noclick" data-original-title="This is You">
										<span class="badge badge-You">You</span>
								<?break;?>
								<?case 'Following':?>
									onclick="unfollow(<?=$this->post->from->id?> ,'<?=$this->post->from->name?>')" 
									data-original-title="Click to Unfollow this User">
										<span class="badge badge-Following">Following</span>
								<?break;?>
								<?default:?>
									onclick="follow(<?=$this->post->from->id?> , '<?=$this->post->from->name?>')" 				
									data-original-title="Click to Follow this User">
										<span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
							<?}?>
						</a>
					</div>
					<div class="photo">
						<a data-toggle="modal"
							<? if (($this->relation[$count] != 'Fanpage')){?> 
								onclick="userProfile('<?=$this->post->from->id?>')"
								rel="popover" 
								data-content="" 
								data-original-title="" 
								data-placement="right" 
								data-userid="<?=$this->post->from->id?>"
							<?php }else{?>
								class="noclick"
							<? }?> 
						>
							<img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->post->from->id ?>/picture" onerror="ImgError(this);"></a>
					</div>
					<div class="name">
						<a data-toggle="modal"
							<? if (($this->relation[$count] != 'Fanpage')){?> 
								onclick="userProfile('<?=$this->post->from->id?>')"
								rel="popover" 
								data-content="" 
								data-original-title="" 
								data-placement="right" 
								data-userid="<?=$this->post->from->id?>"
							<?php }else{?>
								class="noclick"
							<? }?>  
						>
							<?=  $this->post->from->name?>
						</a>
					</div>
				</div>
				<div class="post">
					<?php if(isset($this->post->message)){ ?>
						<div class="message">
							<?php	$reg_ex = "/\n/";
									$message = $this->escape($this->post->message);
									if(preg_match_all($reg_ex, $message, $url)) {
										$message= preg_replace($reg_ex, "<br/>", $message);
									} 
									$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
									$m = preg_match_all($reg_exUrl, $message, $match); 
									if ($m) { 
									    $links=$match[0]; 
									    for ($j=0;$j<$m;$j++) { 
									        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
									    } 
									} 
									echo $message; 
							?>
							<br/>
						</div>
					<?}	?>
					<div class="graphical">	
					
						<?php if (($this->post->type == 'photo')) {?>	
							<div class="image">
							<a target="new" href="<?echo $this->escape($this->post->link)?> ">
								<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $this->post->picture))?>'/>
							</a></div>
						<?php }elseif ($this->post->type =='video') { ?>
			
								<?php if (strstr($this->escape($this->post->link), 'youtube.com')){
										$temp=explode("http://www.youtube.com/watch?v=", $this->escape($this->post->link));?>
										<iframe width="508" height="286" src="http://www.youtube.com/embed/<?= $temp[1]?> "  frameborder="0" allowfullscreen></iframe>
								
								<?php }else if (strstr($this->escape($this->post->link), 'vimeo.com')){
										$temp=explode("http://vimeo.com/", 	$this->escape($this->post->link));	?>
										<iframe width="508" height="286" src="http://player.vimeo.com/video/<?= $temp[1]?>"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
							
								<?php }else if (strstr($this->escape($this->post->link), 'facebook.com')){
										$temp=explode("v=", $this->escape($this->post->link));?>
									 <object width="508" height="286" > 
									 <param name="allowfullscreen" value="true" /> 
									 <param name="allowscriptaccess" value="always" /> 
									 <param name="movie" value="http://www.facebook.com/v/<?= $temp[1]?>" /> 
									 <embed src="http://www.facebook.com/v/<?= $temp[1]?>" type="application/x-shockwave-flash"  
									   allowscriptaccess="always" allowfullscreen="true" width="508" height="286"> 
									 </embed> 
									</object> 
								<?php }else if (strstr($this->escape($this->post->link), 'liveleak.com/view')){ 
										$temp=explode("view?i=", $this->escape($this->post->link));?>
									<iframe width="508" height="286" src="http://www.liveleak.com/ll_embed?f=<?= $temp[1] ?>" frameborder="0" allowfullscreen></iframe>
								<?php }?>
						<?}elseif ($this->post->type == 'link') {?>
							<div class="link">
								<?php if (isset($this->post->picture)){?>
									<div class="link-left">
										<a target="new" href="<?echo $this->escape($this->post->link)?> "> 
											<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $this->post->picture))?> '/>
										</a>
									</div>
								<?php }?>
								<div class="link-right">
										<a target="new" class="link-title" href="<?echo $this->escape($this->post->link)?>">
											<?= (isset($this->post->name)?$this->escape($this->post->name): $this->escape($$this->post->link))?>
										</a>
										<?php if(isset($this->post->caption)){?>
											<br/>
											<a target="new" class="link-caption" href="<?echo $this->escape($$this->post->link)?> ">
												<?php echo $this->escape($$this->post->caption);?>:  
											</a>
										<?php }?>	
									
										<?php if (isset($post->description)){?>
												<?=$this->escape($this->post->description)?> 
											
										<?php }?>
								</div>
							</div>
						<?}?>
						</div>
					</div>	
			
					<div class="social"> 
						<a class="like-control like_control_<?= $this->post->id?>" rel="tooltip" data-placement="top"
							<?php if ($this->likepost == 0) {?>
								 data-original-title="Click to like this" onclick="like('<?= $this->post->id?>', '<?= $this->post->type?>', '<?=$this->post->from->id?>','<?=$this->post->from->name?>' )" >Like   
							<?}else{?>
								  data-original-title="You like this" onclick="unlike('<?= $this->post->id?>', '<?= $this->post->type?>', '<?=$this->post->from->id?>','<?=$this->post->from->name?>')">Unlike   
							<?php }?>
						</a>
						&middot;
						<a rel="tooltip" data-placement="right" class="time noclick" data-original-title="" data-unix-time="<?=  strtotime($this->post->created_time)?>"></a>
					</div>
					<div class="social like <?=$this->post->id?>"  <?php if(!isset($this->post->likes->count) || ($this->post->likes->count == 0)){?>style="display:none"<?php }?>>
						<a rel="tooltip" data-placement="top" onclick="getLikesList('<?=$this->post->id?>',<? if(isset($this->post->likes->count)){echo $this->post->likes->count;}else{echo '0';} ?>, false)" data-original-title="
							<?php 	$likeslist = (isset($post->likes->data))?$post->likes->data:array();
									$countlikes = count($likeslist);
										for($i = 0; $i < $countlikes - 1; $i++){
											echo $likeslist[$i]->name.', ';
										}
										echo $likeslist[$i]->name;
										if ($countlikes < $this->post->likes->count){
											echo " and ".($this->post->likes->count - $countlikes)." others";
										}
							?> likes this.
						">
							<img src = "/img/thumbsup.png" />
							<span class="like_<?= $this->post->id?>" data-like-count = <? if(isset($this->post->likes->count)){echo $this->post->likes->count;}else{echo '0';} ?>>
								<? if(isset($this->post->likes->count)){echo $this->post->likes->count;}else{echo '0';} ?>
								<? if($this->post->likes->count == 1){?>person<?php }else{?>people<?php }?> 
							</span>
							 likes this.
						</a>		
					</div>
					<div class="social comment <?=$this->post->id?>" <?php if(!isset($this->post->comments->count) || ($this->post->comments->count == 0)){?>style="display:none"<?}?>>
						
						 <a  onclick=" comment_feed3('<?= $this->post->id ?>',
			 							'<?= $this->post->type?>', 
			 							<?= (isset($this->post->comments->count)? $this->post->comments->count : '0')?> , 
								 		false )"> 
										<img src="/img/comment.png" />
								 		<?php if($this->post->comments->count != 1){?> 
								 		View all <span class="comment_<?= $this->post->id?>" data-comment-count=<?php if(isset($this->post->comments->count)){
											echo $this->post->comments->count; //echo  $post->comments->count;
										 	} else {
												echo '0'; 
											}?>>
								 		<?php if(isset($this->post->comments->count)){
											echo $this->post->comments->count; //echo  $post->comments->count;
										 	} else {
												echo '0'; 
											}?>
										</span> 
										comments 
									<?php }else { ?>
										View all<span class="comment_<?= $this->post->id?>" data-comment-count=<?php if(isset($this->post->comments->count)){
											echo $this->post->comments->count; //echo  $post->comments->count;
										 	} else {
												echo '0'; 
											}?>>

										</span>
										comments 
									<?php }?>
									</a>
									<?php if($this->post->comments->count > 5){?> 
									
									
									&middot;
								
									<a  onclick=" comment_feed3_filter('<?= $this->post->id ?>',
						 						'<?= $this->post->type?>', 
						 						<?= (isset($this->post->comments->count)? $this->post->comments->count : '0')?> , 
											 	false)"
											class="comment<?= $this->post->id ?>">Top Comments
									
									
									</a>
									<?php }?>
					</div>
					<?php $count = 0?>
					<div id="popup_post_<?=$this->post->id?>" >
					<ul class="comments popup_scroll" >
						<?php if(empty($this->comments)){
							//echo "Missing Access Token";
						}else{?>
							<?php foreach ($this->comments as $post):?>		
							<li class="comment-container" >
							<div class="photo">
								<a  <? if (($this->relation[$count] != 'Fanpage')){?> 
										onclick="userProfile('<?=$post->from->id?>', false)"
										rel="popover" 
										data-content="" 
										data-original-title="" 
										data-placement="right" 
										data-userid="<?=$post->from->id?>"
									<?php }else{?>
										class="noclick"
									<? }?>  
								>
									<img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $post->from->id ?>/picture" onerror="ImgError(this);">
								</a>
							</div>
							<div class="user">
								<div class="user-badge">
									<a rel="tooltip-follow" class ="follow_<?=$post->from->id?>" 
										<?php switch($this->relation[$count]) { 
											case 'Fanpage':?>
										 		class="noclick" data-original-title="You can't Follow an Admin"><span class="badge badge-Fanpage">Admin</span>
											<?break;?>
											<?case 'You':?>
										 		class="noclick"  data-original-title="This is You"><span class="badge badge-You">You</span>
											<?break;?>
											<?case 'Following':?>
												onclick="unfollow(<?=$post->from->id?> ,'<?=$post->from->name?>')" 
												data-original-title="Click to Unfollow this User"><span class="badge badge-Following">Following</span>
											<?break;?>
										
											<?default:?>
												onclick="follow(<?=$post->from->id?> , '<?=$post->from->name?>')" 				
												data-original-title="Click to Follow this User"><span class="badge badge-<?= $this->relation[$count]?>"><?= $this->relation[$count]?></span>
											<?}?>
									</a>
								</div>	
								<div class="name">
									<a <? if (($this->relation[$count+1] != 'Fanpage')){?> 
										onclick="userProfile('<?=$post->from->id?>', false)"
										rel="popover" 
										data-content="" 
										data-original-title="" 
										data-placement="right" 
										data-userid="<?=$post->from->id?>"
										<?php }else{?> 
										class="noclick"
										<?}?>
									>
										<?=  $post->from->name?>
									</a>
								</div>
								<span class="message">
									<?php if(isset($post->message)){  
										$reg_ex = "/\n/";
										$message = $this->escape($post->message);
										if(preg_match_all($reg_ex, $message, $url)) {
											$message= preg_replace($reg_ex, "<br/>", $message);
										} 
											
										$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
										$m = preg_match_all($reg_exUrl, $message, $match); 
											
										if ($m) { 
											$links=$match[0]; 
											for ($j=0;$j<$m;$j++) { 
												$message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
											} 
										} 	
										echo $message; 
									}?>
									<br/>
								</span>
							</div>
							<div class="social"> 
								<a rel="tooltip" data-placement="top" class="time noclick" data-original-title="" data-unix-time="<?=  strtotime($post->created_time)?>"></a>
								&middot;
								<span class="likes">
									
									<a class="like_<?= $post->id?>" data-like-count=<?=isset($post->likes)?$post->likes:'0'?>  onclick="getLikesList('<?=$post->id?>',<?=isset($post->likes)?$post->likes:'0'?>, false)" rel="tooltip" data-placement="top" data-original-title="Click to See who likes this"><?=isset($post->likes)?$post->likes:'0'?></a>
									 
									<a class="like-control like_control_<?= $post->id?>" rel="tooltip" data-placement="top"
										<?php if ($this->likes[$count] == 0) {?>
									  		data-original-title="Click to like this" onclick="like('<?= $post->id?>', 'comment', '<?=$post->from->id?>','<?=$post->from->name?>')">Like
										<?}else{?>
									  		data-original-title="You like this" onclick="unlike('<?= $post->id?>', 'comment', '<?=$post->from->id?>','<?=$post->from->name?>')"> Unlike
										<?php }?>
									</a> 
							 	</span>	 
							 </div>
						</li>								
						<?php $count ++;?>
						<?php endforeach; }?>
					</ul>
					</div>
					<div class="comment-container">
						<div class="photo">
							<img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $this->userid?>/picture" onerror="ImgError(this);">
						</div>
						<form action="#" class="submit-form" >
							<textarea class="comment-box" id="comment_box_popup_<?= $this->post->id ?>" ></textarea>
							<input type=button class="btn-submit" value="Comment" onclick="commentSubmit2(this,'<?= $this->post->id ?>','<?= $this->post->type ?>','<?=$this->post->from->id?>','<?=$this->post->from->name?>')">
						</form>																		
					</div>
				</li>
			</ul>	
		</div>
	</div>
</div>

<script>
	$('.comments.popup_scroll').enscroll({
	showOnHover: true,
	clickTrackToScroll: false,
	verticalTrackClass: 'track3 popup',
	verticalHandleClass: 'handle3 popup'
	});
</script>