<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta http-equiv="imagetoolbar" content="no"/>

        <meta http-equiv="Content-Language" content="en"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <meta name="description" content="Fancrank Inc."/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>

        <meta name="author" content="FanCrank" />
        <meta name="generator" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <script src="/js/libs/jquery-1.7.2.min.js"></script>
        <script src="/js/libs/jquery.scrollTo-1.4.2-min.js"></script>
		<script src="/js/libs/jquery-ui-1.8.21.custom.min.js"></script>
    	<script src="/js/libs/modernizr-2.5.3.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script src="//connect.facebook.net/en_US/all.js"></script>

        <script src="/js/fancrankTour.js"></script>
        <script src="/js/fancrank.js"></script>
        <script>
			var appId = "<?= $this->layout()->appKey ?>";
			var serverUrl = "<?= $this->fullServerUrl() ?>";
			window.fbAsyncInit = function() {
				FB.init({
					 appId  : appId,
					 status : true, // check login status
					 cookie : true, // enable cookies to allow the server to access the session
					 xfbml  : true// parse XFBML
				});
				
			
				//FB.Canvas.setSize();
			};
        </script>
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--  <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>-->
        
        <?= $this->adminTheme($this->fanpageTheme, APPLICATION_ENV) ?>
   
    </head>

    <body controller="<?= $this->layout()->controller ?>" action="<?= $this->layout()->action ?>">
        <div class="navbar navbar-fixed-top">
            <?= $this->layout()->navbar ?>
        </div>

        <div class="container" role="main">
                <?= APPLICATION_ENV ?>
                <?= $this->layout()->content ?>
        </div>

        <div id="fb-root"></div>
    </body>
</html>
