<form id="redeem-form" class="form-horizontal">

	<div class="rvrow">
		<div class="rvgrid-11">
			<div class="box"  >
				<div class="post-container" style="min-height:445px; ">
					<div class="page1">
						<div class="title nopic">
							<div class="title-header nopic">
								Please Select an Item
								<button type="button" id='next_page' class="btn fc-comment" style="float:right; margin-top:-9px; z-index:2">Next</button>
							</div>
							
						</div>
						<div class="post">
							<input type="hidden" name="redeemItemId" id="redeemItemId"/>
							
							<table class="table" id="redeemItemTable">
								<thead>
									<tr>
										<th style="width:25px">Selected Items</th>
										<th></th>
										<th>Name</th>
										<th>Description</th>
									</tr>
								</thead>
								<tbody>
								<?php foreach($this->itemList as $item): ?>
									<tr>
										<td><input data-item-id="<?= $item['id']?>" type="checkbox" /></td>		
										<td><img src='/img/item/<?= $item['picture']?>' width="40px" /></td>	
										<td><?= $item['name']?></td>
										<td><?= $item['description']?></td>		
																
									</tr>
								<?php endforeach; ?>
								</tbody>
							</table>
						</div>
				
					</div>
					<div class="page2"  style="display:none; margin-bottom:50px;">
						<div class="title nopic">
							
							<div class="title-header nopic">
								Shipping Info
								<button type="button" id="last_page" class="btn fc-comment" style="float:right; margin-top:-9px; z-index:2">Back</button>
							</div>
							
						</div>
						<div class="post">
							<div class="control-group">
								<label class="control-label" for="contactName">Contact Name</label>
								<div class="controls">
									<input type="text" name="contactName" id="contactName" value="<?=$this->shippingInfo['name']?>" />
								</div>
							</div>			
							<div class="control-group">
								<label class="control-label" for="address">Street Address</label>
								<div class="controls">
									<input type="text" name="address" id="address" value="<?=$this->shippingInfo['address']?>" />
								</div>
							</div>	
							<div class="control-group">
								<label class="control-label" for="city">City</label>
								<div class="controls">
									<input type="text" name="city" id="city" value="<?=$this->shippingInfo['city']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="region">State/Province</label>
								<div class="controls">
									<input type="text" name="region" id="region" value="<?=$this->shippingInfo['region']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="country">Country</label>
								<div class="controls">
									<input type="text" name="country" id="country" value="<?=$this->shippingInfo['country']?>" />
								</div>
							</div>		
							<div class="control-group">
								<label class="control-label" for="postCode">Zip/Postal Code</label>
								<div class="controls">
									<input type="text" name="postcode" id="postcode" value="<?=$this->shippingInfo['postcode']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="trackingEmail">Email</label>
								<div class="controls">
									<input type="text" name="trackingEmail" id="trackingEmail" value="<?=$this->shippingInfo['email']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="confirmEmail">Confirm Email</label>
								<div class="controls">
									<input type="text" name="confirmEmail" id="confirmEmail" />
								</div>
							</div>						
							
							<div style="float:right">
								<button id="redeem_submit" type="submit" class="btn fc-share" >Confirm</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>

</form>

<script>
	$(document).ready(function() {
		initFormValidate();
		$('#redeemItemTable  input[type=checkbox]').live('click', function() {
			$('#redeemItemTable  input[type=checkbox]').removeAttr('checked');
			$(this).attr('checked', true);
			$('#redeemItemId').val($(this).attr('data-item-id'));
		});

		//var addresspicker = $( "#address" ).addresspicker();
		
		$('#next_page').live('click',function(){
			$('.page1').css('display','none');

			$('.page2').css('display','block');
			
		});
		
		$('#last_page').live('click',function(){
			$('.page2').css('display','none');

			$('.page1').css('display','block');
		});
		
	});

	function initFormValidate() {

		$('#redeem-form').validate({
			rules: {
				//About yourself section
				contactName: {
					required: true,
					minlength: 2,
					maxlength: 100
				},
				trackingEmail: {
					required: true,
					email: true
				},
				confirmEmail:{
					required: true,
					equalTo: '#trackingEmail'
				},
				address: {
					required: true,
					minlength: 2,
					maxlength: 100
				},
				city: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				region: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				country: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				postcode: {
					required: true,
					minlength: 2,
					maxlength: 15					
				}
			},	
			focusInvalid: true,
			focusCleanup: true,
			onkeyup: false
		});
		
	}
		
</script>