<form id="update-shipping-form" class="form-horizontal">

	<div class="rvrow">
		<div class="rvgrid-11">
			<div class="box"  >
				<div class="post-container" style="min-height:445px; ">
					<div class="page1">
						<div class="title nopic">
							
							<div class="title-header nopic">
								Shipping Info
							</div>
							
						</div>
						<div class="post">
							<div class="control-group">
								<label class="control-label" for="contactName">Contact Name</label>
								<div class="controls">
									<input type="text" name="contactName" id="contactName" value="<?=$this->shippingInfo['name']?>" />
								</div>
							</div>			
							<div class="control-group">
								<label class="control-label" for="address">Street Address</label>
								<div class="controls">
									<input type="text" name="address" id="address" value="<?=$this->shippingInfo['address']?>" />
								</div>
							</div>	
							<div class="control-group">
								<label class="control-label" for="city">City</label>
								<div class="controls">
									<input type="text" name="city" id="city" value="<?=$this->shippingInfo['city']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="region">State/Province</label>
								<div class="controls">
									<input type="text" name="region" id="region" value="<?=$this->shippingInfo['region']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="country">Country</label>
								<div class="controls">
									<input type="text" name="country" id="country" value="<?=$this->shippingInfo['country']?>" />
								</div>
							</div>		
							<div class="control-group">
								<label class="control-label" for="postCode">Zip/Postal Code</label>
								<div class="controls">
									<input type="text" name="postcode" id="postcode" value="<?=$this->shippingInfo['postcode']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="trackingEmail">Email</label>
								<div class="controls">
									<input type="text" name="trackingEmail" id="trackingEmail" value="<?=$this->shippingInfo['email']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="confirmEmail">Confirm Email</label>
								<div class="controls">
									<input type="text" name="confirmEmail" id="confirmEmail" />
								</div>
							</div>						
							
							<div style="float:right">
							<button id="updateShippingConfirm" name="updateShippingConfirm" type="submit" class="btn fc-share" value="ok">Confirm</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>

</form>

<script>
	$(document).ready(function() {
		initUpdateFormValidate();
		//var addresspicker = $( "#address" ).addresspicker();
	});

	function initUpdateFormValidate() {

		$('#update-shipping-form').validate({
			rules: {
				//About yourself section
				contactName: {
					required: true,
					minlength: 2,
					maxlength: 100
				},
				trackingEmail: {
					required: true,
					email: true
				},
				confirmEmail:{
					required: true,
					equalTo: '#trackingEmail'
				},
				address: {
					required: true,
					minlength: 2,
					maxlength: 100
				},
				city: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				region: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				country: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				postcode: {
					required: true,
					minlength: 2,
					maxlength: 15					
				}
			},	
			focusInvalid: true,
			focusCleanup: true,
			onkeyup: false
		});
		
	}
		
</script>