<form id="update-shipping-form" class="form-horizontal">

	<div class="rvrow">
		<div class="rvgrid-11">
			<div class="box"  >
				<div class="post-container" style="min-height:445px; ">
					<div class="page1">
						<div class="title nopic">
							<div class="title-header nopic">
								Order Status
								<button type="button" id='next_page' class="btn fc-comment" style="float:right; margin-top:-9px; z-index:2">Update Shipping Information</button>
						
							</div>
							
						</div>
						<div class="post">
										
							<table class="table" id="redeemItemTable">
								<thead>
									<tr>
										<th style="width:10px">Items</th>
										<th></th>
										<th>Name</th>
										<th>Description</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?= $this->item['item_id']?></td>		
										<td><img src='/img/item/<?= $this->item['picture']?>' width="40px" /></td>	
										<td><?= $this->item['name']?></td>
										<td><?= $this->item['description']?></td>		
										<td><? switch ($this->item['status']) {
											case '0': echo 'Disapproved';
											break;
											case '1' : echo 'Redeemed, Waiting for Approval';
											break;
											case '2' : echo 'Approved';
											break;
											case '3' : echo 'Shipped';
											break;
										
											}?></td>		
									</tr>
								</tbody>
							</table>
							
						</div>
				
					</div>
				
				
				
					<div class="page2"  style="display:none; margin-bottom:50px;">
						<div class="title nopic">
							
							<div class="title-header nopic">
								Shipping Info
								<button type="button" id="last_page" class="btn fc-comment" style="float:right; margin-top:-9px; z-index:2">Back</button>
							</div>
							
						</div>
						<div class="post">
							<div class="control-group">
								<label class="control-label" for="contactName">Contact Name</label>
								<div class="controls">
									<input type="text" name="contactName" id="contactName" value="<?=$this->shippingInfo['name']?>" />
								</div>
							</div>			
							<div class="control-group">
								<label class="control-label" for="address">Street Address</label>
								<div class="controls">
									<input type="text" name="address" id="address" value="<?=$this->shippingInfo['address']?>" />
								</div>
							</div>	
							<div class="control-group">
								<label class="control-label" for="city">City</label>
								<div class="controls">
									<input type="text" name="city" id="city" value="<?=$this->shippingInfo['city']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="region">State/Province</label>
								<div class="controls">
									<input type="text" name="region" id="region" value="<?=$this->shippingInfo['region']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="country">Country</label>
								<div class="controls">
									<input type="text" name="country" id="country" value="<?=$this->shippingInfo['country']?>" />
								</div>
							</div>		
							<div class="control-group">
								<label class="control-label" for="postCode">Zip/Postal Code</label>
								<div class="controls">
									<input type="text" name="postcode" id="postcode" value="<?=$this->shippingInfo['postcode']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="trackingEmail">Email</label>
								<div class="controls">
									<input type="text" name="trackingEmail" id="trackingEmail" value="<?=$this->shippingInfo['email']?>" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="confirmEmail">Confirm Email</label>
								<div class="controls">
									<input type="text" name="confirmEmail" id="confirmEmail" />
								</div>
							</div>						
							
							<div style="float:right">
							<button id="updateShippingConfirm" name="updateShippingConfirm" type="submit" class="btn fc-share" value="ok">Confirm</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>

</form>

<script>
	$(document).ready(function() {
		initUpdateFormValidate();
		//var addresspicker = $( "#address" ).addresspicker();
	});
	$('#next_page').live('click',function(){
		$('.page1').css('display','none');

		$('.page2').css('display','block');
		
	});
	$('#last_page').live('click',function(){
		$('.page2').css('display','none');

		$('.page1').css('display','block');
	});
	function initUpdateFormValidate() {

		$('#update-shipping-form').validate({
			rules: {
				//About yourself section
				contactName: {
					required: true,
					minlength: 2,
					maxlength: 100
				},
				trackingEmail: {
					required: true,
					email: true
				},
				confirmEmail:{
					required: true,
					equalTo: '#trackingEmail'
				},
				address: {
					required: true,
					minlength: 2,
					maxlength: 100
				},
				city: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				region: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				country: {
					required: true,
					minlength: 2,
					maxlength: 45
				},
				postcode: {
					required: true,
					minlength: 2,
					maxlength: 15					
				}
			},	
			focusInvalid: true,
			focusCleanup: true,
			onkeyup: false
		});
		
	}
		
</script>