<div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

        <a class="brand" href="/admin/dashboard"><img src="/img/logo.png"></a>
        <ul class="nav pull-right">
            <li><a href="/admin/dashboard/fanpages">My Pages</a></li>
            <li><a href="/admin/dashboard/myaccount">My Account</a></li>
            <li><a href="/admin/dashboard/logout">Log out</a></li>
   				<?php if ( $this->layout()->action === 'fanpages' ): ?>
					<li><a id="fancrankTour" href="#"><i class="icon-flag"></i> Help</a></li>
				<?php endif; ?>
        </ul>
    </div>
</div>