<!-- logged out nav bar -->
muhahahhahaha this isn't being used. it won't run.
<div class="adminTopNavbar navbar-inner">
    <div class="container">
        <a class="brand" href="/dashboard"><img src="/img/logo.png"></a>
        <ul class="nav pull-right">
        </ul>

        <div class="nav-collapse pull-right">
            <!-- .nav, .navbar-search, .navbar-form, etc -->
        </div>
    </div>
</div>