<div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

        <a class="brand" href="/dashboard"><img src="/img/logo.png"></a>
        <ul class="nav pull-right">
            <li><a href="/dashboard/myaccount">My Account</a></li>
            <li><a href="/dashboard/fanpages">Fan Pages</a></li>
            <li><a href="/dashboard/logout">Log out</a></li>
        </ul>

        <div class="nav-collapse">
            <ul class="nav">
                <li><a href="/dashboard/myaccount">My Account</a></li>
                <li><a href="/dashboard/fanpages">Fan Pages</a></li>
                <li><a href="/dashboard/logout">Log out</a></li>
            </ul>
        </div>
    </div>
</div>