<!--  THIS LAYOUT IS FOR THE MULTIPLE PAGES-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta http-equiv="imagetoolbar" content="no"/>

        <meta http-equiv="Content-Language" content="en"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <meta name="description" content="Fancrank Inc."/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>

        <meta name="author" content="FanCrank" />
        <meta name="generator" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <script src="/js/libs/jquery-1.7.2.min.js"></script>
		<script src="/js/libs/jquery-ui-1.8.21.custom.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    	<script src="/js/libs/modernizr-2.5.3.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script src="//connect.facebook.net/en_US/all.js"></script>
        
	    <!-- This following javascripts are used to initialize the iframe look and feel -->
		<script>
			var baseAppUrl = "<?= $this->url() ?>";
			var appId = "<?= $this->layout()->appKey ?>";
			var userId = "<?= $this->facebook_user->facebook_user_id ?>";
			var accessToken = "<?= $this->access_token ?>";
			var fanpageId = "<?= $this->fanpage_id?>"	;	
			
			window.fbAsyncInit = function() {
				FB.init({
					 appId  : appId,
					 status : true, // check login status
					 cookie : true, // enable cookies to allow the server to access the session
					 xfbml  : true// parse XFBML
				});
				FB.Canvas.setAutoResize(10);
			
				//FB.Canvas.setSize();
			};
		 </script>
	 	<!-- End of iframe initialization -->
        <script src="/js/fancrank.js"></script>
        <script src="/js/app/index/login.js"></script>

        <?= $this->headScript(); ?>

        <? if (APPLICATION_ENV == 'development'): ?>
			
			<?php if ($this->color_choice == 1) {?>
            <link href="/css/loadstyle1.less" rel="stylesheet/less" id="stylesheet"/>
            <?}elseif($this->color_choice == 2){?>
             <link href="/css/loadstyle2.less" rel="stylesheet/less" id="stylesheet"/>
               <?}elseif($this->color_choice == 4){?>
             <link href="/css/loadstyle4.less" rel="stylesheet/less" id="stylesheet"/>
               <?}elseif($this->color_choice == 5){?>
             <link href="/css/loadstyle5.less" rel="stylesheet/less" id="stylesheet"/>
            <? } else {?>
            <link href="/css/loadstyle3.less" rel="stylesheet/less" id="stylesheet"/>
            
            <? }?>
            <script type="text/javascript">
                env = 'development';

                less = {};
                less.env = 'development';

            </script>
            <script src="/js/libs/less-1.3.0.min.js"></script>
        <? else: ?>
             <link href="/css/style.css" rel="stylesheet" type="text/css"/>
        <? endif ?>

      
        <style>
            .container, .navbar-fixed-top .container {
                width: 810px;
            }
        </style>
       
    </head>

    <body style="overflow:auto;" controller="<?= $this->layout()->controller ?>" action="<?= $this->layout()->action ?>" module="app">

    	<!-- 
        <div class="navbar navbar-fixed-top">
            <?= $this->layout()->navbar ?>
        </div>
		-->

		<div class="container" role="main"> 
			<div id="wrapper">
	
				<div id="header">
			    
			    	<div id="logo"></div>
			        
			    </div><!--/end header -->
			    
			    <div id="content">
			    
			    <a href="#" onclick="colorChange(1)">Grayscale</a>
			    <a href="#" onclick="colorChange(2)">Bubblegum</a>
			    <a href="#" onclick="colorChange(3)">Original</a>
			     <a href="#" onclick="colorChange(4)">Autumn</a>
			     <a href="#" onclick="colorChange(5)">Ocean</a>
				<div class="user-profile">
								
	        					<div class="top-border"> <a class="closeProfile" href="#" onclick="closeProfile()"></a> </div>
	        					<div class="bottom-border"> </div>
	        					<div class="profile-content">
	        						
	        					
	        					
	        					</div>
	        	</div>
			    	<div class="container">
			    	module version
			    		
						<div class="tabbable">   
						    <ul class="nav nav-tabs" id="pageTabs">
								<li class="active" ><a href="#news-feed" data-toggle="tab" id="newsfeed-tab" >News Feed</a></li>
								<li><a href="#top-fans" data-toggle="tab"  id="topfans-tab">Top Fans</a></li>
								<li><a href="#profile" data-toggle="tab"  id="profile-tab">My Profile</a></li>
								<li><a href="#achievements" data-toggle="tab"  id="achievements-tab">Achievements</a></li>
							</ul>
							
				    		<div class="tab-content">
				    				<div class="tab-pane active" id="news-feed">
	        							<?= $this->layout()->content ?>
	        						</div>
	        						<div class="tab-pane" id="top-fans">
	        						</div>
	        						<div class="tab-pane" id="profile">
	        						</div>
	        						<div class="tab-pane" id="achievements">
	        						</div>
	        						
	        				</div>
	        				
	        			</div>
	        			
	        		</div>
        	
        		</div>
        	</div>
         </div>
         <div class="light-box"></div>
        <div id="fb-root"></div>
    </body>
    <script>

$tfb = false;
$ffb = false;
$ttb = false;
$tcb = false;

	$('#top-fans-btn').live('click', function() {
		
		if (($tfb)==true){
		$('#top-fans-btn').text('- Close');
		}else{
			$('#top-fans-btn').text("+ More");
		}
		$tfb = !$tfb;
	})
	
	$('#fan-favorite-btn').live( 'click', function() {
		if (($ffb)==true){
		$('#fan-favorite-btn').text('- Close');
		}else{
			$('#fan-favorite-btn').text("+ More");
		}
		$ffb = !$ffb;
	})
	
	$('#top-talker-btn').live( 'click', function() {
		if (($ttb)==true){
		$('#top-talker-btn').text('- Close');
		}else{
			$('#top-talker-btn').text("+ More");
		}
		$ttb = !$ttb;
	})
	
	$('#top-clicker-btn').live( 'click', function() {
		if (($tcb)==true){
		$('#top-clicker-btn').text('- Close');
		}else{
			$('#top-clicker-btn').text("+ More");
		}
		$tcb = !$tcb;
	})


    
    function closeProfile(){
    	$('.light-box').css('display','none');
		$('.user-profile').css('display', 'none');
		//$('.top-border').css('top','350px');
		//$('.bottom-border').css('top','350px');
		$('.profile-content').css('top','350px');
		//$('.top-border').css('display','none');
		//$('.bottom-border').css('display','none');
		$('.profile-content').css('display','none');
		$('.profile-content').css('height','660px');

		if($('#top-fans').hasClass('active')){
			getTopfans('#top-fans');
			//alert("top class reload");
		}
    	$('.profile-content').html('');
    	$('#moreComment').removeAttr('postid');
    	
		
    }
    
	$('.light-box').click(function(){
		closeProfile();
	});

	$('#newsfeed-tab').click(function(){
		getNewsfeed('#news-feed');
		$('#top-fans').html('');
		$('#profile').html('');
		$('#achievements').html('');
		 getFancrankfeed('all');
	});
	
	$('#topfans-tab').click(function(){
		getTopfans('#top-fans');
		$('#profile').html('');
		$('#achievements').html('');
		$('#newsfeed').html('');
	});
    
	$('#profile-tab').click(function(){
	
		 getMyProfile('#profile');
		 $('#top-fans').html('');
		 $('#achievements').html('');
		 $('#newsfeed').html('');
	});

	$('#achievements-tab').click(function(){
		getAwards('#achievements') 
		$('#top-fans').html('');
		$('#profile').html('');
		$('#newsfeed').html('');
		
	});
	
	
	
	function userProfile(user){
		getUserProfile('.profile-content', user);
		setTimeout(function() {
		$('.light-box').css('display','block');
		$('.user-profile').css('display', 'block');
			/*
		$('.top-border').animate({
		    height: 'toggle',
			top: '0px'
		  }, 1000, function() {
		    // Animation complete.
		  });
	
		$('.bottom-border').animate({
		    height: 'toggle',
		    top: '0px'
		  }, 1000, function() {
		    // Animation complete.
		  });
		  */
		
		
		  
		$('.profile-content').animate({
			height:'toggle',
			top:'20px'
		   },1500, function(){
			   
		});
		},500);
	}

	function comment(post_id, target, limiter){
		
		getComment('.profile-content', post_id, target, limiter);
		$('.light-box').css('display','block');
		$('.user-profile').css('display', 'block');
	
		/*$('.top-border').animate({
		    height: 'toggle',
			top: '0px'
		  }, 1000, function() {
		    // Animation complete.
		  });
	
		$('.bottom-border').animate({
		    height: 'toggle',
		    top: '0px'
		  }, 1000, function() {
		    // Animation complete.
		  });*/
			$('.profile-content').css('height', 'auto');
		//$('.profile-content').css('height', '1100px');
		$('.profile-content').animate({
			height:'toggle',
			top:'20px'
		   },1000, function(){
			   
		});

		
		
	}
	
	 $(document).ready(function() {
		 FB.api(fanpageId , function(response){
			 if (!response || response.error) {
			 	
		 	 }else{
			 	 	try{
			 	 	var x = -1*(parseInt(response.cover.offset_y) + 50);
			 	 	}catch(err){
					var x = 0;
			 	 	}
			 	 	//alert(x);
			 		$('#logo').html('<img src =" ' + response.cover.source + '"style=" top:'+ x +'px" />' );
			 		
			 }



		 
	 	});

		 getFancrankfeed('all');
		 
	 });

	 
  /*  $(document).ready(function() {

    	var tabs = $( "#pageTabs" ).tabs({
    		load: function(event, ui) {
    			$(ui.panel).delegate('a', 'click', function(event) {
    					$(ui.panel).load(this.href);
    					event.preventDefault();
    				});
    			}
    		});

   
	$(document).ready(function() {		
    		$('#pageTabs').bind('tabsselect', function(event, ui) {
    			$('#pageTabs a').removeAttr('id');
    			$(ui.tab).attr('id', 'currentPageTab').css({'outline': 'none'});
    			
    			//var url = $.data(ui.tab, 'load.tabs');
    			
    		});
    	});*/

	
	function getUserProfile(ui, target) {
		$.ajax({
			type: "GET",
			url: baseAppUrl+'/userprofile?fanpage_id='+ fanpageId + '&target=' + target + '&facebook_user_id='+ userId,
			dataType: "html",
			cache: false,
			success: function( data ) {
		
				$(ui).html(data);
			},	
			error: function( xhr, errorMessage, thrownErro ) {
				console.log(xhr.statusText, errorMessage);
			}
		});
	}
	
	function getComment(ui, post_id, target, limiter) {
		      
		$.ajax({
			type: "GET",
			url: baseAppUrl+'/comment' ,
			dataType: "html",
			cache: false,
			success: function( data ) {
				$(ui).html(data);
				
				 FB.api(post_id ,{ limit: 1 },  function(response){
			    	   if (!response || response.error) {
			    		    //alert('Error occured');
			    		  } else {
			    		    //alert(response.from.id);
				    		
			    			$('#post_img').html("<img id='post_img' class='face' width='30' height='30' src='https://graph.facebook.com/" + response.from.id + "/picture' />");
			    			$('#post_message').html('<div class="name"><a href="">' + response.from.name + '</a></div>' + response.message);
								
							var like;
							try {
								like = response.likes.count;
								
							}catch(err){
								like=0;
							}
							
							$('#post_like').html(like);
							
							var d = new Date(Date.parse(response.created_time));
							//alert(d);
							$('#post_date').html(d.toDateString());	
							var limit = response.comments.data.length;
						//	alert(limit);
							if(limiter < limit){
								limit = limiter;
							}
							//alert(limit);
							//alert(limiter);
							for (i=0;i<limit; i++){	
								//alert(i);
								d = new Date(Date.parse(response.comments.data[i].created_time));
								//alert(d);
								//alert(html);
								$('#post-list').append(
									'<li class="grey-light"><div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/' 
									+ response.comments.data[i].from.id+ '/picture"></a></div><div class="post"><div class="name"><a href="">' 
									+ response.comments.data[i].from.name + '</a></div>' + response.comments.data[i].message + 
									'</div><div class="social">' + '<a href="#" class="likes">Like</a>  Posted on <span class="date"> '
									+ d.toDateString() + '</span></div></li><br/>' 
									);			
							}

							if (limiter < response.comments.data.length){
								$('#moreComments').html('More +');
								$('#moreComments').attr('postid', post_id );
								$('#moreComments').attr('loaded', 5);
							}
			    		  }
			 	});
			},	
			error: function( xhr, errorMessage, thrownErro ) {
				console.log(xhr.statusText, errorMessage);
			}
		});
	}


	$('#moreComments').live('hover',function(){
		FB.api( $('#moreComments').attr('postid')+'/comments?limit=10&offset=' + $('#moreComments').attr('loaded') ,  function(response){
	    	   if (!response || response.error) {
	    		    alert('Error occured');
	    		  } else {
	    		    //alert(response.from.id);
		    		
	    			var limiter=10;
					var limit = response.data.length;
				//	alert(limit);
					if(limiter < limit){
						limit = limiter;
					}
					//alert(limit);
					//alert(limiter);
					for (i=0;i<limit; i++){	
						//alert(i);
						d = new Date(Date.parse(response.data[i].created_time));
						//alert(d);
						//alert(html);
						$('#post-list').append(
							'<li class="grey-light"><div class="photo"><a href=""><img class="face" width="30" height="30" src="https://graph.facebook.com/' 
							+ response.data[i].from.id+ '/picture"></a></div><div class="post"><div class="name"><a href="">' 
							+ response.data[i].from.name + '</a></div>' + response.data[i].message + 
							'</div><div class="social">' + '<a href="#" class="likes">Like</a>  Posted on <span class="date"> '
							+ d.toDateString() + '</span></div></li><br/>' 
							);			
					}

					var x = parseInt($('#moreComments').attr('loaded')) + 10;
					$('#moreComment').removeAttr('loaded');
					$('#moreComments').attr('loaded', x );
					//alert(response.data.length);
					//alert(limiter);
					if (limiter < response.data.length){
						$('#moreComments').html('More +');
						$('#moreComments').attr('postid', post_id );						
					}else{
						$('#moreComments').html('');
					}
	    		  }
	 	});
	});	
	
	
	function getNewsfeed(ui) {
		$.ajax({
			type: "GET",
			url: baseAppUrl+'/newsfeed?fanpage_id='+ fanpageId + '&facebook_user_id=' + userId,
			dataType: "html",
			cache: false,
			success: function( data ) {
				$(ui).html(data);
			},	
			error: function( xhr, errorMessage, thrownErro ) {
				console.log(xhr.statusText, errorMessage);
			}
		});
	}

	function getFancrankfeed(view){
		ui = '#fancrankfeed';
		//alert(baseAppUrl+'/fancrankfeed?fanpage_id='+ fanpageId + '&facebook_user_id=' + userId + '&access_token=' +accessToken + '&viewAs=' +view);
		$.ajax({
			type: "GET",
			url: baseAppUrl+'/fancrankfeed?fanpage_id='+ fanpageId + '&facebook_user_id=' + userId + '&access_token=' +accessToken + '&viewAs=' +view, 
			dataType: "html",
			cache: false,
			success: function( data ) {
				$(ui).html('');
				$(ui).html(data);
			},	
			error: function( xhr, errorMessage, thrownErro ) {
				console.log(xhr.statusText, errorMessage);
			}
		});
	}
	
    function getTopfans(ui) {
     
    	$.ajax({
    		type: "GET",
    		url: baseAppUrl+'/topfans?fanpage_id='+ fanpageId + '&facebook_user_id=' + userId,
    		dataType: "html",
    		cache: false,
    		success: function( data ) {
    			$(ui).html(data);
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
        		alert(url);
    			console.log(xhr.statusText, errorMessage);
    			
    		}
    	});
    }
    
    function getMyProfile(ui) {
    	$.ajax({
    		type: "GET",
    		url: baseAppUrl+'/myprofile?fanpage_id='+ fanpageId + '&facebook_user_id=' + userId,
    		dataType: "html",
    		cache: false,
    		success: function( data ) {
    			$(ui).html(data);
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
    }

	
    
    function getAwards(ui) {
    	$.ajax({
    		type: "GET",
    		url: baseAppUrl+'/awards?fanpage_id='+ fanpageId + '&facebook_user_id=' + userId,
    		dataType: "html",
    		cache: false,
    		success: function( data ) {
    			$(ui).html(data);
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
    }	

	function follow($target){
		$.ajax({
    		type: "GET",
    		url: '/app/user/'+ userId + '/follow/?subscribe_to=' + $target + '&facebook_user_id=' + userId + '&fanpage_id='+ fanpageId + '&subscribe_ref_id=1',
    		dataType: "html",
    		cache: false,
    		success: function( data ) {
				//alert("target followed")
				getUserProfile('.profile-content', $target);
    			//$(ui).html(data);
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
    }	

	function unfollow($target){
		$.ajax({
    		type: "GET",
    		url: '/app/user/'+ userId + '/unfollow/?subscribe_to=' + $target + '&facebook_user_id=' + userId + '&fanpage_id='+ fanpageId + '&subscribe_ref_id=1',
    		dataType: "html",
    		cache: false,
    		success: function( data ) {
				//alert("target unfollowed")
				getUserProfile('.profile-content', $target);
    			//$(ui).html(data);
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
    }	
	function colorChange($choice){
		$.ajax({
    		type: "GET",
    		url: '/app/user/'+ userId + '/color/?choice=' + $choice + '&facebook_user_id=' + userId,
    		dataType: "html",
    		cache: false,
    		success: function( data ) {
    			window.location.reload()
				
    			//$(ui).html(data);
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			console.log(xhr.statusText, errorMessage);
    		}
    	});


	}
	
</script>
    
    
    
    
    <script src="text/javascript">
		window.onload = function() {
			  FB.Canvas.setAutoGrow(91);
			  setTimeout('autoGrowTimer();', 1000); //This is for demonstration
			};
		
		function autoGrowTimer() { //Can be removed.
		  paragraphs_added++; //Increase the count
		  autoGrowDiv = document.getElementById('autoGrow');
		  //autoGrowDiv.innerHTML = autoGrowDiv.innerHTML + "<p>This is making the iframe taller.</p>";
		  //Stop after 50 paragraphs aded
		  if (paragraphs_added > 50) return;
		
		  setTimeout('autoGrowTimer();', 1000);
		}
		
	
	</script>

<script >
	
		
		$('#news-feed a').click(function (e) {
		  e.preventDefault();
		  $(this).tab('show');
		})

		$('#fan-favorite a').click(function (e) {
		  e.preventDefault();
		  $(this).tab('show');
		})
		
		$('#profile a').click(function (e) {
		  e.preventDefault();
		  $(this).tab('show');
		})
		
		$('#achievements a').click(function (e) {
		  e.preventDefault();
		  $(this).tab('show');
		})
</script>	
		
</html>
