<!--  THIS LAYOUT IS FOR THE MULTIPLE PAGES-->
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8" />
		
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta http-equiv="imagetoolbar" content="no" />
		
		<meta http-equiv="Content-Language" content="en" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		
		<meta name="description" content="Fancrank Inc." />
		<meta name="viewport" content="width=device-width,initial-scale=1" />
		
		<meta name="author" content="FanCrank" />
		<meta name="generator" content="" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		
		<script src="/js/libs/jquery-1.7.2.min.js"></script>
		<script src="/js/libs/jquery-ui-1.8.21.custom.min.js"></script>
		<script src="/js/libs/modernizr-2.5.3.min.js"></script>
		<script src="/bootstrap/js/bootstrap.min.js"></script>
		<script src="//connect.facebook.net/en_US/all.js"></script>
		
		<script src="/js/cranker.js"></script>
		<!-- This following javascripts are used to initialize the iframe look and feel -->
		<script>
		
			var baseAppUrl = "<?= $this->url() ?>";
			var serverUrl = "<?= $this->fullServerUrl()?>";
			var appId = "<?= $this->layout()->appKey ?>";
			var userId = "<?= $this->user_id ?>";
			
			var fanpageId = "<?= $this->fanpage_id?>"	;	
			var userName = "<?= $this->username?>";
			var userAccessToken = "<?= $this->facebook_user_access_token?>";
			//alert( accessToken);
			window.fbAsyncInit = function() {
				FB.init({
					 appId  : appId,
					 status : true, // check login status
					 cookie : true, // enable cookies to allow the server to access the session
					 xfbml  : true// parse XFBML
				});

				FB.Canvas.setAutoGrow(91);
			
				//FB.Canvas.setSize();
			};
		 </script>
<!-- End of iframe initialization -->
		

        <?= $this->headScript(); ?>

        <?php $this->selectTheme($this->color_choice, APPLICATION_ENV); ?>
		
		<style>
		.container,.navbar-fixed-top .container {
			width: 810px;
		}
		</style>

	</head>

	<body style="overflow: hidden;"	>

	<div class="container">
		<div id="wrapper">

			<div id="header">

				<div id="logo"></div>

			</div>
			<!--/end header -->

			<div id="content">

				<div id = "like-animation" ></div>
				<div id = "unlike-animation" ></div>
				<div id = "comment-animation"></div>
				<div id = "follow-animation"></div>
				<div id = "unfollow-animation"></div>
				
				
				<div class="user-profile">

					<div class="top-border">
						<a class="closeProfile" href="#" onclick="closeProfile()"></a>
					</div>
					<div class="bottom-border"></div>
					<div class="profile-content"></div>
				</div>
				<div class="container">


					<div class="tabbable">
						<ul class="nav nav-tabs" id="pageTabs">
							<li class="active"><a href="#news-feed" data-toggle="tab"id="newsfeed-tab">News Feed</a></li>
							<li><a href="#leaderboard" data-toggle="tab" id="leaderboard-tab">Leaderboard</a></li>
							<li><a href="#profile" data-toggle="tab" id="profile-tab">My Profile</a></li>
							<li><a href="#achievements" data-toggle="tab"id="achievements-tab">Achievements</a></li>
							<li><a href="#redeem" data-toggle="tab"id="redeem-tab">Redeem</a></li>
						</ul>
						<ul class="nav nav-tabs" id="log-in-out">
							<li><a href="/app/app/logout/<?= $this->fanpage_id ?>">Logout</a></li>
						</ul>
						
						<a href="#" onclick="colorChange(5)">Ocean</a>
					  	<!-- 
						<a href="#" onclick="colorChange(1)">Grayscale</a> 
						<a href="#"	onclick="colorChange(2)">Bubblegum</a> 
						<a href="#"	onclick="colorChange(3)">Original</a>
						<a href="#" onclick="colorChange(4)">Autumn</a> 
						 
						<a href="#" onclick="colorChange(6)">Red</a>
						 -->
						<div class="tab-content">
							
							
									<div class="tab-pane active" id="news-feed"></div>
									<div class="tab-pane" id="leaderboard"></div>
									<div class="tab-pane" id="profile"></div>
									<div class="tab-pane" id="achievements"></div>
									<div class="tab-pane" id="redeem"></div>
								
							
						</div>
						<div id="powered">
							<a href="http://www.fancrank.com" target=_new><img src="/img/fan-footer.jpg" /></a>
						</div>
					</div>

				</div>

			</div>
		</div>
	</div>
	<div class="light-box"></div>

	<div id="fb-root"></div>
</body>


</html>
