<!--  THIS LAYOUT IS FOR THE SINGLE INDEX PAGE-->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta http-equiv="imagetoolbar" content="no"/>

        <meta http-equiv="Content-Language" content="en"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <meta name="description" content="Fancrank Inc."/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>

        <meta name="author" content="FanCrank" />
        <meta name="generator" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <script src="/js/libs/jquery-1.7.2.min.js"></script>
		<script src="/js/libs/jquery-ui-1.8.21.custom.min.js"></script>
		<script src="/js/libs/jquery.flot.min.js"></script>
    	<script src="/js/libs/modernizr-2.5.3.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script src="//connect.facebook.net/en_US/all.js"></script>
        
	    <!-- This following javascripts are used to initialize the iframe look and feel -->
		<script>
			var baseAppUrl = "<?= $this->url() ?>";
			var appId = <?= $this->layout()->appKey ?>;
			var userId = <?= $this->user_id ?>;
			var accessToken = "<?= $this->access_token ?>";
					
			
			window.fbAsyncInit = function() {
				FB.init({
					 appId  : appId,
					 status : true, // check login status
					 cookie : true, // enable cookies to allow the server to access the session
					 xfbml  : true// parse XFBML
				});
				FB.Canvas.setAutoResize(10);
				//FB.Canvas.setSize();
			};
		 </script>
	 	<!-- End of iframe initialization -->
        <script src="/js/fancrank.js"></script>
        <script src="/js/app/index/login.js"></script>

        <?= $this->headScript(); ?>

        <? if (APPLICATION_ENV == 'development'): ?>
			<?php if ($this->color_choice == 1) {?>
            <link href="/css/loadstyle1.less" rel="stylesheet/less" id="stylesheet"/>
            <?}elseif($this->color_choice == 2){?>
             <link href="/css/loadstyle2.less" rel="stylesheet/less" id="stylesheet"/>
            <? } else {?>
            <link href="/css/loadstyle3.less" rel="stylesheet/less" id="stylesheet"/>
            <? }?>
            <script type="text/javascript">
                env = 'development';

                less = {};
                less.env = 'development';

            </script>
            <script src="/js/libs/less-1.3.0.min.js"></script>
        <? else: ?>
             <link href="/css/style.css" rel="stylesheet" type="text/css"/>
        <? endif ?>

      
        <style>
            .container, .navbar-fixed-top .container {
                width: 810px;
            }
        </style>
       
    </head>

    <body style="overflow:auto;" controller="<?= $this->layout()->controller ?>" action="<?= $this->layout()->action ?>" module="app">

    	<!-- 
        <div class="navbar navbar-fixed-top">
            <?= $this->layout()->navbar ?>
        </div>
		-->

		<div class="container" role="main">          
        	<?= $this->layout()->content ?>
        </div>
                
        <div id="fb-root"></div>
    </body>
</html>
