        <!-- temporary styles -->
        <style>
            .ticket {
            	margin: 15px;
                border: 1px solid white;
                display: block;
                padding: 5px;
                margin: 15px;
				background: black;
                color: white;
                height: 150px;
                width: 150px;
            }

            .ticket .num {
                font-size: 50px;
            }
        </style>
        
