<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta http-equiv="imagetoolbar" content="no"/>

        <meta http-equiv="Content-Language" content="en"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <meta name="description" content="Fancrank Inc."/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>

        <meta name="author" content="FanCrank" />
        <meta name="generator" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <script src="/js/libs/jquery-1.8.2.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>

        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
        <!-- temporary styles -->
        <style>
            body {
                margin: 15px;
                background: black;
                color: white;
            }

            .ticket {
                border: 1px solid white;
                display: block;
                padding: 5px;
                margin: 15px;

                height: 150px;
                width: 150px;
            }

            .ticket .num {
                font-size: 50px;
            }
        </style>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="span6">
                    <h1>Fancrank Dashboard</h1>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <?= $this->partial('index/_ticket.phtml', array('title' => 'Fanpages', 'num' => $this->fanpages)) ?>
                </div>
                <div class="span2">
                    <?= $this->partial('index/_ticket.phtml', array('title' => 'Fans', 'num' => $this->fans)) ?>
                </div>
            </div>
            <p class="heading">basick app info </p>
            <div class="app-info"><?php Zend_Debug::dump($this->appInfo);?></div>
            <p class="heading">insight data </p>
            <div class="app-info"><?php Zend_Debug::dump($this->insightData);?></div>
            <p class="heading">admin activities </p>
            <div class="app-info"><?php Zend_Debug::dump($this->adminLog);?></div>
            <p class="heading">fanpage cron log </p>
            <div class="app-info"><?php Zend_Debug::dump($this->cronLog);?></div>
            <p class="heading">point log </p>
            <div class="app-info"><?php Zend_Debug::dump($this->pointLog);?></div>
        </div>
        
        <script>
			$(function(){
				console.log('log begin...');
				jQuery(".app-info").hide();
				//toggle the componenet with class msg_body
				$(".heading").click(function() {
					$(this).next(".app-info").slideToggle(500);
				});
			});
        </script>
    </body>
</html>
