<!doctype html>
<html lang="en" ng-app="fc-internal">
<head>
  <meta charset="utf-8">
  <title>Google Phone Gallery</title>
  <link rel="stylesheet" href="/internal/css/app.css">
  
  <!-- css link -->
  <link rel="stylesheet" type="text/css" href="/internal/css/bootstrap.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/bootstrap-responsive.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/bootmetro.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/bootmetro-tiles.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/bootmetro-charms.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/metro-ui-light.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/icomoon.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/datepicker.css">
   <link rel="stylesheet" type="text/css" href="/internal/css/daterangepicker.css">
  
  
  <script src="/internal/lib/angular/angular.js"></script>
  <script src="/internal/js/app.js"></script>
  <script src="/internal/js/controllers.js"></script>
  <script src="/internal/js/filters.js"></script>
  <script src="/internal/js/services.js"></script>
  <script src="/internal/lib/angular/angular-resource.js"></script>
</head>
<body ng-controller="IndexCtrl">

 <!-- Header
   ================================================== -->
   <header id="nav-bar" class="container-fluid">
      <div class="row-fluid">
         <div class="span8">
            <div id="header-container">
               <a id="backbutton" class="win-backbutton" href="#/home"></a>
               <h5>FanCrank Internal</h5>
               <div class="dropdown">
                  <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#">
                     Start
                     <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                  <li><a href="#">Fanpages</a></li>
                  <li><a href="#">Redeem Items</a></li>
                  <li><a href="#">Graph</a></li>
                  <li><a href="#">Bug Tacking</a></li>
                  <li><a href="#">Feature Request</a></li>
                  <li><a href="#">API</a></li>
                  <li class="divider"></li>
                  <li><a href="#/home">Home</a></li>
               </ul>
            </div>
            </div>
         </div>
         <div id="top-info" class="pull-right">
         <a href="#" class="pull-left">
            <div class="top-info-block">
               <h3>ADMIN</h3>
               <h4>@FanCrank</h4>
            </div>
            <div class="top-info-block">
               <b class="icon-user"></b>
            </div>
         </a>
         <hr class="separator pull-left"/>
         <a id="settings" class="pull-left" href="#">
            <b class="icon-settings"></b>
         </a>
      </div>
   </div>
   </header>
   
   <div id="charms" class="win-ui-dark">

	<div id="theme-charms-section" class="charms-section">
		<div class="charms-header">
			<a href="#" class="close-charms win-command"> <span
				class="win-commandimage win-commandring">&#xe05d;</span>
			</a>
			<h2>Settings</h2>
		</div>

		<div class="row-fluid">
			<div class="span12">

				<form class="">
					<label for="win-theme-select">Change theme:</label> <select
						id="win-theme-select" class="">
						<option value="metro-ui-semilight">WINDOWS 8</option>
						<option value="metro-ui-light">ANDROID</option>
						<option value="metro-ui-dark">IPHONE</option>
					</select>
				</form>

			</div>
		</div>
	</div>
</div>   
   
   <div ng-view></div>

   <script type="text/javascript" src="/internal/lib/jquery-1.8.2.min.js"></script>
   <script type="text/javascript" src="/internal/lib/google-code-prettify/prettify.js"></script>
   <script type="text/javascript" src="/internal/lib/jquery.mousewheel.js"></script>
   <script type="text/javascript" src="/internal/lib/jquery.scrollTo.js"></script>
   <script type="text/javascript" src="/internal/lib/bootstrap.min.js"></script>
   <script type="text/javascript" src="/internal/lib/bootmetro.js"></script>
   <script type="text/javascript" src="/internal/lib/bootmetro-charms.js"></script>
   <script type="text/javascript" src="/internal/lib/holder.js"></script>
   <script type="text/javascript" src="/internal/lib/bootstrap-datepicker.js"></script>
   <script type="text/javascript" src="/internal/lib/daterangepicker.js"></script>
   <script type="text/javascript" src="/internal/js/animate.js"></script>
   <script type="text/javascript" src="/internal/js/init.js"></script>
   
</body>
</html>
