<div class="navbar-inner">
    <div class="container">
        <a class="brand" href="/app/index/index/<?= $this->fanpage_id ?>"><img src="/img/logo.png"></a>
        <ul class="nav pull-right">
        	<li><a href="/app/index/login/<?= $this->fanpage_id ?>">Login</a></li>
        </ul>

        <div class="nav-collapse pull-right">
            <!-- .nav, .navbar-search, .navbar-form, etc -->
        </div>
    </div>
</div>