<style>

.facebook-user-face {
	width: 24px;
	height: 24px;
}

</style>


<div class="row-fluid">
	<div class="span2">
	
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			Admin Post with the most Like
			Admin Post with the most Comment
			Admin Post that rewarded the most points
			All Admin Posts
			All Admin Comments
			All Admin Likes
		</div>

	</div>
	<div class="span10">
		<div class="row-fluid">
			<div class="span12">
				<h2>Admin Posts</h2>
				<?//php Zend_Debug::dump($this->adminPost)?>
				<table class="table" id="adminPostTable">
					<thead>
						<tr>
							
							<th><a>Message</a></th>
							<th><a>Comments</a></th>
							<th><a>Likes</a></th>
							<th><a>Unique Users</a></th>
							<th><a>Total Points Given</a>
							<th><a>Bonus</a>
							<th><a>Created Time</a>
						</tr>
					</thead>
					<tbody>
						<?php foreach($this->adminPost as $post): ?>
							<tr>
							
			
								<td style="word-break:break-word;word-wrap: break-word; width:50%" >
									<a class="post" data-post-id="<?= $post['post_id']?>">
										<?=stripcslashes(preg_replace('/^\'?(.*?(?=\'?$))\'?$/','$1' ,$post['post_message'])); ?>
									</a>
								</td>
								<td><?=$post['post_comments_count']?></td>
								<td><?=$post['post_likes_count']?></td>
								<td><?=$post['unique_user']?></td>
								<td><?=$post['points']?></td>
								<td><?=$post['bonus']?></td>
								<td><?=$post['created_time']?></td>												
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			
			</div>
		
		</div>
		<div class="row-fluid">
			<div class="span12">
				<h2>Admin Comment</h2>
				<?//php Zend_Debug::dump($this->adminPost)?>
				<table class="table" id="adminCommentTable">
					<thead>
						<tr>
							<th><a>Comments</a></th>
							<th><a>Message</a></th>
							<th><a>Original Post Owner</a>
							<th><a>Likes</a></th>
							<th><a>Created Time</a>
						</tr>
					</thead>
					<tbody>
						<?php foreach($this->adminComment as $comment): ?>
							<tr>
								<td style="word-break:break-word;word-wrap: break-word; width:25%" ><?=stripcslashes(preg_replace('/^\'?(.*?(?=\'?$))\'?$/','$1' ,$comment['comment_message'])); ?></td>
								<td style="word-break:break-word;word-wrap: break-word; width:25%" ><?=stripcslashes(preg_replace('/^\'?(.*?(?=\'?$))\'?$/','$1' ,$comment['post_message'])); ?></td>
								<td><a class="username" data-id="<?= $comment['p_facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $comment['p_facebook_user_id']?>/picture'/> 
								<span><?= $comment['fan_first_name'] . ' ' . $comment['fan_last_name']?></span> </a></td>
								<td><?=$comment['comment_likes_count']?></td>
								<td><?=$comment['created_time']?></td>												
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			
			</div>
		
		</div>
	</div>

</div>

