<script>
var fanpageId = <?= $this->page_id ?>;
var postData = <?= $this->post_data ?>;
</script>

<? $this->headScript()->appendFile('/js/libs/jquery.flot.min.js') ?>
<? $this->headScript()->appendFile('/js/admin/dashboard/analytic.js') ?>

<div>
	<ul class="nav pull-left">
          <li><a class="model-btn" href="#myFanpageSettingModel"><i class="icon-home"></i> home</a></li>
          <li><a class="model-btn" href="#myFanpageSettingModel"><i class="icon-cog"></i> page stats</a></li>
          <li><a class="model-btn" href="#myFanpageSettingModel"><i class="icon-cog"></i> top fans</a></li>
	</ul>
</div>

<div class="span12">
	<div class="num">
	    # of fans: <?= $this->fans ?>;    
	</div>
	<div class="num">
	    # of new fans in 24 hours: <?= $this->new_fans ?>;    
	</div>
	<div class="num">
	    Increase: <?= round($this->new_fans / $this->fans, 4) ?> %;    
	</div>			
</div>

<!-- likes graph -->
<div class="analytic-setting btn-group">
	<ul class="nav nav-pills">
		<li></li>
		<li class="dropdown" id="menu1"><a class="dropdown-toggle"
			data-toggle="dropdown" href="#menu1"> Show statistics <b
				class="caret"></b>
		</a>
			<ul class="dropdown-menu">
				<li><a href="#">total likes statistics</a></li>
				<li><a href="#">daily posts statistics</a></li>
				<li><a href="#">daily comments statistics</a></li>
				<li class="divider"></li>
				<li><a href="#">over all</a></li>
			</ul></li>
	</ul>
</div>

<div id="placeholder"></div>

<div style="width:900px;" class="container-fluid">
		<div class="content">
			<div class="row-fluid">
				<div class="span12">
					<div class="box">
						<div class="box-head tabs">
							<h3>Fan dataTables with tabs</h3>
							<ul class='nav nav-tabs'>
								<li class='active'>
									<a href="#basic" data-toggle="tab">Top fan list</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Top talker</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Top advocates</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Top influencer</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">find user</a>
								</li>								
							</ul>
						</div>
						<div class="box-content box-nomargin">
							<div class="tab-content">
									<div class="tab-pane active" id="basic">
										<table class='table table-striped dataTable table-bordered'>
											<thead>
												<tr>
													<th>id</th>
													<th>name</th>
													<th>points</th>
													<th>level</th>
													<th>Total # of posts</th>
													<th>Total # of comments</th>
													<th>Total # of likes</th>
													<th>Total # of likes received</th>
												</tr>
											</thead>
											<tbody>
												<?php foreach($this->topFanList as $fan): ?>
													<tr>
														<td><?=$fan['facebook_user_id']?></td>
														<td><?=$fan['fan_name']?></td>
														<td><?=$fan['fan_points']?></td>
														<td><?=$fan['fan_level']?></td>
														<td><?=$fan['post_count']?></td>
														<td><?=$fan['comment_count']?></td>
														<td><?=$fan['like_count']?></td>
														<td><?=$fan['got_like_count']?></td>														
													</tr>
												<?php endforeach; ?>
										</tbody>
										</table>
									</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
</div>

<div style="width:600px;" class="container-fluid">
	<h3>Top Post By # Of Likes</h3>
	<div class="box-content box-nomargin">
		<div class="tab-content">
				<div class="tab-pane active" id="basic">
					<table class='table table-striped dataTable table-bordered'>
						<thead>
							<tr>
								<th>Facebook User ID</th>
								<th>Message</th>
								<th># of likes</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->topPostByLike as $post): ?>
								<tr>
									<td><?=$post['facebook_user_id']?></td>
									<td><?=$post['post_message']?></td>
									<td><?=$post['post_likes_count']?></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
					</table>
				</div>
		</div>
	</div>
</div>


<div style="width:600px;" class="container-fluid">
	<h3>Top Post By # Of Comments</h3>
	<div class="box-content box-nomargin">
		<div class="tab-content">
				<div class="tab-pane active" id="basic">
					<table class='table table-striped dataTable table-bordered'>
						<thead>
							<tr>
								<th>Facebook User ID</th>
								<th>Message</th>
								<th># of Comments</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->topPostByComment as $post): ?>
								<tr>
									<td><?=$post['facebook_user_id']?></td>
									<td><?=$post['post_message']?></td>
									<td><?=$post['post_comments_count']?></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
					</table>
				</div>
		</div>
	</div>
</div>

<!-- top post bar graph -->    

<div id="postStat"></div>
