<? //$this->headLink()->headLink(array('rel'=>'stylesheet', 'href'=>'/css/dashboard/analytic.css', 'type'=>'text/css')) ?>

<script>
var fanpageId = <?= $this->page_id ?>;
var postData = <?= $this->post_data ?>;
var sexPieData = <?= $this->fansNumberBySex ?>;
</script>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.barnumbers.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.pie.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.dataTables.min.js') ?>
<? $this->headScript()->appendFile('/js/admin/dashboard/analytic.js') ?>


<ul class="breadcrumb">
  <li><a href="#"><i class="icon-home"></i></a> <span class="divider">/</span></li>
  <li class="active">Name of this fanpage</li>
</ul>
<ul class="widget">
<li class="dropdown pendingContainer">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="icon-barcode"></i>
			Pending Orders</a><div class="label label-important"><?=$this->pending_orders_count ?></div>
		<ul class="dropdown-menu pull-right custom custom-dark">
			<li class="custom">
				<div class="title">
					Pending order #1 
				</div>
				<div class="action">
					<div class="btn-group">
						<a class="tip btn btn-mini" href="#" data-original-title="Show order"><i class="icon-search"></i></a>
					</div>
				</div>
			</li>
		</ul>
	</li>
	<li class="dropdown messageContainer">
		<a data-toggle="dropdown" class="dropdown-toggle" href="#">
			<i class="icon-check"></i>
			Fan Points Request</a><div class="label label-info"><?=$this->fan_requests_count?></div>
		<ul class="dropdown-menu pull-right custom custom-dark">
			<li class="custom">
				<div class="title">
					Show fan's request objects
				</div>
				<div class="action">
					<div class="btn-group">
						<a class="tip btn btn-mini" href="#" data-original-title="Show message"><i class="icon-search"></i></a>
					</div>
				</div>
			</li>
		</ul>
	</li>
</ul>


	<div class="row">
		<div class="span2">
			<div class="box">
				<ul class="nav nav-list">
					<li class="active"><a>General</a></li>
					<li>Fan Data</li>
					<li>Fan Data</li>
					<li class="divider"></li>
					<li>Fan Data</li>
					<li>Fan Data</li>
					<li>Fan Data</li>
					<li>Fan Data</li>
					<li>Fan Data</li>
				</ul>
			</div>
		</div>
		<div class="span10">
			<div class="box">
				<div class="box-head tabs">
							<h3>Fan Data By Leaderboards</h3>
							<ul class='nav nav-tabs'>
								<li class='active'>
									<a href="#basic" data-toggle="tab">Top Fans</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Fan Favorites</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Top Talkers</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Top Clicker</a>
								</li>
								<li>
									<a href="#nohead" data-toggle="tab">Top Followed</a>
								</li>
							</ul>
						</div>
						<div class="box-content box-nomargin">
							<div class="tab-content">
									<div class="tab-pane active" id="basic">
										<table  class='table' id="topFanTable">
											<thead>
												<tr>
													<th>ID</th>
													<th>Name</th>
													<th>Points</th>
													<th>Level</th>
													<th><img src="/img/post.png" rel="tooltip" title="Total # of Posts"/></th>
													<th><img src="/img/thumbsup.png" rel="tooltip" title="Total # of Likes"/></th>
													<th><img src="/img/comment.png" rel="tooltip" title="Total # of Comments"/></th>
													<th><img src="/img/rthumbsup.png" rel="tooltip" title="Total # of Recieved Likes"/></th>
													<th><img src="/img/rcomment.png"rel="tooltip" title="Total # of Recieved Comments"/></th>
													
												</tr>
											</thead>
											<tbody>
												<?php foreach($this->topFanList as $fan): ?>
													<tr>
														<td><?=$fan['facebook_user_id']?></td>
														<td><?=$fan['fan_name']?></td>
														<td><?=$fan['fan_points']?></td>
														<td><?=$fan['fan_level']?></td>
														<td><?=$fan['post_count']?></td>
														<td><?=$fan['like_count']?></td>
														<td><?=$fan['comment_count']?></td>
														<td><?=$fan['got_like_count']?></td>
														<td><?=$fan['got_comment_count']?></td>
																												
													</tr>
												<?php endforeach; ?>
										</tbody>
										</table>
									</div>
							</div>
						</div>
			
			
			
			</div>
		</div>
	</div>


<div class="span12">
	<ul class="quickstats">
		<li>
			<div class="small-chart" data-color="6a9d29" data-stroke="345010" data-type="line"><span style="display: none;">5,3,9,6,5,9,7,3,5,10</span><canvas height="32" width="60"></canvas></div>
			<div class="chart-detail">
				<span class="amount green"><?= $this->fans ?></span>
				<span class="description"># of fans: </span>
			</div>
		</li>
		<li>
			<div class="small-chart" data-color="962c2c" data-stroke="651111" data-type="pie"><span style="display: none;">6/10</span><canvas height="32" width="32"></canvas></div>
			<div class="chart-detail">
				<span class="amount"><?= round($this->new_fans * 100 / $this->fans, 4) ?> %</span>
				<span class="description">Increase</span>
			</div>
		</li>
		<li>
			<div class="small-chart" data-color="2c5b96" data-stroke="102c50" data-type="line"><span style="display: none;">521,500,481,429,550,521</span><canvas height="32" width="60"></canvas></div>
			<div class="chart-detail">
				<span class="amount"><?= $this->new_fans ?></span>
				<span class="description"># of new fans in 24 hours:</span>
			</div>
		</li>
	</ul>
</div>
			

<div class="btn-group">
	<ul class="nav nav-pills">
		<li></li>
		<li class="dropdown" id="menu2"><a class="dropdown-toggle"
			data-toggle="dropdown" href="#menu2"> Export <b
				class="caret"></b>
		</a>
			<ul class="dropdown-menu export-dropdown">
				<li><a href="#">Top fans list</a></li>
				<li><a href="#">Top post</a></li>
			</ul></li>
	</ul>
	<span id="loadGif"></span>
</div>

<!-- likes graph -->
<div class="analytic-setting btn-group">
	<ul class="nav nav-pills">
		<li></li>
		<li class="dropdown" id="menu1"><a class="dropdown-toggle"
			data-toggle="dropdown" href="#menu1"> Show statistics <b
				class="caret"></b>
		</a>
			<ul class="dropdown-menu graph-drodown">
				<li><a href="#">total likes statistics</a></li>
				<li><a href="#">daily posts statistics</a></li>
				<li><a href="#">daily comments statistics</a></li>
				<li class="divider"></li>
				<li><a href="#">over all</a></li>
			</ul></li>
	</ul>
</div>

<div id="placeholder"></div>

<div style="width:1000px;" class="container-fluid">
		<div class="content">
			<div class="row-fluid">
				<div class="span12">
					<div class="box">
						
					</div>
				</div>
			</div>
		</div>	
</div>

<div style="width:600px;" class="container-fluid">
	<h3>Top Post By # Of Likes</h3>
	<div class="box-content box-nomargin">
		<div class="tab-content">
				<div class="tab-pane active" id="basic">
					<table id="topPostByLike" class='table table-striped dataTable table-bordered'>
						<thead>
							<tr>
								<th>Facebook User ID</th>
								<th>Message</th>
								<th># of likes</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->topPostByLike as $post): ?>
								<tr>
									<td><?=$post['facebook_user_id']?></td>
									<td><?=$post['post_message']?></td>
									<td><?=$post['post_likes_count']?></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
					</table>
				</div>
		</div>
	</div>
</div>


<div style="width:600px;" class="container-fluid">
	<h3>Top Post By # Of Comments</h3>
	<div class="box-content box-nomargin">
		<div class="tab-content">
				<div class="tab-pane active" id="basic">
					<table id="topPostByComment" class='table table-striped dataTable table-bordered'>
						<thead>
							<tr>
								<th>Facebook User ID</th>
								<th>Message</th>
								<th># of Comments</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->topPostByComment as $post): ?>
								<tr>
									<td><?=$post['facebook_user_id']?></td>
									<td><?=$post['post_message']?></td>
									<td><?=$post['post_comments_count']?></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
					</table>
				</div>
		</div>
	</div>
</div>

<!-- top post bar graph -->    

<div id="postStat"></div>

<div id="sexPieGraph"></div>
<div id="piehover"></div>

<!-- user profile -->
<div class="modal" id="userprofile">
	    <div class="modal-header">
	    <button type="button" class="close model-btn-close" data-dismiss="modal">x</button>
	    <h3>fan profile</h3>
	    </div>
	    <div class="modal-body" id="fan-profile-content">
		</div>
</div>