<script>
var fanpageId = <?= $this->page_id ?>;
</script>

<? $this->headScript()->appendFile('/js/libs/jquery.flot.min.js') ?>
<? $this->headScript()->appendFile('/js/admin/dashboard/analystic.js') ?>

<div class="analystic-setting btn-group">
	<ul class="nav nav-pills">
		<li></li>
		<li class="dropdown" id="menu1"><a class="dropdown-toggle"
			data-toggle="dropdown" href="#menu1"> Show statistics <b
				class="caret"></b>
		</a>
			<ul class="dropdown-menu">
				<li><a href="#">total likes statistics</a></li>
				<li><a href="#">daily posts statistics</a></li>
				<li><a href="#">daily comments statistics</a></li>
				<li class="divider"></li>
				<li><a href="#">over all</a></li>
			</ul></li>
	</ul>
</div>

<div id="placeholder"></div>

