<script>
var fanpageId = <?= $this->page_id ?>;
</script>

<? $this->headScript()->appendFile('/js/libs/jquery.flot.min.js') ?>
<? $this->headScript()->appendFile('/js/admin/dashboard/analystic.js') ?>

<div style="padding: 10px 0;" class="well">
	<ul class="nav nav-list">
          <li><a href="#"><i class="icon-user"></i> search</a></li>
          <li><a class="model-btn" href="#myFanpageSettingModel"><i class="icon-cog"></i> top fan list</a></li>
          <li><a class="model-btn" href="#myFanpageSettingModel"><i class="icon-cog"></i> top like list</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="icon-flag"></i> Help</a></li>
        </ul>
</div>
	
<div class="analystic-setting btn-group">
	<ul class="nav nav-pills">
		<li></li>
		<li class="dropdown" id="menu1"><a class="dropdown-toggle"
			data-toggle="dropdown" href="#menu1"> Show statistics <b
				class="caret"></b>
		</a>
			<ul class="dropdown-menu">
				<li><a href="#">total likes statistics</a></li>
				<li><a href="#">daily posts statistics</a></li>
				<li><a href="#">daily comments statistics</a></li>
				<li class="divider"></li>
				<li><a href="#">over all</a></li>
			</ul></li>
	</ul>
</div>

<div id="placeholder"></div>

