<div class="row-fluid">
	<div class="span3">
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div>
				<span>Total Number of Badges Awarded:</span> 
				<span>X</span>
			</div>
			<div>
				<span>Most Awarded Badge:</span> 
				<span>X</span>
			</div>
			<div>
				<span>Points Awarded from Badges:</span> 
				<span>X</span>
			</div>
			<div>
				<span>Badges Awarded:</span> 
				<span> Today | This Week | This Month</span>
			</div>
		</div>
	</div>
	<div class="span3">
		Most Awarded Badges
	</div>
	<div class="span3">
		Recently Awarded Badges 
	</div>

	<div class="span3">
		User with the most badges
	</div>
	

</div>

<div class = "row-fluid">
	
	<div class="span8">
	
	</div>
</div>