<? $this->headLink()->headLink(array('rel'=>'stylesheet', 'href'=>'/css/dashboard/badgewizard.css', 'type'=>'text/css')) ?>

<script>
var fanpageId = <?= $this->page_id ?>;
</script>

<? $this->headScript()->appendFile('/js/libs/jquery.dataTables.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.form.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.validate.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.form.wizard-min.js') ?>


<div class="content row-fluid">
	<div class="span12">
		<div class="box">
			<div class="box-head">
				<h3>Fancrank Badge Wizard</h3>
			</div>
			<div class="box-content box-nomargin">
				<div id="myModal2" class="modal hide">
				  <div class="modal-header">
				    <button data-dismiss="modal" class="close" type="button">×</button>
				    <h3>Success</h3>
				  </div>
				  <div class="modal-body">
				    <p>Wizard was submit!</p>
				  </div>
				  <div class="modal-footer">
				    <a data-dismiss="modal" class="btn btn-primary" href="#">Ok, thanks!</a>
				  </div>
				</div>
				<form class="form-horizontal bbq wizard ui-formwizard ui-helper-reset ui-widget ui-widget-content ui-corner-all" action="/admin/dashboard/badgewizard/<?= $this->page_id ?>" method="post" novalidate="novalidate" id="badgeForm">
					<div id="step3" class="step ui-formwizard-content ui-helper-reset ui-corner-all" style="display: block;">
						<ul class="steps">
							<li class="active">
								Step 1
								<span>Basic badge information</span>
							</li>
							<li>
								Step 2
								<span>Select assocaite rules</span>
							</li>
							<li>
								Step 3
								<span>Confirm</span>
							</li>
						</ul>
						<div class="control-group success">
							<label class="control-label" for="name">Badge Name: </label>
							<div class="controls">
								<input type="text" class="required ui-wizard-content ui-helper-reset ui-state-default valid" id="name" name="name"><label for="name" generated="true" class="error valid"></label>
							</div>
						</div>
						
						<div class="control-group success">
							<label class="control-label" for="description">Badge Description: </label>
							<div class="controls">
								<input type="text" class="ui-wizard-content ui-helper-reset ui-state-default valid" id="description" name="description"><label for="description" generated="true" class="error valid"></label>
							</div>
						</div>
						
						<div class="control-group success">
							<label class="control-label" for="weight">Giving Reward Points: </label>
							<div class="controls">
								<input type="text" class="required ui-wizard-content ui-helper-reset ui-state-default valid" name="weight"><label for="weight" generated="true" class="error valid"></label>
							</div>
						</div>
					</div>
					<div id="step4" class="step ui-formwizard-content ui-helper-reset ui-corner-all" style="display: none;">
						<ul class="steps">
							<li>
								Step 1
								<span>Basic badge information</span>
							</li>
							<li class="active">
								Step 2
								<span>Select assocaite rules</span>
							</li>
							<li>
								Step 3
								<span>Confirm</span>
							</li>
						</ul>
						<div class="controls">
								<select class="cho chzn-done" id="target" name="target">
									<option value="posts">posts</option>
									<option value="comments">comments</option>
									<option value="likes">likes</option>
									<option value="subscribes">follows</option>
								</select>
								
								<select class="cho chzn-done" id="operator" name="operator">
									<option value="0"> greater than </option>
									<option value="1"> less than </option>
									<option value="2"> equal </option>
								</select>
								
								<input type="text" class="required ui-wizard-content ui-helper-reset ui-state-default valid" id="argument" name="argument"><label for="argument" generated="true" class="error valid"></label>
						</div>
					</div>
					<div id="step8" class="step ui-formwizard-content ui-helper-reset ui-corner-all" style="display: none;">
						<ul class="steps">
							<li>
								Step 1
								<span>Basic badge information</span>
							</li>
							<li>
								Step 2
								<span>Select associate rule</span>
							</li>
							<li class="active">
								Step 3
								<span>Confirm</span>
							</li>
						</ul>
						<h4>Please select a badge image</h4>
						<div class="control-group">
							<div class="box-head">
								<h3>Badge Icon</h3>
							</div>
							<div class="box-content box-nomargin">
								<ul class="badgeIcon">
									<li>
										<a href="#" class="fancy"><img src="/img/badges/admin/badges.png" alt=""></a>
									</li>
								</ul>
							</div>
												
						</div>
					</div>
					<div id="navigation2">
						<div class="form-actions">
							<input type="reset" value="Back" id="back2" class="navigation_button btn btn-danger ui-wizard-content ui-formwizard-button ui-helper-reset ui-state-default ui-state-active">
							<input type="submit" value="Submit" id="next2" class="navigation_button btn btn-primary ui-wizard-content ui-formwizard-button ui-helper-reset ui-state-default ui-state-active">
							<input type="hidden" name="confirm" value="true" />
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span6">
		<div class="box">
			<div class="box-head">
				<h3>Your Custom Badge</h3>
			</div>
		</div>
				<table class="table table-striped table-bordered" id="badgeTable">
					<thead>
						<tr>
							<th>ID</th>
							<th>Badge Name</th>
							<th>Description</th>
							<th>Weight</th>
							<th>Picture</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>