
<? //$this->headLink()->headLink(array('rel'=>'stylesheet', 'href'=>'/css/dashboard/dashboard.css', 'type'=>'text/css')) ?>

<script>


//var postData = <?= $this->post_data ?>;
//var sexPieData = <?= $this->fansNumberBySex ?>;
</script>

<? $this->headScript()->appendFile('/js/libs/jquery.flot.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.time.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.resize.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.barnumbers.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.flot.pie.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.dataTables.min.js') ?>
<? $this->headScript()->appendFile('/js/admin/dashboard/dashboard.js') ?>
<? $url = 'https://www.facebook.com/pages/' . str_replace(' ', '-', $this->fanpage_name) . '/' . $this->page_id;?>

<div class="padding">

	<ul class="breadcrumb">
		<li>
			<a href="/fanpages">
				<i class="icon-home"></i>
			</a> 
			<span class="divider">/</span>
		</li>
		<li class="active">
			<?=$this->fanpage_name?>
		</li>
	</ul>
	
	<div class="row-fluid">
		<div class="span2">
			<div class="box left-sidebar-wrapper">
				<ul class="nav nav-list">
				<li>Your Pages</li>
				<li class="divider"></li>
				<?php foreach($this->pages as $page){ ?>
					<?php
						$url = '/admin/dashboard/dashboard?id='.$page['fanpage_id'];
					?>
					
					<li><a href="<?= $url ?>"><img class="face" width="30" height="30" src="https://graph.facebook.com/<?= $page['fanpage_id'] ?>/picture" onerror="ImgError(this);"><?= $page['fanpage_name'] ?></a></li>
				<?php }?>
					
				</ul>
			</div>
		</div>
		
		
		<div class="span10">
			
				<ul class='nav nav-tabs'>
					<li class='active'>
						<a href="#home" id="home-tab" data-toggle="tab" >Home</a>
					</li>
					<li>
						<a href="#dashboard" id="dashboard-tab"data-toggle="tab" >Dashboard</a>
					</li>
					<li>
						<a href="#themesettings" id="themesettings-tab" data-toggle="tab">Theme Settings</a>
					</li>
					<li>
						<a href="#users" id="users-tab" data-toggle="tab">Users</a>
					</li>
					<li>
						<a href="#badges"  id="badges-tab" data-toggle="tab">Badges</a>
					</li>
					<li>
						<a href="#points" id="points-tab" data-toggle="tab">Points</a>
					</li>
				</ul>
		
		
			<div class="box tab-content">
				<div id="home" class="tab-pane active" >
					<div class="row-fluid">
						<div class="span4">
						<!-- <div class="small-chart">
							 <img height="32" width="60" src="/img/graph/line_chart.png"></div>-->
							<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
								<div>
									<span>Fanpage ID: </span> 
									<span><?= $this->page_id?></span>
								</div>
								<div>
									<span>Fanpage Name: </span> 
									<span><?= $this->fanpage_name?></span>
								</div>
								<div>
									<span>Fancrank Fanpage Level: </span> 
									<span><?= $this->level?></span>
								</div>
								<div>
									<span>Using Fancrank Since: </span> 
									<span>YYYY-MM-DD </span>
								</div>
								<div>
									<span>Last Admin Activity: </span> 
									<span>YYYY-MM-DD </span>
								</div>
								<div>
									<span>Last Data Collection: </span> 
									<span><?= $this->cron_time?> </span>
								</div>
							</div>
							
							<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
								<div>
									<span class="description">Number of Page Likes: </span>
									<span class="amount"><?= $this->likes ?></span>
								</div>
								
								<div>
									<span class="description">Number of Fans: </span>
									<span class="amount"><?= $this->fans ?></span>
								</div>
								<div>
									<span class="description">Overall User Participation </span>
									<span class="amount"><?= round($this->fans *100/$this->likes, 4) ?> %</span>
								</div>
								<div>
									<span class="description">Number of New Fans in the last 24 Hours:</span>
										<span class="amount"><?= $this->new_fans ?></span>
								</div>
								<div>
									<span class="description">Increase Percentage: </span>
									<span class="amount"><?= round($this->new_fans * 100 / $this->fans, 4) ?> %</span>
								</div>
								<div>
									<span class="description">Number of New FanCrank Users this Week:</span>
									<span class="amount"><?= $this->new_fancrank_users?></span>
								</div>
								<div>
									
									<span class="description">Number of Fans that Participated this Week:</span>
									<span class="amount"><?= $this->new_interaction_users?></span>
								</div>
								<div>
									<span class="description">Number of Interactions:</span>
									<span class="amount"><?= $this->new_interaction?></span>
								</div>
								
								<div>
									<span class="description">Number of Fans that Participated this Week via FanCrank:</span>
									<span class="amount"><?= $this->fancrank_interaction_users?></span>
								</div>
								<div>
									<span class="description">Number of Interactions via FanCrank:</span>
									<span class="amount"><?= $this->fancrank_interaction?></span>
								</div>
								
								
								
								<div >
									
									<span class="description"># of points awarded:</span>
									<span class="amount"></span>
									<br/>
									Today - <?= ($this->points[2]['points'] != null)?$this->points[2]['points']:0 ?> | This Week - <?= ($this->points[1]['points'] != null)?$this->points[1]['points']:0?> | Month - <?= ($this->points[0]['points'] != null)?$this->points[0]['points']:0?>
								</div>
							</div>
						
							
						</div>
						
						<div class="span8">
							<div id="placeholder"></div>
							<div id="placeholder2"></div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
				
							<table class="table" id="topPostByLike">
								<thead>
									<tr>
										<th><a>Fan</a></th>
										<th><a>Message</a></th>
										<th><a>Number of Interactions</a></th>
									</tr>
								</thead>
								<tbody>
									<?php foreach($this->topPostByLike as $post): ?>
										<tr>
											<td style="width:20%"><?=$post['fan_name']?></td>
											<td style="width:70%"><?=$this->escape($post['message'])?></td>
											<td style="width:10%"><?=$post['total_interactions']?></td>
										</tr>
									<?php endforeach; ?>
							</tbody>
							</table>

						</div>
						<div class="span6">
							<table class="table" id="topfanTable">
								<thead>
									<tr>
										
										<th><a>Name</a></th>
										<th><a>EXP</a></th>
										<th><a >Level</a></th>
										<th><a rel="tooltip"  data-original-title="Total # of Posts" data-placement="top"><img src="/img/post.png" /></a></th>
										<th><a rel="tooltip"  data-original-title="Total # of Likes" data-placement="top"><img src="/img/thumbsup.png"/></a></th>
										<th><a rel="tooltip" data-original-title="Total # of Comments" data-placement="top"><img src="/img/comment.png" /></a></th>
										<th><a rel="tooltip"  data-original-title="Total # of Recieved Likes" data-placement="top"><img src="/img/rthumbsup.png" /></a></th>
										<th><a rel="tooltip" data-original-title="Total # of Recieved Comments" data-placement="top"><img src="/img/rcomment.png" /></a></th>
										<th><a rel="tooltip" data-original-title="Total Followers" data-placement="top"><img src="/img/eye_arrow.png" /></a></th>
										<th><a rel="tooltip" data-original-title="Total Following" data-placement="top"><img src="/img/eye_arrow2.png" /></a></th>
									</tr>
								</thead>
								<tbody>
									<?php foreach($this->topFanList as $fan): ?>
										<tr>
										
											<td class="name"><a rel="popover" data-userid="<?=$fan['facebook_user_id']?>"><?=$fan['fan_name']?></a></td>
											<td class="points"><?=$fan['fan_exp']; ?></td>
											<td class="level"><?=$fan['fan_level']?></td>
											<td class="posts"><?=$fan['post_count']?></td>
											<td class="likes"><?=$fan['like_count']?></td>
											<td class="comments"><?=$fan['comment_count']?></td>
											<td class="rlikes"><?=$fan['got_like_count']?></td>
											<td class="rcomments"><?=$fan['got_comment_count']?></td>
											<td class="followers"><?=$fan['follower']?></td>
											<td class="followings"><?=$fan['following']?></td>															
										</tr>
									<?php endforeach; ?>
								</tbody>
							</table>
						</div>
					</div>
					
				</div>
						
				<div id="dashboard" class="tab-pane">
				
				
				
				
				</div>
				<div id="themesettings" class="tab-pane"></div>
				<div id="users" class="tab-pane"></div>
				<div id="badges" class="tab-pane"></div>
				<div id="points" class="tab-pane"></div>
			</div>
			
		</div>
	
	</div>
	
</div>	
	
	
<!--  
	
	
	<div class="row-fluid">
		<div class="span3">
			<div class="box left-sidebar-wrapper">
				<ul class="nav nav-list">
					<li class="active"><a>General</a></li>
					<li><a href="/admin/dashboard/preview/<?= $this->page_id ?>"><i class="icon-eye-open"></i> Preview</a></li>
					<li><a href="/admin/dashboard/badgewizard/<?= $this->page_id ?>"><i class="icon-pencil"></i> BadgeWizard</a></li>
					<li>
						<div class="btn-group" style="margin-left: -14px;">
							<ul class="nav nav-pills">
								<li class="dropdown" id="menu3"><a class="dropdown-toggle"
									data-toggle="dropdown" href="#menu3"><i class="icon-cog"></i> Setting <b
										class="caret"></b>
								</a>
									<ul class="dropdown-menu">
										<li><a href="/admin/dashboard/pointsetting/<?= $this->page_id ?>"> Point Setting</a></li>
										<li><a href="/admin/dashboard/fanpagescope/<?= $this->page_id ?>"> Facebook Permission</a></li>
										<li class="divider"></li>
										<li><a class="model-btn" href="#myFanpageSettingModel"> Other Settings</a></li>
									</ul></li>
							</ul>
						</div>
					</li>					
					<li class="divider"></li>
					<li><a href="/admin/dashboard/showlog/<?= $this->page_id ?>"><i class="icon-list-alt"></i> View Logs</a></li>
					<li class="divider"></li>
					<li>
			
						<div class="dashboard-setting btn-group">
							<ul class="nav nav-pills">
								<li></li>
								<li class="dropdown" id="menu1"><a class="dropdown-toggle"
									data-toggle="dropdown" href="#menu1"> Show statistics <b
										class="caret"></b>
								</a>
									<ul class="dropdown-menu graph-dropdown">
										<li><a href="#">total likes statistics</a></li>
										<li><a href="#">daily posts statistics</a></li>
										<li><a href="#">daily comments statistics</a></li>
										<li class="divider"></li>
										<li><a href="#">over all</a></li>
									</ul></li>
							</ul>
						</div>
					</li>
					<li>
				
						<div class="btn-group">
							<ul class="nav nav-pills">
								<li></li>
								<li class="dropdown" id="menu2"><a class="dropdown-toggle"
									data-toggle="dropdown" href="#menu2"> Export <b
										class="caret"></b>
								</a>
									<ul class="dropdown-menu export-dropdown">
										<li><a href="#">Top fans list</a></li>
										<li><a href="#">Top post</a></li>
									</ul></li>
							</ul>
							<span id="loadGif"></span>
						</div>
					</li>

				</ul>
			</div>
		</div>
		<div class="span8">
			<div class="box">
				<div class="box-head tabs">
							<h3>Fan Data By Leaderboards</h3>
							<ul class='nav nav-tabs'>
								<li class='active'>
									<a href="#topfan" data-toggle="tab" id="topfan-tab">Top Fans</a>
								</li>
								<li>
									<a href="#fanfavorite" data-toggle="tab" id="fanfavorites-tab">Fan Favorites</a>
								</li>
								<li>
									<a href="#toptalkers" data-toggle="tab" id="toptalkers-tab">Top Talkers</a>
								</li>
								<li>
									<a href="#topclickers" data-toggle="tab" id="topclicker-tab">Top Clicker</a>
								</li>
								<li>
									<a href="#topfollowed" data-toggle="tab" id="topfollowed-tab">Top Followed</a>
								</li>
							</ul>
						</div>
						<div class="box-content box-nomargin">
							<div class="tab-content">
									
									<div class="tab-pane" id="fanfavorite">
								
									
									</div>
									<div class="tab-pane" id="toptalkers">
							
									
										<table  class='table' id="toptalkersTable">
											
										</table> 
									</div>
									<div class="tab-pane" id="topclickers">
									
										<table  class='table' id="topclickersTable">
											
										</table>
									</div>
									<div class="tab-pane" id="topfollowed">
									
										<table  class='table' id="topfollowedTable">
											
										</table>
									</div>
							</div>
						</div>
			
			
			
			</div>
		</div>
	
		<div class="span2">
			<ul class="mini widget">
				<li class="dropdown pendingContainer">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-barcode"></i>Pending Orders
					</a>		
					<div class="label label-important"><?=$this->pending_orders_count ?></div>
					<ul class="dropdown-menu pull-right custom custom-dark">
						<li class="custom">
							<div class="title">
								Pending order #1 
							</div>
							<div class="action">
								<div class="btn-group">
									<a class="tip btn btn-mini" href="#" data-original-title="Show order"><i class="icon-search"></i></a>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<li class="dropdown messageContainer">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<i class="icon-check"></i>Fan Points Request
					</a>
					<div class="label label-info">
						<?=$this->fan_requests_count?>
					</div>
					<ul class="dropdown-menu pull-right custom custom-dark">
						<li class="custom">
							<div class="title">
								Show fan's request objects
							</div>
							<div class="action">
								<div class="btn-group">
									<a class="tip btn btn-mini" href="#" data-original-title="Show message"><i class="icon-search"></i></a>
								</div>
							</div>
						</li>
					</ul>
				</li>
				
				<li>
					<div class="small-chart"></div>
					<div class="chart-detail">
						<span class="amount green"><?= $this->totalPoints ?></span>
						<span class="description"><?= $this->total_award_points ?> award points </span>
					</div>
				</li>
				<li>
					<div class="small-chart"></div>
					<div class="chart-detail">
						<span class="amount"><?= $this->page_view ?></span>
						<span class="description"># of page visits yesterday</span>
					</div>
				</li>
			</ul>
		</div>
	</div>







<div style="width:600px;" class="container-fluid">
	<h3>Top Post By # Of Comments</h3>
	<div class="box-content box-nomargin">
		<div class="tab-content">
				<div class="tab-pane active" id="basic">
					<table id="topPostByComment" class='table table-striped dataTable table-bordered'>
						<thead>
							<tr>
								<th>Facebook User ID</th>
								<th>Message</th>
								<th># of Comments</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->topPostByComment as $post): ?>
								<tr>
									<td><?=$post['facebook_user_id']?></td>
									<td><?=$post['post_message']?></td>
									<td><?=$post['post_comments_count']?></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
					</table>
				</div>
		</div>
	</div>
</div>


    <div class="modal" id="myFanpageSettingModel" style="display: none">
	    <div class="modal-header">
	    <button type="button" class="close setting-btn-close" data-dismiss="modal">x</button>
	    <h3>Fanpage Setting</h3>
	    </div>
	    <div class="modal-body">
		<form class="form-horizontal">
	        <fieldset>
	          
	          <div class="control-group">
	            <label for="optionsCheckbox" class="control-label">Profile Image</label>
	            <div class="controls">
	              <label class="checkbox">
	                <input type="checkbox" value="option1" id="enableProfileImage">
	                	Enable upload profile picture to replace default fanpage picture 
	              </label>
	            </div>
	          </div>
	          
	          <div class="control-group">
	            <label for="topPostBy" class="control-label">View Top Post By</label>
	            <div class="controls">
	              <select id="topPostBy">
	                <option>time peroid</option>
	                <option>day</option>
	                <option>week</option>
	                <option>month</option>
	              </select>
	            </div>
	          </div>
	
			<div class="control-group upload_image">
	    		<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
	        	<span class="control-label">Select an image</span>
	    		<input type="file" name="datafile" />
				<input type="button" value="upload"
	        		onClick="fileUpload(this.form,'/api/fanpages/<?= $this->page_id  ?>','upload'); return false;" >
				<div id="upload"></div>
			</div>
			
	        </fieldset>
      </form>
	    </div>
	    <div class="modal-footer">
	    <a href="#" class="btn model-btn-close setting-btn-close" data-dismiss="modal">Close</a>
	    <a href="#" class="btn btn-primary setting-btn-primary" data-id="<?= $this->page_id ?>">Save changes</a>
	    </div>
    </div>


    <div class="modal" id="pointModifyModel" style="display: none">
	    <div class="modal-header">
	    <button type="button" class="close user-btn-close" data-dismiss="modal">x</button>
	    <h3>Modify User: <span id="modify_user_id"></span></h3>
	    </div>
	    <div class="modal-body">
		<form class="form-horizontal">
			<div class="controls">
				<label class="radio"><input type="radio" id="add_radio" name="pointAction" checked /> <i class="icon-plus-sign"></i> </label>
				<label class="radio"><input type="radio" id="subtract_radio" name="pointAction" /> <i class="icon-minus-sign"></i> </label>
				<input type="text" id="adjust_point" name="adjust_point">
			</div>		
			<div class="control-group">
				<label class="control-label" for="message">message</label>
				<div class="controls">
				<textarea rows="3" id="modifiedPointMessage" name="modifiedPointMessage"></textarea>
				</div>
			</div>							
	    </form>
	    </div>
	    <div class="modal-footer">
	    <a href="#" class="btn model-btn-close user-btn-close" data-dismiss="modal">Close</a>
	    <a href="#" class="btn btn-primary user-btn-primary" data-id="<?= $this->page_id ?>">Submit</a>
	    </div>
    </div>
    
 

<div id="postStat"></div>
<div id="sexPieGraph2"></div>
<div id="sexPieGraph"></div>
<div id="piehover"></div>



-->
