
<? //$this->headLink()->headLink(array('rel'=>'stylesheet', 'href'=>'/css/dashboard/dashboard.css', 'type'=>'text/css')) ?>

<script>


//var postData = <?= $this->post_data ?>;
//var sexPieData = <?= $this->fansNumberBySex ?>;
</script>


<? $this->headScript()->appendFile('/js/libs/d3.v2.js') ?>
<? $this->headScript()->appendFile('/js/libs/enscroll-0.2.6.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.dataTables.min.js') ?>
<? $this->headScript()->appendFile('/js/libs/jquery.dataTables.plugin.js') ?>
<? $this->headScript()->appendFile('/js/admin/dashboard/dashboard.js') ?>
<? $this->headScript()->appendFile('/js/libs/ui.spinner.js') ?>
<? $url = 'https://www.facebook.com/pages/' . str_replace(' ', '-', $this->fanpage_name) . '/' . $this->page_id;?>

<div class="padding">

	<ul class="breadcrumb">
		<li>
			<a href="/dashboard/fanpages">
				<i class="icon-home"></i>
			</a> 
			<span class="divider">/</span>
		</li>
		<li class="active">
			<?=$this->fanpage_name?>
		</li>
	</ul>
	
	<div class="row-fluid">
		<div class="span2">
			<div class="box left-sidebar-wrapper">
				<ul class="nav nav-list">
				<li class="nav-header">Your Pages</li>
				<li class="divider"></li>
				<?php foreach($this->active_pages as $page){ ?>
					<?php
						$url = '/admin/dashboard/dashboard?id='.$page['fanpage_id'];
					?>
					
					<li <?= ($this->page_id == $page['fanpage_id'])?'class="active"':''?>>
						<a href="<?= $url ?>"><span class="image">
							
								
								<img class="face" width="30" height="30"  src="https://graph.facebook.com/<?= $page['fanpage_id'] ?>/picture" onerror="ImgError(this);">
						
						</span>	
						<span class="name">
						
								<?= $page['fanpage_name'] ?>
							
						</span>
						</a>
					</li>
				<?php }?>
					
				</ul>
			</div>
		</div>
		
		
		<div class="span10">
			
				<ul class='nav nav-tabs'>
					<li class='active'>
						<a href="#home" id="home-tab" data-toggle="tab" >Home</a>
					</li>
					<li>
						<a href="#facebook" id="facebook-tab" data-toggle="tab">Facebook Insights</a>
					</li>
					<li>
						<a href="#dashboard" id="dashboard-tab"data-toggle="tab" >Dashboard</a>
					</li>
					<li>
						<a href="#admin" id="admin-tab" data-toggle="tab">Admin</a>
					</li>
					<li>
						<a href="#users" id="users-tab" data-toggle="tab">Users</a>
					</li>
					<li>
						<a href="#badges"  id="badges-tab" data-toggle="tab">Badges</a>
					</li>
					<li>
						<a href="#points" id="points-tab" data-toggle="tab">Points</a>
					</li>
					<li>
						<a href="#redemptions" id="redemptions-tab" data-toggle="tab">Redemptions</a>
					</li>
					<li>
						<a href="#settings" id="settings-tab" data-toggle="tab">Settings</a>
					</li>
				</ul>

			<div class="box tab-content">
				<div id="home" class="tab-pane active" >
	
				</div>
						
				<div id="dashboard" class="tab-pane">

				</div>
				<div id="facebook" class="tab-pane"></div>
				<div id="admin" class="tab-pane"></div>
				<div id="users" class="tab-pane"></div>
				<div id="badges" class="tab-pane"></div>
				<div id="points" class="tab-pane"></div>
				<div id="settings" class="tab-pane"></div>
	
			</div>
			
		</div>
	
	</div>
	
</div>	
	
	
<!--  
	
	
	<div class="row-fluid">
		<div class="span3">
			<div class="box left-sidebar-wrapper">
				<ul class="nav nav-list">
					<li class="active"><a>General</a></li>
					<li><a href="/admin/dashboard/preview/<?= $this->page_id ?>"><i class="icon-eye-open"></i> Preview</a></li>
					<li><a href="/admin/dashboard/badgewizard/<?= $this->page_id ?>"><i class="icon-pencil"></i> BadgeWizard</a></li>
					<li>
						<div class="btn-group" style="margin-left: -14px;">
							<ul class="nav nav-pills">
								<li class="dropdown" id="menu3"><a class="dropdown-toggle"
									data-toggle="dropdown" href="#menu3"><i class="icon-cog"></i> Setting <b
										class="caret"></b>
								</a>
									<ul class="dropdown-menu">
										<li><a href="/admin/dashboard/pointsetting/<?= $this->page_id ?>"> Point Setting</a></li>
										<li><a href="/admin/dashboard/fanpagescope/<?= $this->page_id ?>"> Facebook Permission</a></li>
										<li class="divider"></li>
										<li><a class="model-btn" href="#myFanpageSettingModel"> Other Settings</a></li>
									</ul></li>
							</ul>
						</div>
					</li>					
					<li class="divider"></li>
					<li><a href="/admin/dashboard/showlog/<?= $this->page_id ?>"><i class="icon-list-alt"></i> View Logs</a></li>
					<li class="divider"></li>
					<li>
			
						<div class="dashboard-setting btn-group">
							<ul class="nav nav-pills">
								<li></li>
								<li class="dropdown" id="menu1"><a class="dropdown-toggle"
									data-toggle="dropdown" href="#menu1"> Show statistics <b
										class="caret"></b>
								</a>
									<ul class="dropdown-menu graph-dropdown">
										<li><a href="#">total likes statistics</a></li>
										<li><a href="#">daily posts statistics</a></li>
										<li><a href="#">daily comments statistics</a></li>
										<li class="divider"></li>
										<li><a href="#">over all</a></li>
									</ul></li>
							</ul>
						</div>
					</li>
					<li>
				
						<div class="btn-group">
							<ul class="nav nav-pills">
								<li></li>
								<li class="dropdown" id="menu2"><a class="dropdown-toggle"
									data-toggle="dropdown" href="#menu2"> Export <b
										class="caret"></b>
								</a>
									<ul class="dropdown-menu export-dropdown">
										<li><a href="#">Top fans list</a></li>
										<li><a href="#">Top post</a></li>
									</ul></li>
							</ul>
							<span id="loadGif"></span>
						</div>
					</li>

				</ul>
			</div>
		</div>
		<div class="span8">
			<div class="box">
				<div class="box-head tabs">
							<h3>Fan Data By Leaderboards</h3>
							<ul class='nav nav-tabs'>
								<li class='active'>
									<a href="#topfan" data-toggle="tab" id="topfan-tab">Top Fans</a>
								</li>
								<li>
									<a href="#fanfavorite" data-toggle="tab" id="fanfavorites-tab">Fan Favorites</a>
								</li>
								<li>
									<a href="#toptalkers" data-toggle="tab" id="toptalkers-tab">Top Talkers</a>
								</li>
								<li>
									<a href="#topclickers" data-toggle="tab" id="topclicker-tab">Top Clicker</a>
								</li>
								<li>
									<a href="#topfollowed" data-toggle="tab" id="topfollowed-tab">Top Followed</a>
								</li>
							</ul>
						</div>
						<div class="box-content box-nomargin">
							<div class="tab-content">
									
									<div class="tab-pane" id="fanfavorite">
								
									
									</div>
									<div class="tab-pane" id="toptalkers">
							
									
										<table  class='table' id="toptalkersTable">
											
										</table> 
									</div>
									<div class="tab-pane" id="topclickers">
									
										<table  class='table' id="topclickersTable">
											
										</table>
									</div>
									<div class="tab-pane" id="topfollowed">
									
										<table  class='table' id="topfollowedTable">
											
										</table>
									</div>
							</div>
						</div>
			
			
			
			</div>
		</div>
	
		<div class="span2">
			<ul class="mini widget">
				<li class="dropdown pendingContainer">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-barcode"></i>Pending Orders
					</a>		
					<div class="label label-important"><?=$this->pending_orders_count ?></div>
					<ul class="dropdown-menu pull-right custom custom-dark">
						<li class="custom">
							<div class="title">
								Pending order #1 
							</div>
							<div class="action">
								<div class="btn-group">
									<a class="tip btn btn-mini" href="#" data-original-title="Show order"><i class="icon-search"></i></a>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<li class="dropdown messageContainer">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<i class="icon-check"></i>Fan Points Request
					</a>
					<div class="label label-info">
						<?=$this->fan_requests_count?>
					</div>
					<ul class="dropdown-menu pull-right custom custom-dark">
						<li class="custom">
							<div class="title">
								Show fan's request objects
							</div>
							<div class="action">
								<div class="btn-group">
									<a class="tip btn btn-mini" href="#" data-original-title="Show message"><i class="icon-search"></i></a>
								</div>
							</div>
						</li>
					</ul>
				</li>
				
				<li>
					<div class="small-chart"></div>
					<div class="chart-detail">
						<span class="amount green"><?= $this->totalPoints ?></span>
						<span class="description"><?= $this->total_award_points ?> award points </span>
					</div>
				</li>
				<li>
					<div class="small-chart"></div>
					<div class="chart-detail">
						<span class="amount"><?= $this->page_view ?></span>
						<span class="description"># of page visits yesterday</span>
					</div>
				</li>
			</ul>
		</div>
	</div>







<div style="width:600px;" class="container-fluid">
	<h3>Top Post By # Of Comments</h3>
	<div class="box-content box-nomargin">
		<div class="tab-content">
				<div class="tab-pane active" id="basic">
					<table id="topPostByComment" class='table table-striped dataTable table-bordered'>
						<thead>
							<tr>
								<th>Facebook User ID</th>
								<th>Message</th>
								<th># of Comments</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->topPostByComment as $post): ?>
								<tr>
									<td><?=$post['facebook_user_id']?></td>
									<td><?=$post['post_message']?></td>
									<td><?=$post['post_comments_count']?></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
					</table>
				</div>
		</div>
	</div>
</div>


    <div class="modal" id="myFanpageSettingModel" style="display: none">
	    <div class="modal-header">
	    <button type="button" class="close setting-btn-close" data-dismiss="modal">x</button>
	    <h3>Fanpage Setting</h3>
	    </div>
	    <div class="modal-body">
		<form class="form-horizontal">
	        <fieldset>
	          
	          <div class="control-group">
	            <label for="optionsCheckbox" class="control-label">Profile Image</label>
	            <div class="controls">
	              <label class="checkbox">
	                <input type="checkbox" value="option1" id="enableProfileImage">
	                	Enable upload profile picture to replace default fanpage picture 
	              </label>
	            </div>
	          </div>
	          
	          <div class="control-group">
	            <label for="topPostBy" class="control-label">View Top Post By</label>
	            <div class="controls">
	              <select id="topPostBy">
	                <option>time peroid</option>
	                <option>day</option>
	                <option>week</option>
	                <option>month</option>
	              </select>
	            </div>
	          </div>
	
			<div class="control-group upload_image">
	    		<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
	        	<span class="control-label">Select an image</span>
	    		<input type="file" name="datafile" />
				<input type="button" value="upload"
	        		onClick="fileUpload(this.form,'/api/fanpages/<?= $this->page_id  ?>','upload'); return false;" >
				<div id="upload"></div>
			</div>
			
	        </fieldset>
      </form>
	    </div>
	    <div class="modal-footer">
	    <a href="#" class="btn model-btn-close setting-btn-close" data-dismiss="modal">Close</a>
	    <a href="#" class="btn btn-primary setting-btn-primary" data-id="<?= $this->page_id ?>">Save changes</a>
	    </div>
    </div>


    <div class="modal" id="pointModifyModel" style="display: none">
	    <div class="modal-header">
	    <button type="button" class="close user-btn-close" data-dismiss="modal">x</button>
	    <h3>Modify User: <span id="modify_user_id"></span></h3>
	    </div>
	    <div class="modal-body">
		<form class="form-horizontal">
			<div class="controls">
				<label class="radio"><input type="radio" id="add_radio" name="pointAction" checked /> <i class="icon-plus-sign"></i> </label>
				<label class="radio"><input type="radio" id="subtract_radio" name="pointAction" /> <i class="icon-minus-sign"></i> </label>
				<input type="text" id="adjust_point" name="adjust_point">
			</div>		
			<div class="control-group">
				<label class="control-label" for="message">message</label>
				<div class="controls">
				<textarea rows="3" id="modifiedPointMessage" name="modifiedPointMessage"></textarea>
				</div>
			</div>							
	    </form>
	    </div>
	    <div class="modal-footer">
	    <a href="#" class="btn model-btn-close user-btn-close" data-dismiss="modal">Close</a>
	    <a href="#" class="btn btn-primary user-btn-primary" data-id="<?= $this->page_id ?>">Submit</a>
	    </div>
    </div>
    
 

<div id="postStat"></div>
<div id="sexPieGraph2"></div>
<div id="sexPieGraph"></div>
<div id="piehover"></div>



-->
