<div id="pageFanMap" style="width: 800px; height:400px;"></div>

<script type="text/javascript">
	var mapData = <?= $this->pageFanData ?> || [], arrayMapData = [['country', 'fans']];
    
	$.each(mapData, function (i,v) {
		arrayMapData.push([i, v]);
	});

	console.log(arrayMapData);
	function drawVisualization(arrayMapData) {
		var arrMapData = arrayMapData,
			data = google.visualization.arrayToDataTable(arrMapData),
			geomap = new google.visualization.GeoChart(document.getElementById('pageFanMap'));
		console.log(geomap);	
		geomap.draw(data, null);
	}
    
    if (arrayMapData.length > 1) {
    	//google.setOnLoadCallback(drawVisualization);
        drawVisualization(arrayMapData);
    } else {
        //$('#pageFanMap').hide();
    }
</script>