<? $this->headLink()->headLink(array('rel'=>'stylesheet', 'href'=>'/css/dashboard/fanpagescope.css', 'type'=>'text/css')) ?>

<? $this->headScript()->appendFile('/js/libs/jquery.tagsinput.min.js') ?>

<ul class="breadcrumb">
  <li><a href="http://www.fancrank.local/admin/dashboard/fanpages"><i class="icon-home"></i></a> <span class="divider">/</span></li>
  <li><a href="/admin/dashboard/dashboard/<?= $this->page_id ?>">dashboard</a><span class="divider">/</span></li>
  <li class="active">Point Setting</li>
</ul>

<div>
	<form class="form-horizontal" action="/admin/dashboard/fanpagescope/<?= $this->page_id ?>" method="post">
		<div class="control-group">
			<label for="tags" class="control-label">Scope List</label>
			<div class="controls scopelist">
				<ul>
				<?php foreach(explode(',', $this->all_scope) as $scope) {?>
					<li><span class="scopetag"><?php echo $scope;?></span></li>
				<?}?>
				</ul>
			</div>
		</div>
		
		<div class="control-group">
			<label for="tags" class="control-label">Current Permission Scope</label>
			<div class="controls droppable">
				<input type="text" id="tags" name="facebook_scope" value="<?=$this->facebook_scope?>" class='tagsinput span12 droppable'>
			</div>
		</div>
		<input type="submit" name="confirm" value="save" />
	</form>
</div>
