<h2>Fanpages</h2>
<table class="table-striped">
	<thead>
		<th>Name</th>
		<th>Category</th>
		<th></th>
		<th></th>
	</thead>
	<tbody>
	<?php foreach($this->pages as $page): ?>
		<tr id="<?= $page['fanpage_id'] ?>">
			<td class="name"><img src="http://graph.facebook.com/<?=  $page['fanpage_id'] ?>/picture"><?= $page['fanpage_name'] ?></td>
			<td class="category"><?= $page['fanpage_category'] ?></td>
			<td class="status">
				<?php if ($page['active']): ?>
					<button class="deactivate btn btn-danger" rel="tooltip" title="Turn off data collection for this page" data-id="<?= $page['fanpage_id'] ?>">Deactivate</button>
				<?php else: ?>
					<button class="activate btn btn-success" rel="tooltip" title="Turn on data collection for this page" data-id="<?= $page['fanpage_id'] ?>">Activate</button>
				<?php endif; ?>
			</td>
			<td class="app">
				<?php if ($page['active']): ?>
					<button class="app btn btn-success" rel="tooltip" title="See fancrank working with your data." data-id="<?= $page['fanpage_id'] ?>">App</button>
				<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>	
</table>