<h2>Fanpages</h2>
<table class="table-striped">
	<thead>
		<th>Name</th>
		<th>Category</th>
		<th></th>
	</thead>
	<tbody>
	<?php foreach($this->accounts as $account): ?>
		<?php if($account->category != 'Application'): ?>
		<tr>
			<td class="name"><img src="http://graph.facebook.com/<?= $account->id ?>/picture"><?= $account->name ?></td>
			<td class="category"><?= $account->category ?></td>
			<td class="status">
				<?php if (in_array($account->id, $this->authorized)): ?>
					<button class="deactivate btn btn-danger" data-id="<?= $account->id ?>">Un-install</button>
				<?php else: ?>
					<button class="deactivate btn btn-success" data-id="<?= $account->id ?>">Install</button>
				<?php endif; ?>
			</td>
		</tr>
		<?php endif; ?>
	<?php endforeach; ?>
	</tbody>	
</table>