<div class="time">
										<label>View for 
											<select id='timelimit' onchange='changeTimeLimit()'>
												<option value=30>30 Days</option>
												<option value=14>14 Days</option>
												<option value=7>7 Days</option>
												<option value=1>1 Day</option>
												<option value=all>All Time</option>
											</select>
										</label>
										</div>
										
<table  class='table' 
<? switch($this->tabletype){?>
<? case 'topfan':?>
	id="topfanTable"
	<?break;?>
<? case 'fanfavorite': ?>
	id="fanfavoriteTable"
	<?break;?>
<? case 'toptalker': ?>
	id="toptalkerTable"
	<?break;?>
<? case 'topclicker': ?>
	id="topclickerTable"
	<?break;?>
<? case 'topfollowed': ?>
	id="topfollowedTable"
	<?break;?>
<?}?>
 >

<thead>
	<tr>
		<th><a>ID</a></th>
		<th><a>Name</a></th>
		<?php if ($this->tabletype == 'fanfavorite'){?>
		<th><a>Props</a></th>
		<?php }else if ($this->tabletype == 'topfan'){?>
		<th><a>EXP</a></th>
		<?php }else{?>
		<th><a>thing</a></th>
		<?php }?>
		<th><a >Level</a></th>
		<th><a rel="tooltip"  data-original-title="Total # of Posts" data-placement="top"><img src="/img/post.png" /></a></th>
		<th><a rel="tooltip"  data-original-title="Total # of Likes" data-placement="top"><img src="/img/thumbsup.png"/></a></th>
		<th><a rel="tooltip" data-original-title="Total # of Comments" data-placement="top"><img src="/img/comment.png" /></a></th>
		<th><a rel="tooltip"  data-original-title="Total # of Recieved Likes" data-placement="top"><img src="/img/rthumbsup.png" /></a></th>
		<th><a rel="tooltip" data-original-title="Total # of Recieved Comments" data-placement="top"><img src="/img/rcomment.png" /></a></th>
		<th><a rel="tooltip" data-original-title="Total Followers" data-placement="top"><img src="/img/eye_arrow.png" /></a></th>
		<th><a rel="tooltip" data-original-title="Total Following" data-placement="top"><img src="/img/eye_arrow2.png" /></a></th>
	</tr>
</thead>
<tbody>
	<?php foreach($this->topFanList as $fan): ?>
		<tr>
			<td class="id"><?=$fan['facebook_user_id']?></td>
			<td class="name"><a rel="popover" data-userid="<?=$fan['facebook_user_id']?>"><?=$fan['fan_name']?></a></td>
			
			<?php if ($this->tabletype == 'fanfavorite'){?>
			<td class="prop"><?=$fan['props']?></td>
			<?php }else{?>
			<td class="points"><?=$fan['fan_exp']; ?></td>
			<?php }?>
			<td class="level"><?=$fan['fan_level']?></td>
			<td class="posts"><?=$fan['post_count']?></td>
			<td class="likes"><?=$fan['like_count']?></td>
			<td class="comments"><?=$fan['comment_count']?></td>
			<td class="rlikes"><?=$fan['got_like_count']?></td>
			<td class="rcomments"><?=$fan['got_comment_count']?></td>
			<td class="followers"><?=$fan['follower']?></td>
			<td class="followings"><?=$fan['following']?></td>															
		</tr>
	<?php endforeach; ?>
</tbody>
</table>