<div class="row-fluid">
	<div class="span3">
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div class="info">
				<span class="description">Fanpage ID: </span> 
				<span class="amount"><?= $this->page_id?></span>
			</div>
			
			<div class="info">
				<span class="description">Fanpage Name: </span> 
				<span class="amount"><?= $this->fanpage_name?></span>
			</div>
			
			<div class="info">
				<span class="description">Fancrank Fanpage Level: </span> 
				<span class="amount" ><?= $this->level?></span>
			</div>
			
			<div class="info">
				<span class="description">Using Fancrank Since: </span> 
				<span class="amount">YYYY-MM-DD </span>
			</div>
			
			<div class="info">
				<span class="description">Last Admin Activity: </span> 
				<span class="amount">YYYY-MM-DD </span>
			</div>
			
			<div class="info">
				<span class="description">Last Data Collection: </span> 
				<span class="amount"><?= $this->cron_time?> </span>
			</div>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div class="info">
				<span class="description">Page Likes: </span>
				<span class="amount"><?= $this->likes ?></span>
			</div>
			
			<div class="info">
				<span class="description">Fans: </span>
				<span class="amount"><?= $this->fans ?></span>
			</div>
			<div class="info">
				<span class="description">Overall User Participation </span>
				<span class="amount"><?= round($this->fans *100/$this->likes, 4) ?> %</span>
			</div>
			<div class="info">
				<span class="description">New Fans in the last 24 Hours:</span>
					<span class="amount"><?= $this->new_fans ?></span>
			</div>
			<div class="info">
				<span class="description">Fans Increase: </span>
				<span class="amount"><?= round($this->new_fans * 100 / $this->fans, 4) ?> %</span>
			</div>
			<div class="info">
				<span class="description">New FanCrank Users this Week:</span>
				<span class="amount"><?= $this->new_fancrank_users?></span>
			</div>
			<div class="info">
				
				<span class="description">Fans that Participated this Week:</span>
				<span class="amount"><?= $this->new_interaction_users?></span>
			</div>
			<div class="info">
				<span class="description">Interactions:</span>
				<span class="amount"><?= $this->new_interaction?></span>
			</div>
			
			<div class="info">
				<span class="description">Fans that Participated this Week via FanCrank:</span>
				<span class="amount"><?= $this->fancrank_interaction_users?></span>
			</div>
			<div class="info">
				<span class="description">Interactions via FanCrank:</span>
				<span class="amount"><?= $this->fancrank_interaction?></span>
			</div>
			
			
			
			<div class="info">
				
				<span class="description">Points Awarded:</span>
				<span class="amount"></span>
				<br/>
				Today - <?= ($this->points[2]['points'] != null)?$this->points[2]['points']:0 ?> | This Week - <?= ($this->points[1]['points'] != null)?$this->points[1]['points']:0?> | Month - <?= ($this->points[0]['points'] != null)?$this->points[0]['points']:0?>
			</div>
		</div>
	
		
	</div>
	
	<div class="span9">
		<div id="placeholder"></div>

	</div>
</div>
<div class="row-fluid">
	<div class="span3"></div>
	<div class="span9">

		<table class="table" id="topPostByLike">
			<thead>
				<tr>
					<th><a>Fan</a></th>
					<th><a>Message</a></th>
					<th><a>Number of Interactions</a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->topPostByLike as $post): ?>
					<tr>
						<td style="width:20%"><?=$post['fan_name']?></td>
						<td style="width:70%"><?=$this->escape($post['message'])?></td>
						<td style="width:10%"><?=$post['total_interactions']?></td>
					</tr>
				<?php endforeach; ?>
		</tbody>
		</table>

	</div>
	<!--  
	<div class="span6">
		<table class="table" id="topfanTable">
			<thead>
				<tr>
					
					<th><a>Name</a></th>
					<th><a>EXP</a></th>
					<th><a >Level</a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Posts" data-placement="top"><img src="/img/post.png" /></a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Likes" data-placement="top"><img src="/img/thumbsup.png"/></a></th>
					<th><a rel="tooltip" data-original-title="Total # of Comments" data-placement="top"><img src="/img/comment.png" /></a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Recieved Likes" data-placement="top"><img src="/img/rthumbsup.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total # of Recieved Comments" data-placement="top"><img src="/img/rcomment.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total Followers" data-placement="top"><img src="/img/eye_arrow.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total Following" data-placement="top"><img src="/img/eye_arrow2.png" /></a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->topFanList as $fan): ?>
					<tr>
					
						<td class="name"><a rel="popover" data-userid="<?=$fan['facebook_user_id']?>"><?=$fan['fan_name']?></a></td>
						<td class="points"><?=$fan['fan_exp']; ?></td>
						<td class="level"><?=$fan['fan_level']?></td>
						<td class="posts"><?=$fan['post_count']?></td>
						<td class="likes"><?=$fan['like_count']?></td>
						<td class="comments"><?=$fan['comment_count']?></td>
						<td class="rlikes"><?=$fan['got_like_count']?></td>
						<td class="rcomments"><?=$fan['got_comment_count']?></td>
						<td class="followers"><?=$fan['follower']?></td>
						<td class="followings"><?=$fan['following']?></td>															
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	-->
</div>