<script>
var first_time_use = '<?= $this->first_time?>';
</script> 


<div class="row-fluid">
	<div class="span3">
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div class="info">
				<span class="description">Fanpage ID: </span> 
				<span class="amount"><?= $this->page_id?></span>
			</div>
			
			<div class="info">
				<span class="description">Fanpage Name: </span> 
				<span class="amount"><?= $this->fanpage_name?></span>
			</div>
			
			<div class="info">
				<span class="description">FanCrank Fanpage Level: </span> 
				<span class="amount" ><?= $this->level?></span>
			</div>
			
			<div class="info">
				<span class="description">Using FanCrank Since: </span> 
				<span class="amount"><?= $this->first_time?> </span>
			</div>
			
			<div class="info">
				<span class="description">Last Admin Activity: </span> 
				<span class="amount">YYYY-MM-DD </span>
			</div>
			
			<div class="info">
				<span class="description">Last Data Collection: </span> 
				<span class="amount"><?= $this->cron_time?> </span>
			</div>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div class="info">
				<span class="description">Page Likes: </span>
				<br/>
				<a onclick = "getHomePageLikes('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->likes ?></span>
				<br/>
				<a onclick = "getHomePageLikes('month')"><span class="description">This Month: </span></a>
				<span class="amount">x</span>
				<br/>
				<a onclick = "getHomePageLikes('week')"><span class="description">This Week: </span></a>
				<span class="amount">x</span>
				
			</div>
		</div>
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div class="info">
				<span class="description">New Fans: </span>
				<br/>
				<a onclick = "getHomeFans('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->fans['all'] ?></span>
				<br/>
				<a onclick = "getHomeFans('month')"><span class="description">This Month: </span></a>
				<span class="amount"><?= $this->fans['month'] ?></span>
				<br/>
				<a onclick = "getHomeFans('week')"><span class="description">This Week: </span></a>
				<span class="amount"><?= $this->fans['week'] ?></span>
				<br/>
				<a onclick = "getHomeFans('today')"><span class="description">Today: </span></a>
				<span class="amount"><?= $this->fans['today'] ?></span>
			</div>
		</div>	
			
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">	
			<div class="info">
				<span class="description">New Active Fans: </span>
				<br/>
				<a onclick = "getHomeActivedFans('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->active_fans['all'] ?></span>
				<br/>
				<a onclick = "getHomeActivedFans('month')"><span class="description">This Month: </span></a>
				<span class="amount"><?= $this->active_fans['month'] ?></span>
				<br/>
				<a onclick = "getHomeActivedFans('week')"><span class="description">This Week: </span></a>
				<span class="amount"><?= $this->active_fans['week'] ?></span>
				<br/>
				<a onclick = "getHomeActivedFans('today')"><span class="description">Today: </span></a>
				<span class="amount"><?= $this->active_fans['today'] ?></span>
			</div>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">	
			<div class="info">
				<span class="description">New Facebook Interactions(no Admin): </span>
				<br/>
				<a onclick = "getHomeFacebookInteractions('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->facebook_interactions[3]['all'] ?></span>
				<br/>
				<a onclick = "getHomeFacebookInteractions('month')"><span class="description">This Month: </span></a>
				<span class="amount"><?= $this->facebook_interactions[3]['month'] ?></span>
				<br/>
				<a onclick = "getHomeFacebookInteractions('week')"><span class="description">This Week: </span></a>
				<span class="amount"><?= $this->facebook_interactions[3]['week'] ?></span>
				<br/>
				<a onclick = "getHomeFacebookInteractions('today')"><span class="description">Today: </span></a>
				<span class="amount"><?= $this->facebook_interactions[3]['today'] ?></span>
			</div>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">	
			<div class="info">
				<span class="description">New FanCrank Interactions(no Admin): </span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['all'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('month')"><span class="description">This Month: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['month'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('week')"><span class="description">This Week: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['week'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('today')"><span class="description">Today: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['today'] ?></span>
			</div>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">	
			<div class="info">
				<span class="description">Interactions from Unique Users on Facebook(No Admin): </span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['all'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('month')"><span class="description">This Month: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['month'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('week')"><span class="description">This Week: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['week'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('today')"><span class="description">Today: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['today'] ?></span>
			</div>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">	
			<div class="info">
				<span class="description">Interactions from Unique Users on FanCrank(No Admin): </span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('all')"><span class="description">All: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['all'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('month')"><span class="description">This Month: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['month'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('week')"><span class="description">This Week: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['week'] ?></span>
				<br/>
				<a onclick = "getHomeFanCrankInteractions('today')"><span class="description">Today: </span></a>
				<span class="amount"><?= $this->fancrank_interactions[0]['today'] ?></span>
			</div>
		</div>
		
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">	
			
	
			<div class="info">
				<span class="description">Fans Increase: </span>
				<span class="amount"></span>
			</div>
	

			<div class="info">
				
				<a onclick="getHomePointsAwarded('#placeholder')"><span class="description">Points Awarded:</span></a>
				<span class="amount"></span>
				<br/>
				Today - <?= ($this->points[2]['points'] != null)?$this->points[2]['points']:0 ?> | This Week - <?= ($this->points[1]['points'] != null)?$this->points[1]['points']:0?> | Month - <?= ($this->points[0]['points'] != null)?$this->points[0]['points']:0?>
			</div>
		</div>
	
		
	</div>
	<div class="span9">
	
		<div class="row-fluid">
		
			<div class="span12">
				<h3 id="graphtitle">Facebook Likes</h3>
			</div>
		</div>	
		<div class="row-fluid">
			<div class="span12">
				<div id="placeholder" class= "graph">
				
				</div>
		
			</div>
			
			
			
		</div>
		<div class="row-fluid">
			<div class="span12">
				<h3 id="graphtitle2">Total Facebook Likes</h3>
			</div>
		</div>
		<div class="row-fluid">
			
			<div class="span12">
				<div id="placeholder2" class="graph"></div>
		
			</div>
		
		
		</div>
		
		<div class="row-fluid">
			
			<div class="span12">
				<table class="table" id="topPostByLike">
					<thead>
						<tr>
							<th><a>Fan</a></th>
							<th><a>Message</a></th>
							<th><a>Number of Interactions</a></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($this->topPostByLike as $post): ?>
							<tr>
								<td style="width:20%"><?=$post['fan_name']?></td>
								<td style="width:70%"><?=$this->escape($post['message'])?></td>
								<td style="width:10%"><?=$post['total_interactions']?></td>
							</tr>
						<?php endforeach; ?>
				</tbody>
				</table>
		
			</div>
		
		
		</div>
		
	</div>
	
</div>

	<!--  
	<div class="span6">
		<table class="table" id="topfanTable">
			<thead>
				<tr>
					
					<th><a>Name</a></th>
					<th><a>EXP</a></th>
					<th><a >Level</a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Posts" data-placement="top"><img src="/img/post.png" /></a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Likes" data-placement="top"><img src="/img/thumbsup.png"/></a></th>
					<th><a rel="tooltip" data-original-title="Total # of Comments" data-placement="top"><img src="/img/comment.png" /></a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Recieved Likes" data-placement="top"><img src="/img/rthumbsup.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total # of Recieved Comments" data-placement="top"><img src="/img/rcomment.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total Followers" data-placement="top"><img src="/img/eye_arrow.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total Following" data-placement="top"><img src="/img/eye_arrow2.png" /></a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->topFanList as $fan): ?>
					<tr>
						<td class="name"><a rel="popover" data-userid="<?=$fan['facebook_user_id']?>"><?=$fan['fan_name']?></a></td>
						<td class="points"><?=$fan['fan_exp']; ?></td>
						<td class="level"><?=$fan['fan_level']?></td>
						<td class="posts"><?=$fan['post_count']?></td>
						<td class="likes"><?=$fan['like_count']?></td>
						<td class="comments"><?=$fan['comment_count']?></td>
						<td class="rlikes"><?=$fan['got_like_count']?></td>
						<td class="rcomments"><?=$fan['got_comment_count']?></td>
						<td class="followers"><?=$fan['follower']?></td>
						<td class="followings"><?=$fan['following']?></td>															
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	-->
