<div class="row-fluid">
	<div>
	<img class="small-face"  src="https://graph.facebook.com/<?= $this->post->from->id ?>/picture" onerror="ImgError(this);">
	<?=  $this->post->from->name?>
	</div>
	
	<div>
	<?php if(isset($this->post->message)){ ?>
		<div>
			<?php	$reg_ex = "/\n/";
					$message = $this->escape($this->post->message);
					if(preg_match_all($reg_ex, $message, $url)) {
						$message= preg_replace($reg_ex, "<br/>", $message);
					} 
					$reg_exUrl = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,5}(\/\S*)?/";
					$m = preg_match_all($reg_exUrl, $message, $match); 
					if ($m) { 
					    $links=$match[0]; 
					    for ($j=0;$j<$m;$j++) { 
					        $message=str_replace($links[$j],'<a href="'.$links[$j].'" target="_new">'.$links[$j].'</a>',$message); 
					    } 
					} 
					echo $message; 
			?>
		</div>
	<?}	?>
	<div>	
					
				<?php if (($this->post->type == 'photo')) {?>	
					<div>
					<a target="new" href="<?echo $this->escape($this->post->link)?> ">
						<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $this->post->picture))?>'/>
					</a></div>
				<?php }elseif ($this->post->type =='video') { ?>
	
						<?php if (strstr($this->escape($this->post->link), 'youtube.com')){
								$temp=explode("http://www.youtube.com/watch?v=", $this->escape($this->post->link));?>
								<iframe width="508" height="286" src="http://www.youtube.com/embed/<?= $temp[1]?> "  frameborder="0" allowfullscreen></iframe>
						
						<?php }else if (strstr($this->escape($this->post->link), 'vimeo.com')){
								$temp=explode("http://vimeo.com/", 	$this->escape($this->post->link));	?>
								<iframe width="508" height="286" src="http://player.vimeo.com/video/<?= $temp[1]?>"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
					
						<?php }else if (strstr($this->escape($this->post->link), 'facebook.com')){
								$temp=explode("v=", $this->escape($this->post->link));?>
							 <object width="508" height="286" > 
							 <param name="allowfullscreen" value="true" /> 
							 <param name="allowscriptaccess" value="always" /> 
							 <param name="movie" value="http://www.facebook.com/v/<?= $temp[1]?>" /> 
							 <embed src="http://www.facebook.com/v/<?= $temp[1]?>" type="application/x-shockwave-flash"  
							   allowscriptaccess="always" allowfullscreen="true" width="508" height="286"> 
							 </embed> 
							</object> 
						<?php }else if (strstr($this->escape($this->post->link), 'liveleak.com/view')){ 
								$temp=explode("view?i=", $this->escape($this->post->link));?>
							<iframe width="508" height="286" src="http://www.liveleak.com/ll_embed?f=<?= $temp[1] ?>" frameborder="0" allowfullscreen></iframe>
						<?php }?>
				<?}elseif ($this->post->type == 'link') {?>
					<div >
						<?php if (isset($this->post->picture)){?>
							<div >
								<a target="new" href="<?echo $this->escape($this->post->link)?> "> 
									<img src = '<?echo (str_replace('_s.jpg', '_n.jpg', $this->post->picture))?> '/>
								</a>
							</div>
							<div >
								<a target="_new" class="link-title" href="<?echo $this->escape($this->post->link)?>">
									<?= (isset($this->post->name)?$this->escape($this->post->name): $this->escape($this->post->link))?>
								</a>
								<?php if(isset($this->post->caption)){?>
								<br/>
								<a target="_new" class="link-caption" href="<?echo $this->escape($this->post->link)?> ">
									<?php echo $this->escape($this->post->caption);?>:  
								</a>
								<?php }?>	
						
								<?php if (isset($this->post->description)){?>
									<a target="_new" class="link-caption" href="<?echo $this->escape($this->post->link)?> ">	
										<?=$this->escape($this->post->description)?> 
									</a>
								<?php }?>
						</div>
						<?php }else{?>
						<div ">
								<a target="_new" class="link-title" href="<?echo $this->escape($this->post->link)?>">
									<?= (isset($this->post->name)?$this->escape($this->post->name): $this->escape($this->post->link))?>
								</a>
								<?php if(isset($this->post->caption)){?>
								<br/>
								<a target="_new" class="link-caption" href="<?echo $this->escape($this->post->link)?> ">
									<?php echo $this->escape($this->post->caption);?>:  
								</a>
								<?php }?>	
						
								<?php if (isset($this->post->description)){?>
									<a target="_new" class="link-caption" href="<?echo $this->escape($this->post->link)?> ">	
										<?=$this->escape($this->post->description)?> 
									</a>
								<?php }?>
								
						</div>
						<?php }?>
					</div>
				<?}?>
		</div>
		
		<div>
			Likes <?= isset($this->post->likes)?$this->post->likes->count:'0'?>
			Comments  <?= isset($this->post->comments)?$this->post->comments->count:'0'?>
		</div>
	
	
	</div>
</div>	
	
<div class="row-fluid">
	
</div>
