<div class="setting_menu">
    <div class="color-setting btn-group">
	    <a class="dropdown-toggle btn btn-primary" data-toggle="dropdown" href="#setting">
	    	<i class="icon-cog icon-white"></i>Theme Settings
			<span class="caret"></span>
	    </a>
	    <ul class="color-config dropdown-menu">
		    <li><a href="#" data-id="<?= $this->page_id ?>">Grey theme</a></li>
		    <li><a href="#" data-id="<?= $this->page_id ?>">Pink lady theme</a></li>
			<li><a href="#" data-id="<?= $this->page_id ?>">Classic theme</a></li>
			<li><a href="#" data-id="<?= $this->page_id ?>">Orange theme</a></li>
		    <li><a href="#" data-id="<?= $this->page_id ?>">Ocean theme</a></li>
		    <li class="divider"></li>
		    <li><a href="#">Extra</a></li>
    	</ul>
	</div>
	
	<div style="padding: 10px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">List header</li>
          <li class="active"><a href="#"><i class="icon-white icon-home"></i> Home</a></li>
          <li><a href="/admin/dashboard/analytic/<?= $this->page_id ?>"><i class="icon-pencil"></i> Analyst</a></li>
          <li class="nav-header">Another list header</li>
          <li><a href="/admin/dashboard/myaccount"><i class="icon-user"></i> Profile</a></li>
          <li><a class="model-btn" href="#myFanpageSettingModel"><i class="icon-cog"></i> Fanpage Settings</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="icon-flag"></i> Help</a></li>
        </ul>
	</div>
	
    <div class="modal" id="myFanpageSettingModel">
	    <div class="modal-header">
	    <button type="button" class="close model-btn-close" data-dismiss="modal">x</button>
	    <h3>Fanpage Setting</h3>
	    </div>
	    <div class="modal-body">
		<form class="form-horizontal">
	        <fieldset>
	          
	          <div class="control-group">
	            <label for="optionsCheckbox" class="control-label">Profile Image</label>
	            <div class="controls">
	              <label class="checkbox">
	                <input type="checkbox" value="option1" id="enableProfileImage">
	                	Enable upload profile picture to replace default fanpage picture 
	              </label>
	            </div>
	          </div>
	          
	          <div class="control-group">
	            <label for="topPostBy" class="control-label">View Top Post By</label>
	            <div class="controls">
	              <select id="topPostBy">
	                <option>time peroid</option>
	                <option>day</option>
	                <option>week</option>
	                <option>month</option>
	              </select>
	            </div>
	          </div>
	
			<div class="control-group upload_image">
	    		<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
	        	<span class="control-label">Select an image</span>
	    		<input type="file" name="datafile" />
				<input type="button" value="upload"
	        		onClick="fileUpload(this.form,'/api/fanpages/<?= $this->page_id  ?>','upload'); return false;" >
				<div id="upload"></div>
			</div>
			
	        </fieldset>
      </form>
	    </div>
	    <div class="modal-footer">
	    <a href="#" class="btn model-btn-close" data-dismiss="modal">Close</a>
	    <a href="#" class="btn btn-primary" data-id="<?= $this->page_id ?>">Save changes</a>
	    </div>
    </div>
</div>
<div class="install-header">
	<?php if (!$this->installed): ?>
		<h1>Add this app to your page...</h1>
		<button class="install btn btn-success" data-id="<?= $this->page_id ?>">Install</button>
	<?php else: ?>
		<h1>This app is already installed</h1>
	<?php endif; ?>
</div>

<div id="preview-panel" class="panel">
	<div class="panel">
	<div class="row">
		<div class="span12">
			<div class="top-fan" id="login">
				<div class="title">
					<div class="photo">
						<img src="/img/news-feed/top-fan-icon.jpg" />
					</div>
					<div class="title-header">
						<h3>Top Fans</h3>
						<div class="tip">
							<a rel="tooltip" title="The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!">?</a>
						</div>
					</div>
				</div>
				
			
					<div class="row profile_background">
						<?php $count = 0; ?> 
						<?php foreach($this->top_fans as $top_fan):  ?>
						<?php if ($count == 0){?>
						<ul class="top-list">
							<li>
								<div class="border-dark first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>

									<div class="flag">
										<a > <span class="photo"><img class="face"
												width="35" height="35"
												src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"
												onerror="ImgError(this);"> </span> <span class="name first">
												<?= $top_fan['fan_first_name'] ?>
										</span>
										</a>
									</div>

									<div class="points">
										<h3>
											<?= $top_fan['number_of_posts'] ?>
										</h3>
										<span>Points <br />
										</span>
									
									</div>
								</div>
							</li>

						</ul>
						<?php }else{ ?>
							<?php if ($count == 1){?>
							<ul id="top-fans-collapse" class="top-list collapse in">
							<?php }?>
								<li>
									<div class="border-dark ">
										<div class="rank">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="flag">
											<a > <span class="photo"><img class="face"
													width="35" height="35"
													src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"
													onerror="ImgError(this);"> </span> <span class="name"> <?= $top_fan['fan_first_name'] ?>
											</span>
											</a>
										</div>
										<div class="points">
											<h3>
												<?= $top_fan['number_of_posts'] ?>
											</h3>
											<span>
												Points<br />
											</span>
											
										</div>
									</div>
								</li>
	
							<?php }?>
							
							<?php $count ++; ?>
					
							<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
							<ul class="top-list">
								<li>
									<div class="border-dark first">
										<div class="rank first">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="photo"></div>
										<div class="name"></div>
										<div class="points"></div>
									</div>
								</li>
								<?php $count++;?>
							</ul>
						<?php }?>
						
						
						<?php for ( ;$count<5; $count++){ ?>
						
							<?php if ($count == 1){?>
							<ul  id="top-fans-collapse" class="top-list collapse in">		
							<?php }?>
								<li>
									<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="photo"></div>
										<div class="name"></div>
										<div class="points"></div>
									</div>
								</li>
								
							
						<?}?>
						<?}?>		
							</ul>
						
							<ul class="top-list">
								<li>
									<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank">
											<? if (strlen($this->popularYou['my_rank'])== 1){?>
											<h1>
												<?= $this->popularYou['my_rank']?>
											</h1>
											<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
											<h2>
												<?= $this->popularYou['my_rank']?>
											</h2>
											<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
											<h3>
												<?= $this->popularYou['my_rank']?>
											</h3>
											<?php }else{?>
											<h1>*</h1>
											<?php }?>
										</div>
										<div class="photo">
											<img class="face" width="35" height="35"
												src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
												onerror="ImgError(this);">
										</div>
										<div class="name">
											YOU<br />
										</div>
										
										
										<div class="align-right"><h1><a class='fancrank_login' href="#">LOGIN</a></h1><br/> TO SEE YOUR RANK!</div>
											
									
									</div>
								</li>
							</ul>
				</div>
			
			</div><!-- topfan -->
		</div><!-- span -->
	</div><!-- row -->
	<div class="feed_spacer_top">
	</div>
	<div class= "row">
		<div class="span6">
			<div class="fan-favorite">
				<div class="title">
					<div class="photo">
						<img src="/img/news-feed/fan-fav-icon.jpg" />
					</div>
					<div class="title-header">
						<h3>Fan Favorite</h3>
						<div class="tip">
							<a rel="tooltip" title="This list of fans represents the people who have garnered the most activity from others on the page.  Other fans love talking to them!">?</a>
						</div>
					</div>
				</div>
				<div class="row profile_background">
					<?php $count = 0; ?>
					<?php foreach($this->most_popular as $popular):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list">
						<li>
							<div class="border-dark first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name first">
											<?= $popular['fan_first_name'] ?>
									</span>
									</a>
								</div>

								<div class="points">
									<h3>
										<?= $popular['count'] ?>
									</h3>
									<span>Points <br />
									</span>
								
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="fan-favorite-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="border-dark ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name"> <?= $popular['fan_first_name'] ?>
									</span>
									</a>
								</div>
								<div class="points">
									<h3>
										<?= $popular['count'] ?>
									</h3>
									<span> Points<br />
									</span>
								
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list">
							<li>
								<div class="border-dark first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="photo"></div>
									<div class="name"></div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="fan-favorite-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="photo"></div>
										<div class="name"></div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->popularYou['my_rank'])== 1){?>
										<h1>
											<?= $this->popularYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->popularYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->popularYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="photo">
										<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);">
									</div>
									<div class="name">
										YOU<br />
									</div>
									<div class="align-right"><h1><a class='fancrank_login' href="#">LOGIN</a></h1><br/> TO SEE YOUR RANK!</div>
											
								</div>
							</li>
						</ul>
				
				</div>
				<div class="shadow">
					<button class="btn-top" id="fan-favorite-btn" data-toggle="collapse"
						data-target="#fan-favorite-collapse">+ More</button>
				</div>
			</div><!-- fanfav -->
		</div><!-- span -->
		<div class="span6">
			<div class="top-talker">
				<div class="title">
					<div class="photo">
						<img src="/img/news-feed/fan-fav-icon.jpg" />
					</div>
					<div class="title-header">
						<h3>Top Talker</h3>
						<div class="tip">
							<a rel="tooltip" title="These people have posted the most on the page.  Do they talk too much?  You decide!">?</a>
						</div>
					</div>
				</div>
				<div class="row profile_background">
					<?php $count = 0; ?>
					<?php foreach($this->top_talker as $talker):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list">
						<li>
							<div class="border-dark first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name first">
											<?= $talker['fan_first_name'] ?>
									</span>
									</a>
								</div>

								<div class="points">
									<h3>
										<?= $talker['number_of_posts'] ?>
									</h3>
									<span>Points <br />
									</span>
								
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="top-talker-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="border-dark ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name"> <?= $talker['fan_first_name'] ?>
									</span>
									</a>
								</div>
								<div class="points">
									<h3>
										<?= $talker['number_of_posts'] ?>
									</h3>
									<span> Points<br />
									</span>
									
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list">
							<li>
								<div class="border-dark first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="photo"></div>
									<div class="name"></div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="top-talker-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="photo"></div>
										<div class="name"></div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->talkerYou['my_rank'])== 1){?>
										<h1>
											<?= $this->talkerYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->talkerYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->talkerYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->talkerYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->talkerYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="photo">
										<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);"> 
									</div>
									<div class="name">
										YOU<br />
									</div>
									<div class="align-right"><h1><a class='fancrank_login' href="#">LOGIN</a></h1><br/> TO SEE YOUR RANK!</div>
											
								</div>
							</li>
						</ul>
				
				</div>
				<div class="shadow">
					<button class="btn-top" id="top-talker-btn" data-toggle="collapse"
						data-target="#top-talker-collapse">+ More</button>
				</div>
			</div><!-- toptalker -->
		</div><!-- span -->
	</div><!-- row -->
	<div class="feed_spacer_top">
	</div>
	<div class="row">
		<div class="span6">
			<div class="top-clicker">
				<div class="title">
					<div class="photo">
						<img src="/img/news-feed/fan-fav-icon.jpg" />
					</div>
					<div class="title-header">
						<h3>Top Clicker</h3>
						<div class="tip">
							<a rel="tooltip" title="Like, like, and like!  These people have clicked Like the most!">?</a>
						</div>
					</div>
				</div>
				<div class="row profile_background">
					<?php $count = 0; ?>
					<?php foreach($this->top_clicker as $clicker):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list">
						<li>
							<div class="border-dark first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name first">
											<?= $clicker['fan_first_name'] ?>
									</span>
									</a>
								</div>

								<div class="points">
									<h3>
										<?= $clicker['number_of_likes'] ?>
									</h3>
									<span>Points <br />
									</span>

									
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="top-clicker-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="border-dark ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name"> <?= $clicker['fan_first_name'] ?>
									</span>
									</a>
								</div>
								<div class="points">
									<h3>
										<?= $clicker['number_of_likes'] ?>
									</h3>
									<span> Points<br />
									</span>
								
									
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list">
							<li>
								<div class="border-dark first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="photo"></div>
									<div class="name"></div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="top-clicker-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="photo"></div>
										<div class="name"></div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->clickerYou['my_rank'])== 1){?>
										<h1>
											<?= $this->clickerYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->clickerYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->clickerYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->clickerYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->clickerYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="photo">
									<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);">
									</div>
									<div class="name">
										YOU<br />
									</div>
									<div class="align-right"><h1><a class='fancrank_login' href="#">LOGIN</a></h1><br/> TO SEE YOUR RANK!</div>
											
								</div>
							</li>
						</ul>
				
				</div>
				<div class="shadow">
					<button class="btn-top" id="top-clicker-btn" data-toggle="collapse"
						data-target="#top-clicker-collapse">+ More</button>
				</div>
			</div><!-- topclicker -->
		</div>
		<div class="span6">
			<div class="top-followed">
				<div class="title">
					<div class="photo">
						<img src="/img/news-feed/fan-fav-icon.jpg" />
					</div>
					<div class="title-header">
						<h3>Top Followed</h3>
						<div class="tip">
							<a rel="tooltip" title="These people have got the most followers!  Talk about being popular!">?</a>
						</div>
					</div>
				</div>
				<div class="row profile_background">
					<?php $count = 0; ?>
					<?php foreach($this->top_followed as $followed):  ?>
					<?php if ($count == 0){?>

					<ul class="top-list">
						<li>
							<div class="border-dark first">
								<div class="rank first">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>

								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $followed['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name first">
											<?= $followed['fan_first_name'] ?>
									</span>
									</a>
								</div>

								<div class="points">
									<h3>
										<?= $followed['count'] ?>
									</h3>
									<span>Points <br />
									</span>
							

									
								</div>
							</div>
						</li>

					</ul>
					<?php }else{ ?>
					<?php if ($count == 1){?>
					<ul id="top-followed-collapse" class="top-list collapse">
						<?php }?>
						<li>
							<div class="border-dark ">
								<div class="rank">
									<h1>
										<?= $count + 1 ?>
									</h1>
								</div>
								<div class="flag">
									<a > <span class="photo"><img class="face"
											width="35" height="35"
											src="https://graph.facebook.com/<?= $followed['facebook_user_id'] ?>/picture"
											onerror="ImgError(this);"> </span> <span class="name"> <?= $followed['fan_first_name'] ?>
									</span>
									</a>
								</div>
								<div class="points">
									<h3>
										<?= $followed['count'] ?>
									</h3>
									<span> Points<br />
									</span>
								

									
								
								</div>
							</div>
						</li>

						<?php }?>

						<?php $count ++; ?>

						<?php endforeach; ?>

						<?php if ($count < 5){?>
						<?php if ($count == 0){?>
						<ul class="top-list">
							<li>
								<div class="border-dark first">
									<div class="rank first">
										<h1>
											<?= $count + 1 ?>
										</h1>
									</div>
									<div class="photo"></div>
									<div class="name"></div>
									<div class="points"></div>
								</div>
							</li>
							<?php $count++;?>
							</ul>
							<?php }?>
						

						<?php for ( ;$count<5; $count++){ ?>
	
							<?php if ($count == 1){?>
							<ul id="top-followed-collapse" class="top-list collapse">
								<?php }?>
								<li>
									<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
										<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
											<h1>
												<?= $count + 1 ?>
											</h1>
										</div>
										<div class="photo"></div>
										<div class="name"></div>
										<div class="points"></div>
									</div>
								</li>

						<?}	?>
						<?}	?>

						</ul>
						<ul class="top-list">
							<li>
								<div class="border-dark <?= ($count == 0 ? ' first' : '') ?>">
									<div class="rank">
										<? if (strlen($this->followedYou['my_rank'])== 1){?>
										<h1>
											<?= $this->followedYou['my_rank']?>
										</h1>
										<?php }elseif (strlen($this->followedYou['my_rank'])== 2) { ?>
										<h2>
											<?= $this->followedYou['my_rank']?>
										</h2>
										<?php }elseif (strlen($this->followedYou['my_rank'])== 3) { ?>
										<h3>
											<?= $this->followedYou['my_rank']?>
										</h3>
										<?php }else{?>
										<h1>*</h1>
										<?php }?>
									</div>
									<div class="photo">
										<img class="face" width="35" height="35"
											src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
											onerror="ImgError(this);">
									</div>
									<div class="name">
										YOU <br />
									</div>
									<div class="align-right"><h1><a class='fancrank_login' href="#">LOGIN</a></h1><br/> TO SEE YOUR RANK!</div>
											
								</div>
							</li>
						</ul>
				
				</div>
				<div class="shadow">
					<button class="btn-top" id="top-followed-btn" data-toggle="collapse"
						data-target="#top-followed-collapse">+ More</button>
				</div>
			</div><!-- topfollowed -->
		</div>
	</div><!-- row -->
</div><!-- panel -->	
</div>		
