<style>
.dataTable {
	width:100%;
}

.dataTables_length {
	float: left;
}
.dataTables_filter {
	float: right;
}
.dataTables_info {
	float: left;
}
.dataTables_paginate {
	float: right;	
}

.thumbnails > li {
    display: inline-block;
	float: none;
}
.facebook-user-face {
	width: 35px;
	height: 35px;
}
</style>






<div class="row-fluid">
	<div class="span2">
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<div class="info">
				<span class="description">a </span> 
				<span class="amount">b</span>
			</div>
			
		
		</div>
	</div>
	<div class="span10">
		<div class="row-fluid">
			<div class="span6">
				<h2>Redeem Item Request</h2>
				<table class="table" id="requestRedeemTable">
					<thead>
						<tr>
							<th>Transaction ID</th>
							<th>Item ID</th>
							<th>Item Name</th>
							<th></th>
							<th>Facebook User</th>
							<th>Redeemed Time (GMT-0)</th>
							<th>Confirm</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
			<div class="span6">
				<h2>Shipping Management</h2>
				<table class="table" id="shippingInfoTable">
					<thead>
						<tr>
							<th>Transaction ID</th>
							<th>Item Name</th>
							<th>Fan Name</th>
							<th>Fan Email</th>
							<th>Address</th>
							
							<th>Confirmation</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<h2>Redeem Item History</h2>
				<table class="table" id="redeemHistoryTable">
					<thead>
						<tr>
							<th>Transaction ID</th>
							<th>Item ID</th>
							<th>Item Name</th>
							<th>Picture</th>
							<th>Facebook User</th>
							<th>Redeemed Time (GMT-0)</th>
							<th>Status</th>
							<th>Memo</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>



<br/><br/>
<div class="row-fluid">
	<div class="span12">
		<h2>Item Inventory</h2>
		<button id="btnAddNewItem">Add New Item</button>
		<table class="table" id="redeemItemTable">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Description</th>
					<th>Picture</th>
					<th>Cost</th>
					<th>Operation</th>					
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>	
</div>

<!-- POPUPS -->
<!--//////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!--//////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!--//////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!--//////////////////////////////////////////////////////////////////////////////////////////////////// -->



<div id="myItemModal" class="modal hide " tabindex="-1" role="dialog" aria-labelledby="myItemModalLabel" aria-hidden="true">
	<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
	<h3 id="myItemModalLabel">Add New Item</h3>
	</div>
	<div class="modal-body">
		<form id="fanpage-item-form">
			<div class="control-group">
				<label class="control-label" for="itemName">Item Name</label>
				<div class="controls">
					<input type="text" name="itemName" id="itemName">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemDescription">Item Description</label>
				<div class="controls">
					<input type="text" name="itemDescription" id="itemDescription">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemPictureUrl">Picture Url</label>
				<div class="controls">
					<input type="text" name="itemPictureUrl" id="itemPictureUrl">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemPrice">Item Price</label>
				<div class="controls">
					<input type="text" name="itemPrice" id="itemPrice">
				</div>
			</div>		
	    	<div class="form-actions">
	    		<button type="submit" class="btn btn-primary">Add Item</button>
	    		<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    	</div>		
		</form>
	</div>
</div>

<div id="editItemModal" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myItemModalLabel" aria-hidden="true">
	<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
	<h3 id="myItemModalLabel">Edit Item</h3>
	</div>
	<div class="modal-body">
		<img name="itemPictureUrl" style="width:100px; float:right; margin-right:90px; margin-top:20px;"/>
		<form id="edit-item-form">
			<div class="control-group">
				<label class="control-label" for="itemName">Item Name</label>
				<div class="controls">
					<input type="text" name="itemName" id="itemName">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemDescription">Item Description</label>
				<div class="controls">
					<input type="text" name="itemDescription" id="itemDescription">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemPictureUrl">Picture Url</label>
				<div class="controls">
					<input type="text" name="itemPictureUrl" id="itemPictureUrl">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemPrice">Item Price</label>
				<div class="controls">
					<input type="text" name="itemPrice" id="itemPrice">
				</div>
			</div>		
	    	<div class="form-actions">
	    		<input type="hidden" name="itemId" value="" />
	    		<button type="submit" class="btn btn-primary" id="edit-item-btn">Save</button>
	    		<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    	</div>		
		</form>
		
		
		
	</div>
</div>

<div id="redeemConfirmDialog" class="modal hide " tabindex="-1" role="dialog" aria-labelledby="redeemConfirmDialog" aria-hidden="true">
	<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
	<h3 id="redeemConfirmDialog">Are you sure ?</h3>
	</div>
	<div class="modal-body">
		<form id="confirm-dialog-form">
			<div class="control-group">
				<label class="control-label" for="note">Additional note for current operation: </label>
				<div class="controls">
					<textarea rows="3" name="note" id="note"></textarea>
				</div>
			</div>
	    	<div class="form-actions">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    		<button type="submit" class="btn btn-primary" id="request-confirm-btn"  data-redeem-id="" data-request-action="">Ok</button>
	    	</div>		
		</form>
	</div>
</div>

<div id="redeemDetailModal" class="modal hide " tabindex="-1" role="dialog" aria-labelledby="redeemConfirmDialog" aria-hidden="true">
	<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
	<h3 id="redeemConfirmDialog">Redeemed Transaction Detail</h3>
	</div>
	<div class="modal-body" id="redeemDetailContent">
	</div>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {

	/* request redeem table section */
	var requestRedeemTable = $('#requestRedeemTable').dataTable({
		"sDom":'t',
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		bJQueryUI : false,
		"bAutoWidth":false,
		"bDestroy": true,
		"aoColumns": [
			{ 
				"mData": null,
				"fnRender": function(oObj) {
					return "<a class='redeem-detail' data-redeem-id='"+ oObj.aData['id'] +"' >"+ oObj.aData['id'] +"</a>";
				}					 
			},
			
			{ "mData": "item_id", "bVisible": false },
			{ 
				"mData": "name",
				"fnRender": function(oObj) {
					return "<a class='item-info' data-item-id='"+ oObj.aData['item_id'] +"' >"+ oObj.aData['name']+"</a>";
				}
			},

			{ 
				"mData": "picture",
				"fnRender": function(oObj) {
					return "<img src='"+ oObj.aData['picture'] +"' />";
				}
			},
			
			{ 
				"mData": "facebook_user_id",
				"fnRender": function(oObj) {
					return "<a class='face' data-id= '"+ oObj.aData['facebook_user_id'] +"' href='#'><img class='facebook-user-face' src='https://graph.facebook.com/"+ oObj.aData['facebook_user_id'] +
						"/picture' onerror='ImgError(this);'> <span class='facebook-user-name'>"+ oObj.aData['facebook_user_name'] +"</span></a>";
					}
			},
			{ "mData": "created_time" },
			{ 
				"mData": null, 
				"fnRender": function (oObj) {
					var redeemId = oObj.aData['id'];
					return "<ul class='unstyled thumbnails'><li><a class='approve-request-item' data-id='"+ redeemId +"' href='#'><i class='icon-ok-sign'></i>approve</a></li>" +
						"<li><a class='disapprove-request-item' data-id='"+ redeemId +"' href='#'><i class='icon-ban-circle'></i>disapprove</a></li></ul>";
				}
			}						  	
		],
		"sAjaxSource": "/admin/redeem/request/" +fanpageId
	});

	/* shipping info table section */
	var shippingInfoTable = $('#shippingInfoTable').dataTable({
		"sDom":'t',
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		bJQueryUI : false,
		"bAutoWidth":false,
		"bDestroy": true,
		"aoColumns": [
			{ 
				"mData": null,
				"fnRender": function(oObj) {
					return "<a class='redeem-detail' data-redeem-id='"+ oObj.aData['id'] +"' >"+ oObj.aData['id'] +"</a>";
				}					 
			},
			{ 
				"mData": "item_name",
				"fnRender": function(oObj) {
					return "<a class='item-info' data-item-id='"+ oObj.aData['item_id'] +"' >"+ oObj.aData['item_name']+"</a>";
				}
			},
		
			{ 
				"mData": "facebook_user_id",
				"fnRender": function(oObj) {
					return "<a class='face' data-id= '"+ oObj.aData['facebook_user_id'] +"' href='#'><img class='facebook-user-face' src='https://graph.facebook.com/"+ oObj.aData['facebook_user_id'] +
						"/picture' onerror='ImgError(this);'> <span class='facebook-user-name'>"+ oObj.aData['name'] +"</span></a>";
				}
			},
			{ "mData": "email" },
			{ "mData": "address",
			  "fnRender": function(oObj) {
					return oObj.aData['address'] + oObj.aData['city'] + oObj.aData['region'] 
							+ oObj.aData['country'] +oObj.aData['postcode'];
				}
			},
										
			{ 
				"mData": null, 
				"fnRender": function (oObj) {
					var redeemId = oObj.aData['id'];
					return "<a class='fullfill-request-item' data-id='"+ redeemId +"' href='#'><i class='icon-ok-sign'></i>fullfill</a>";
				}
			}						  	
		],
		"sAjaxSource": "/admin/redeem/shipping/" +fanpageId
	});
	
	/* hisotry table section */
	var redeemHistoryTable = $('#redeemHistoryTable').dataTable({
		"sDom":'t',
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		bJQueryUI : false,
		"bAutoWidth":false,
		"bDestroy": true,
		"aoColumns": [
			{ 
				"mData": "id",
				"fnRender": function(oObj) {
					return "<a class='redeem-detail' data-redeem-id='"+ oObj.aData['id'] +"' >"+ oObj.aData['id'] +"</a>";
				}					
			},
	        { "mData": "item_id", "bVisible": false },
			{ 
				"mData": "name",
				"fnRender": function(oObj) {
					return "<a class='item-info' data-item-id='"+ oObj.aData['item_id'] +"' >"+ oObj.aData['name']+"</a>";
				}
			},
			{ 
				"mData": "picture",
				"fnRender": function(oObj) {
					return "<img src='/img/"+ oObj.aData['picture'] +"' style='width:100px' />";
				}
			},
			{ 
				"mData": "facebook_user_id",
				"fnRender": function(oObj) {
					return "<a class='face username'  data-id= '"+ oObj.aData['facebook_user_id'] +"' href='#'><img class='facebook-user-face' src='https://graph.facebook.com/"+ oObj.aData['facebook_user_id'] +
			    		"/picture' onerror='ImgError(this);'> <span class='facebook-user-name'>"+ oObj.aData['facebook_user_name'] +"</span></a>";
				}
			},
			{ "mData": "created_time" },
			{ 
				"mData": "status",
				"fnRender": function(oObj) {
					var status = ['disapproved', 'pending', 'approved', 'fullfilled'];
					return status[oObj.aData['status']];
				}
			},
			{ "mData": "note" }
		],
		"sAjaxSource": "/admin/redeem/history/" +fanpageId
	});

	// handle approve request popup dialog
	$('.approve-request-item').live('click', function(e) {
		e.preventDefault();
		var redeemId = $(this).attr('data-id');
		$('#request-confirm-btn').attr('data-redeem-id', redeemId);
		$('#request-confirm-btn').attr('data-request-action', 'approve');
		$('#note').text('');
		$('#redeemConfirmDialog').modal('show');
	});

	// handle disaprove request popup dialog
	$('.disapprove-request-item').live('click', function(e){
		e.preventDefault();
		var redeemId = $(this).attr('data-id');
		$('#request-confirm-btn').attr('data-redeem-id', redeemId);
		$('#request-confirm-btn').attr('data-request-action', 'disapprove');
		$('#note').text('');
		$('#redeemConfirmDialog').modal('show');
	});

	// handle shipping request popup dialog
	$('.fullfill-request-item').live('click', function(e){
		e.preventDefault();
		var redeemId = $(this).attr('data-id');
		$('#request-confirm-btn').attr('data-redeem-id', redeemId);
		$('#request-confirm-btn').attr('data-request-action', 'fullfill');
		$('#note').text('');
		$('#redeemConfirmDialog').modal('show');
	});
	
	// handle request form
	$('#confirm-dialog-form').submit(function(e) {
		e.preventDefault();
		var redeemId = $('#request-confirm-btn').attr('data-redeem-id'),
			requestFormData =  $(this).serialize() + '&redeemId=' + redeemId,
			requestAction = $('#request-confirm-btn').attr('data-request-action');
		if (redeemId) {
			console.log(requestAction + ' ' + requestFormData);
			requestActionConfirm(requestAction, requestFormData);
		}
	});

	function requestActionConfirm(action, requestFormData) {
		$.ajax({
    		type: "POST",
    		url:  '/admin/redeem/'+ action +'/'+ fanpageId,
    		cache: false,
    		async: true,
    		dataType: 'html',
    		data: requestFormData,
    		success: function( data ) {
        		console.log(data);
        		if ($.trim(data) == 'ok') {
        			$('#request-confirm-btn').attr('data-redeem-id', '');
        			$('#request-confirm-btn').attr('data-request-action', '');
        			$('#redeemConfirmDialog').modal('hide');
        			if (typeof requestRedeemTable != 'undefined' && (action == 'approve' || action == 'disapprove')) {
        				requestRedeemTable.fnReloadAjax();
        				if (typeof shippingInfoTable != 'undefined' && action == 'approve') {
        					shippingInfoTable.fnReloadAjax();
        				} 

        				if (typeof redeemHistoryTable != 'undefined' && action == 'disapprove') {
        					redeemHistoryTable.fnReloadAjax();
        				}
        			}

        			if (typeof shippingInfoTable != 'undefined' && action == 'fullfill') {
        				shippingInfoTable.fnReloadAjax();
        				if (typeof redeemHistoryTable != 'undefined') {
        					redeemHistoryTable.fnReloadAjax();
        				}
        			}
        		}
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			alert(xhr.statusText);
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
	}
	/* add item form*/
	$('#fanpage-item-form').submit(function(e) {
		e.preventDefault();
		var formData = $(this).serialize();
		console.log(formData);
		$.ajax({
			url: '/admin/fanpage/additem/'+fanpageId,
		    type: 'post',
		    dataType: 'html',
		    data: formData,
		    error: function( data ) {
		    	console.log('error'+data);
		    },
		    beforeSend : function() {
			},
		    success: function (data) {
		    	console.log(data);
		    	$('#myItemModal').modal('hide');
		    	if (typeof itemTable == 'undefined') {
			    	console.log('itemTable is undefined');
		    	} else {
		    		itemTable.fnReloadAjax();
		    	}
		    	//loadRedeem();
		    }
		});  
	});

	/**/
	var itemTable = $('#redeemItemTable').dataTable({
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		 bJQueryUI : false,
		"bAutoWidth":false,
		"bDestroy": true,
		"aoColumns": [
			{ "mData": "id"},
			{ "mData": "name"},
			{ "mData": "description" },
			{ "mData": "picture" },
			{ "mData": "points" },
			{ 
				"mData": null,
				"bSearchable": false,
				"fnRender": function (oObj) {
					return "<a class='remove-fanpage-item' data-id= '"+ oObj.aData['id']+"' href='#'><i class='icon-trash'></i>delete</a>";
				}
			}
		],
		"sAjaxSource": "/admin/fanpage/listitems/" +fanpageId
	});

	itemTable.makeEditable({
        //sUpdateURL: "/admin/fanpage/updateitem/"+fanpageId,
		"aoColumns": [
			null,
			{
				//submit: 'save',
				//onblur: 'submit',
				submit: 'save',
				sUpdateURL: function(value, settings) {
					var target = $(this).closest('tr').find('td:first'),
						itemId = target.text();
						return updateItemField(itemId, 'name', value, target);
				}                              	
			},
			{
				onblur: 'submit',
				sUpdateURL: function(value, settings) {
					var target = $(this).closest('tr').find('td:first'),
						itemId = target.text();
					return updateItemField(itemId, 'description', value, target);
				}                                	
			},
			{
				onblur: 'submit',
				sUpdateURL: function(value, settings) {
					var target = $(this).closest('tr').find('td:first'),
						itemId = target.text();
					return updateItemField(itemId, 'picture', value, target);
				}                                	
			},
			{
				onblur: 'submit',
				sUpdateURL: function(value, settings) {
					var target = $(this).closest('tr').find('td:first'),
                        itemId = target.text();
					return updateItemField(itemId, 'points', value, target);
				}                                	
			}										
		],
        sAddURL: "/admin/fanpage/additem/"+fanpageId,
        sDeleteURL: "/admin/fanpage/deleteitem/"+fanpageId
	});

	/**/
	$('#btnAddNewItem').live('click', function() {
		console.log('open dialog');
		$('#fanpage-item-form')[0].reset();
		$('#myItemModal').modal('show');
	});

	/* remove item */
	$('.remove-fanpage-item').live('click', function(e){
		e.preventDefault();
		var itemId = $(this).attr('data-id');
		
		$.ajax({
    		type: "GET",
    		url:  '/admin/fanpage/deleteitem/'+ fanpageId +'?itemId=' + itemId,
    		cache: false,
    		async: true,
    		success: function( data ) {
        		console.log(data);
        		if (data == 1 && typeof itemTable != 'undefined') {
		    		itemTable.fnReloadAjax();
        		}
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			alert(xhr.statusText);
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
	});

	// update item field in item table
	function updateItemField(id, fName, fValue, target) {
		var itemId = id || '', fieldName = fName || '', fieldValue = fValue || '';
		 
		if (itemId.length > 0 && fieldName.length > 0 && fieldValue.length > 0) {
			$.ajax({
	    		type: "POST",
	    		url:  "/admin/fanpage/updateitem/"+fanpageId,
	    		cache: false,
	    		async: false,
	    		dataType: 'html',
	    		data: 'itemId='+itemId+'&'+fieldName+'='+fieldValue,
	    		success: function( data ) {
	        		if ($.trim(data) == 'ok') {
		        		console.log(data);
		        		target.css({'background-color' : 'rgb(190, 220, 190)'});
	        		} else {
	        			target.css({'background-color' : 'rgb(215, 130, 140)'});
	        		}
	    		},	
	    		error: function( xhr, errorMessage, thrownErro ) {
	    			alert(xhr.statusText);
	    			console.log(xhr.statusText, errorMessage);
	    		}
	    	});
		}
		return fValue;
	}

	// handle item information popup
	$('.item-info').live('click', function(e) {
		e.preventDefault();
		$('#edit-item-form')[0].reset();
		var itemId = $(this).attr('data-item-id');
		if (itemId) {
			$.ajax({
	    		type: "get",
	    		url:  "/admin/fanpage/iteminfo/"+fanpageId+"?itemId="+itemId,
	    		cache: false,
	    		async: true,
	    		dataType: 'json',
	    		success: function( data ) {
		    		console.log(data.id);
		    		if (data.id) {
		    			$('form#edit-item-form input[name="itemId"]').val(data.id);
						$('form#edit-item-form input[name="itemName"]').val(data.name);
						$('form#edit-item-form input[name="itemDescription"]').val(data.description);
						$('form#edit-item-form input[name="itemPictureUrl"]').val(data.picture);
						$('form#edit-item-form input[name="itemPrice"]').val(data.points);
						$('img.[name="itemPictureUrl"]').attr("src",'/img/'+data.picture);
						$('#editItemModal').modal('show');
		    		} else {
			    		alert('item not found');
		    		}
	    		},	
	    		error: function( xhr, errorMessage, thrownErro ) {
	    			alert(xhr.statusText);
	    			console.log(xhr.statusText, errorMessage);
	    		}
	    	});
		}
	});

	// handle item edit form save action
	$('#edit-item-form').submit(function(e) {
		e.preventDefault();
		var formData = $(this).serialize();
		$.ajax({
			url:  "/admin/fanpage/edititem/"+fanpageId,
		    type: 'POST',
		    dataType: 'html',
		    data: formData,
		    error: function( data ) {
		    	console.log('error'+data);
		    },
		    beforeSend : function() {
			},
		    success: function (data) {
		    	console.log(data);
		    	$('#editItemModal').modal('hide');
		    	if (typeof itemTable == 'undefined') {
			    	console.log('itemTable is undefined');
		    	} else {
		    		itemTable.fnReloadAjax();
		    	}
		    	//loadRedeem();
		    }
		}); 
	});

	
	// handle redeem detail popup
	$('.redeem-detail').live('click', function(e) {
		e.preventDefault();
		$('#redeemDetailContent').html('');
		var redeemId = $(this).attr('data-redeem-id');
		if (redeemId) {
			$.ajax({
	    		type: "get",
	    		url:  "/admin/redeem/detail/"+fanpageId+"?redeemId="+redeemId,
	    		cache: false,
	    		async: true,
	    		dataType: 'html',
	    		success: function( data ) {
					$('#redeemDetailContent').html(data);
		    		$('#redeemDetailModal').modal('show');
	    		},	
	    		error: function( xhr, errorMessage, thrownErro ) {
	    			alert(xhr.statusText);
	    			console.log(xhr.statusText, errorMessage);
	    		}
	    	});
		}
	});
});

</script>