<div class="row-fluid">
		<div class="span9">
		topfan last week
		<table class="table" id="topFansLastWeekTable">
			<thead>
				<tr>
					<th><a>Facebook User Id</a></th>
					<th><a>Rank</a></th>
					<th><a>Name</a></th>
					<th><a>Count</a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->lastWeekTopFans as $fans): ?>
					<tr>
						<td><?= $fans['facebook_user_id']?></td>	
						<td><?= $fans['rank']?></td>
						<td><?= $fans['fan_first_name']?> <?= $fans['fan_last_name']?></td>		
						<td><?= $fans['count']?></td>									
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div class="row-fluid">
	<div class="span9">
		Redeem Item History
		<table class="table" id="redeemHistoryTable">
			<thead>
				<tr>
					<th>Transaction ID</th>
					<th>Item ID</th>
					<th>Facebook User ID</th>
					<th>Created Time</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->redeemHistoryList as $redeemItem): ?>
					<tr>
						<td><?= $redeemItem->id?></td>	
						<td><?= $redeemItem->item_id?></td>
						<td><?= $redeemItem->facebook_user_id?></td>
						<td><?= $redeemItem->created_time?></td>
						<td><?= $redeemItem->status?></td>		
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div class="row-fluid">
	<div class="span9">
		Redeem Item Pending Request
		<table class="table" id="requestRedeemTable">
			<thead>
				<tr>
					<th>Transaction ID</th>
					<th>Item ID</th>
					<th>Facebook User ID</th>
					<th>Created Time</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->requestRedeemItemList as $redeemItem): ?>
					<tr>
						<td><?= $redeemItem->id?></td>	
						<td><?= $redeemItem->item_id?></td>
						<td><?= $redeemItem->facebook_user_id?></td>
						<td><?= $redeemItem->created_time?></td>
						<td><?= $redeemItem->status?></td>		
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div class="row-fluid">
	<div class="span9">
		Item Inventory
		<table class="table" id="redeemItemTable">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>description</th>
					<th>picture</th>
					<th>cost</th>					
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->itemList as $item): ?>
					<tr>
						<td><?= $item['id']?></td>	
						<td><?= $item['name']?></td>
						<td><?= $item['description']?></td>
						<td><?= $item['picture']?></td>
						<td><?= $item['points']?></td>								
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>	
</div>

<div>
	<form id="fanpage-item-form">
		<div class="control-group">
			<label class="control-label" for="itemName">Item Name</label>
			<div class="controls">
				<input type="text" name="itemName" id="itemName">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="itemDescription">Item Description</label>
			<div class="controls">
				<input type="text" name="itemDescription" id="itemDescription">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="itemPictureUrl">Picture Url</label>
			<div class="controls">
				<input type="text" name="itemPictureUrl" id="itemPictureUrl">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="itemPrice">Item Price</label>
			<div class="controls">
				<input type="text" name="itemPrice" id="itemPrice">
			</div>
		</div>		
    	<div class="form-actions">
    		<button type="submit" class="btn btn-primary">Add Item</button>
    		<button type="button" class="btn">Cancel</button>
    	</div>		
	</form>
</div>


<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	$('#fanpage-item-form').submit(function(e) {
		e.preventDefault();
		$formData = $(this).serialize();
		console.log($formData);
		$.ajax({
			url: '/admin/fanpage/additem/'+fanpageId,
		    type: 'post',
		    dataType: 'html',
		    data: $formData,
		    error: function( data ) {
		    	console.log('error'+data);
		    },
		    beforeSend : function() {
			},
		    success: function (data) {
		    	console.log(data);
		    	loadRedeem();
		    }
		});  
	});
});

</script>