<style>
.dataTables_length {
	float: left;
}
.dataTables_filter {
	float: right;
}
.dataTables_info {
	float: left;
}
.dataTables_paginate {
	float: right;	
}

.thumbnails > li {
    display: inline-block;
	float: none;
}

</style>

<div class="row-fluid">
		<div class="span9">
		topfan last week
		<table class="table" id="topFansLastWeekTable">
			<thead>
				<tr>
					<th><a>Facebook User Id</a></th>
					<th><a>Rank</a></th>
					<th><a>Name</a></th>
					<th><a>Count</a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->lastWeekTopFans as $fans): ?>
					<tr>
						<td><?= $fans['facebook_user_id']?></td>	
						<td><?= $fans['rank']?></td>
						<td><?= $fans['fan_first_name']?> <?= $fans['fan_last_name']?></td>		
						<td><?= $fans['count']?></td>									
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<br/><br/>
<div class="row-fluid">
	<div class="span9">
		<h2>Redeem Item Request</h2>
		<table class="table" id="requestRedeemTable">
			<thead>
				<tr>
					<th>Transaction ID</th>
					<th>Item ID</th>
					<th>Facebook User ID</th>
					<th>Created Time</th>
					<th>Status</th>
					<th>Confirmation</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>

<br/><br/>
<div class="row-fluid">
	<div class="span9">
		<h2>Redeem Item History</h2>
		<table class="table" id="redeemHistoryTable">
			<thead>
				<tr>
					<th>Transaction ID</th>
					<th>Item ID</th>
					<th>Facebook User ID</th>
					<th>Created Time</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>

<br/><br/>
<div class="row-fluid">
	<div class="span9">
		<h2>Item Inventory</h2>
		<button id="btnAddNewItem">Add New Item</button>
		<table class="table" id="redeemItemTable">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>description</th>
					<th>picture</th>
					<th>cost</th>
					<th>operation</th>					
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>	
</div>

<div id="myItemModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myItemModalLabel" aria-hidden="true">
	<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
	<h3 id="myItemModalLabel">Add New Item</h3>
	</div>
	<div class="modal-body">
		<form id="fanpage-item-form">
			<div class="control-group">
				<label class="control-label" for="itemName">Item Name</label>
				<div class="controls">
					<input type="text" name="itemName" id="itemName">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemDescription">Item Description</label>
				<div class="controls">
					<input type="text" name="itemDescription" id="itemDescription">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemPictureUrl">Picture Url</label>
				<div class="controls">
					<input type="text" name="itemPictureUrl" id="itemPictureUrl">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="itemPrice">Item Price</label>
				<div class="controls">
					<input type="text" name="itemPrice" id="itemPrice">
				</div>
			</div>		
	    	<div class="form-actions">
	    		<button type="submit" class="btn btn-primary">Add Item</button>
	    		<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	    	</div>		
		</form>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {

	/* request redeem table section */
	var requestRedeemTable = $('#requestRedeemTable').dataTable({
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		bJQueryUI : true,
		"bDestroy": true,
		"aoColumns": [
		              { "mData": "id"},
		              { "mData": "item_id"},
		              { "mData": "facebook_user_id" },
		              { "mData": "created_time" },
		              { 
			              "mData": null, 
			              "fnRender": function (oObj) {
										return 'pending';
						  			}
					  },
		              { 
			              "mData": null, 
			              "fnRender": function (oObj) {
										return "<ul class='unstyled thumbnails'><li><a class='approve-request-item' data-id= '"+ oObj.aData['id']+"' href='#'><i class='icon-ok-sign'></i></a></li>" +
												"<li><a class='disapprove-request-item' data-id= '"+ oObj.aData['id']+"' href='#'><i class='icon-ban-circle'></i></a></li></ul>";;
						  			}
					  }						  	
		          ],
		"sAjaxSource": "/admin/redeem/request/" +fanpageId
	});

	/* hisotry table section */
	var redeemHistoryTable = $('#redeemHistoryTable').dataTable({
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		bJQueryUI : true,
		"bDestroy": true,
		"aoColumns": [
		              { "mData": "id"},
		              { "mData": "item_id"},
		              { "mData": "facebook_user_id" },
		              { "mData": "created_time" },
		              { "mData": "status" }
		          ],
		"sAjaxSource": "/admin/redeem/history/" +fanpageId
	});
	
	// handle approve request item action
	$('.approve-request-item').live('click', function(e){
		e.preventDefault();
		var redeemId = $(this).attr('data-id');
		
		$.ajax({
    		type: "GET",
    		url:  '/admin/redeem/approve/'+ fanpageId +'?redeemId=' + redeemId,
    		cache: false,
    		async: true,
    		dataType: 'html',
    		success: function( data ) {
        		console.log(data);
        		if ($.trim(data) == 'ok' && typeof requestRedeemTable != 'undefined') {
        			requestRedeemTable.fnReloadAjax();
        			if (typeof redeemHistoryTable != 'undefined') {
        				redeemHistoryTable.fnReloadAjax();
        			}
        		}
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			alert(xhr.statusText);
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
	});

	// handle disaprove request item action
	$('.disapprove-request-item').live('click', function(e){
		e.preventDefault();
		var redeemId = $(this).attr('data-id');
		
		$.ajax({
    		type: "GET",
    		url:  '/admin/redeem/disapprove/'+ fanpageId +'?redeemId=' + redeemId,
    		cache: false,
    		async: true,
    		dataType: 'html',
    		success: function( data ) {
        		console.log(data);
        		if ($.trim(data) == 'ok' && typeof requestRedeemTable != 'undefined') {
        			requestRedeemTable.fnReloadAjax();
        			if (typeof redeemHistoryTable != 'undefined') {
        				redeemHistoryTable.fnReloadAjax();
        			}
        		}
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			alert(xhr.statusText);
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
	});

	/* add item form*/
	$('#fanpage-item-form').submit(function(e) {
		e.preventDefault();
		var formData = $(this).serialize();
		console.log(formData);
		$.ajax({
			url: '/admin/fanpage/additem/'+fanpageId,
		    type: 'post',
		    dataType: 'html',
		    data: formData,
		    error: function( data ) {
		    	console.log('error'+data);
		    },
		    beforeSend : function() {
			},
		    success: function (data) {
		    	console.log(data);
		    	$('#myItemModal').modal('hide');
		    	if (typeof itemTable == 'undefined') {
			    	console.log('itemTable is undefined');
		    	} else {
		    		itemTable.fnReloadAjax();
		    	}
		    	//loadRedeem();
		    }
		});  
	});

	/**/
	var itemTable = $('#redeemItemTable').dataTable({
		"bProcessing": false,
		"bServerSide": false,
		"sPaginationType" : "full_numbers",
		bJQueryUI : true,
		"bDestroy": true,
		"aoColumns": [
		              { "mData": "id"},
		              { "mData": "name"},
		              { "mData": "description" },
		              { "mData": "picture" },
		              { "mData": "points" },
		              { 
		            	  "mData": null,
		            	  "bSearchable": false,
	                      "fnRender": function (oObj) {
	                            return "<a class='remove-fanpage-item' data-id= '"+ oObj.aData['id']+"' href='#'><i class='icon-remove'></i></a>";
	                      }
		              }
		          ],
		"sAjaxSource": "/admin/fanpage/listitems/" +fanpageId
	});

	itemTable.makeEditable({
        //sUpdateURL: "/admin/fanpage/updateitem/"+fanpageId,
        "aoColumns": [
						null,
					{
							//submit: 'save',
							//onblur: 'submit',
							submit: 'save',
                          	sUpdateURL: function(value, settings) {
                            	var target = $(this).closest('tr').find('td:first');
                              	var itemId = target.text();
                              	//updateItemField(itemId, 'name', value, target);
                              	return updateItemField(itemId, 'name', value, target);
                          	}                              	
                    },
  					{
  						onblur: 'submit',
                        sUpdateURL: function(value, settings) {
							var target = $(this).closest('tr').find('td:first');
                          	var itemId = target.text();
							return updateItemField(itemId, 'description', value, target);
                        }                                	
					},
  					{
  						onblur: 'submit',
                        sUpdateURL: function(value, settings) {
							var target = $(this).closest('tr').find('td:first');
                          	var itemId = target.text();
							return updateItemField(itemId, 'picture', value, target);
                        }                                	
					},
  					{
  						onblur: 'submit',
                        sUpdateURL: function(value, settings) {
							var target = $(this).closest('tr').find('td:first');
                          	var itemId = target.text();
							return updateItemField(itemId, 'points', value, target);
                        }                                	
					}										
		],
        sAddURL: "/admin/fanpage/additem/"+fanpageId,
        sDeleteURL: "/admin/fanpage/deleteitem/"+fanpageId
	});

	/**/
	$('#btnAddNewItem').live('click', function() {
		console.log('open dialog');
		$('#fanpage-item-form')[0].reset();
		$('#myItemModal').modal('show');
	});

	/* remove item */
	$('.remove-fanpage-item').live('click', function(e){
		e.preventDefault();
		var itemId = $(this).attr('data-id');
		
		$.ajax({
    		type: "GET",
    		url:  '/admin/fanpage/deleteitem/'+ fanpageId +'?itemId=' + itemId,
    		cache: false,
    		async: true,
    		success: function( data ) {
        		console.log(data);
        		if (data == 1 && typeof itemTable != 'undefined') {
		    		itemTable.fnReloadAjax();
        		}
    		},	
    		error: function( xhr, errorMessage, thrownErro ) {
    			alert(xhr.statusText);
    			console.log(xhr.statusText, errorMessage);
    		}
    	});
	});

	function updateItemField(id, fName, fValue, target) {
		var itemId = id || '', fieldName = fName || '', fieldValue = fValue || '';
		 
		if (itemId.length > 0 && fieldName.length > 0 && fieldValue.length > 0) {
			$.ajax({
	    		type: "POST",
	    		url:  "/admin/fanpage/updateitem/"+fanpageId,
	    		cache: false,
	    		async: false,
	    		dataType: 'html',
	    		data: 'itemId='+itemId+'&'+fieldName+'='+fieldValue,
	    		success: function( data ) {
	        		if ($.trim(data) == 'ok') {
		        		console.log(data);
		        		target.css({'background-color' : 'rgb(190, 220, 190)'});
	        		} else {
	        			target.css({'background-color' : 'rgb(215, 130, 140)'});
	        		}
	    		},	
	    		error: function( xhr, errorMessage, thrownErro ) {
	    			alert(xhr.statusText);
	    			console.log(xhr.statusText, errorMessage);
	    		}
	    	});
		}
		return fValue;
	}

	// form validation
	
});

</script>