<? $this->headLink()->headLink(array('rel'=>'stylesheet', 'href'=>'/css/dashboard/showlog.css', 'type'=>'text/css')) ?>

<script>
var fanpageId = <?= $this->page_id ?>;
</script>

<? $this->headScript()->appendFile('/js/libs/jquery.dataTables.min.js') ?>

<ul class="breadcrumb">
  <li><a href="http://www.fancrank.local/admin/dashboard/fanpages"><i class="icon-home"></i></a> <span class="divider">/</span></li>
  <li><a href="/admin/dashboard/analytic/<?= $this->page_id ?>"><?=$this->fanpage_name?></a><span class="divider">/</span></li>
  <li class="active">Logs</li>
</ul>

<div style="padding: 10px 0;" class="well">
	<ul class="nav nav-list log-nav">
	    <li class="nav-header">View Logs By</li>
	    <li><a data-type='overall' href="/admin/dashboard/showlog/<?= $this->page_id ?>?logType=overall"><i class="icon-list-alt"></i> Over All</a></li>
	    <li><a data-type='like' href="/admin/dashboard/showlog/<?= $this->page_id ?>?logType=like"><i class="icon-list-alt"></i> Like</a></li>
	    <li><a data-type='comment' href="/admin/dashboard/showlog/<?= $this->page_id ?>?logType=comment"><i class="icon-list-alt"></i> Comment</a></li>
	    <li><a data-type='post' href="/admin/dashboard/showlog/<?= $this->page_id ?>?logType=post"><i class="icon-list-alt"></i> Post</a></li>
	    <li><a data-type='pointlog' href="/admin/dashboard/showlog/<?= $this->page_id ?>?logType=pointlog"><i class="icon-list-alt"></i> Point Log</a></li>
    </ul>
</div>

<div class="row-fluid">
	<div class="span8">
		<div class="box">
			<div class="box-head">
				<h3>Log Data</h3>
			</div>
		</div>
				<table class="table table-striped table-bordered" id="overallLogTable" style="display : none;">
					<thead>
						<tr>
							<th>fanpage_id</th>
							<th>facebook user id</th>
							<th>facebook user name</th>
							<th>activity type</th>
							<th>event object</th>
							<th>target user id</th>
							<th>target user name</th>
							<th>date</th>
							<th>message</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
		
				<table class="table table-striped table-bordered" id="postLogTable" style="display : none;">
					<thead>
						<tr>
							<th>fanpage_id</th>
							<th>facebook user id</th>
							<th>facebook user name</th>
							<th>activity type</th>
							<th>event object</th>
							<th>target user id</th>
							<th>target user name</th>
							<th>date</th>
							<th>message</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
								
				<table class="table table-striped table-bordered" id="likeLogTable" style="display : none;">
					<thead>
						<tr>
							<th>fanpage_id</th>
							<th>facebook user id</th>
							<th>facebook user name</th>
							<th>activity type</th>
							<th>event object</th>
							<th>target user id</th>
							<th>target user name</th>
							<th>date</th>
							<th>message</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
				
				<table class="table table-striped table-bordered" id="commentLogTable" style="display : none;">
					<thead>
						<tr>
							<th>fanpage_id</th>
							<th>facebook user id</th>
							<th>facebook user name</th>
							<th>activity type</th>
							<th>event object</th>
							<th>target user id</th>
							<th>target user name</th>
							<th>date</th>
							<th>message</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
				
				<table class="table table-striped table-bordered" id="pointLogTable" style="display : none;">
					<thead>
						<tr>
							<th>ID</th>
							<th>facebook user id</th>
							<th>object id</th>
							<th>object type</th>
							<th>giving point</th>
							<th>bonus</th>
							<th>date</th>
							<th>note</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
	</div>
</div>
