


<div class="row-fluid">
	<div class="span2">
	
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Fan</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topFan as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="small-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Fan All</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topFanAll as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="small-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Fan Favorite</h2>
			<?php $count = 1;?>
			<?php foreach ($this->fanFavorite as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="small-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Talker</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topTalker as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="small-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
	
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Clicker</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topClicker as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="small-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Followed</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topFollowed as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="small-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
	
		
	</div>
	<div class="span10">
		<h2>Top Fans -Deprecated Rmb to change</h2>
		<table class="table" id="userTable">
			<thead>
				<tr>
					
					<th class="table-user">Name</th>
					<?php if($this->fanpage_level >1){?>
						<th class="number">EXP</th>
						<th class="number">Level</th>
					<?php }?>
					<?php if($this->fanpage_level >2){?>
						<th class="number">Points</th>
					<?php }?>
					<th class="number">Posts<img src="/img/post.png" /></th>
					<th class="number">Likes<img src="/img/thumbsup.png"/></th>
					<th class="number">Comments<img src="/img/comment.png" /></th>
					<th class="number">Received Likes<img src="/img/rthumbsup.png" /></th>
					<th class="number">Received Comments<img src="/img/rcomment.png" /></th>
					<th class="number">Followers<img src="/img/eye_arrow.png" /></th>
					<th class="number">Following<img src="/img/eye_arrow2.png" /></th>

				</tr>
			</thead>
			<tbody>
				<?php foreach($this->topFanList as $fan): ?>
	
					<tr>
					
						<td class="table-user">
							<div class="table-user">
								<div class="gender <?=$fan['fan_gender']?>"></div>
								<div class="photo">
									<a class="username" data-id="<?=$fan['facebook_user_id']?>">
										<img class="large-face" src='https://graph.facebook.com/<?= $fan['facebook_user_id']?>/picture'/>
									</a>
								</div>
								<div class="text">
									<a class="username" data-id="<?=$fan['facebook_user_id']?>">
										<?=$fan['fan_name']?>
									</a>
								</div>
							</div>
						</td>
						<?php if($this->fanpage_level >1){?>
							<td class="number"><?=$fan['fan_exp']; ?></td>
							<td class="number"><?=$fan['fan_level']?></td>
						<?php }?>
						<?php if($this->fanpage_level >2){?>
							<td class="number"><?=$fan['points']?></td>
						<?php }?>
						<td class="number"><?=$fan['post_count']?></td>
						<td class="number"><?=$fan['like_count']?></td>
						<td class="number"><?=$fan['comment_count']?></td>
						<td class="number"><?=$fan['got_like_count']?></td>
						<td class="number"><?=$fan['got_comment_count']?></td>
						<td class="number"><?=$fan['follower']?></td>
						<td class="number"><?=$fan['following']?></td>			
											
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		
	
	</div>

</div>

