<style>

.facebook-user-face {
	width: 24px;
	height: 24px;
}

</style>


<div class="row-fluid">
	<div class="span2">
	
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Fan</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topFan as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Fan All</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topFanAll as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Fan Favorite</h2>
			<?php $count = 1;?>
			<?php foreach ($this->fanFavorite as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Talker</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topTalker as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
	
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Clicker</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topClicker as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
		
		<div style = "border:1px solid black; padding:5px; margin-bottom:10px">
			<h2>Top Followed</h2>
			<?php $count = 1;?>
			<?php foreach ($this->topFollowed as $a){?>
				<?= $count?>
				<a class="username" data-id="<?= $a['facebook_user_id']?>"> <img class="facebook-user-face" src='https://graph.facebook.com/<?= $a['facebook_user_id']?>/picture'/> 
					<span><?= $a['fan_first_name'] . ' ' . $a['fan_last_name']?></span> </a>
				<span><?=$a['count']?></span> <br/>
				<? $count++?>
			<?php }?>
		</div>
	
		
	</div>
	<div class="span10">
		<table class="table" id="userTable">
			<thead>
				<tr>
					
					<th><a>Name</a></th>
					<th><a>EXP</a></th>
					<th><a >Level</a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Posts" data-placement="top"><img src="/img/post.png" /></a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Likes" data-placement="top"><img src="/img/thumbsup.png"/></a></th>
					<th><a rel="tooltip" data-original-title="Total # of Comments" data-placement="top"><img src="/img/comment.png" /></a></th>
					<th><a rel="tooltip"  data-original-title="Total # of Recieved Likes" data-placement="top"><img src="/img/rthumbsup.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total # of Recieved Comments" data-placement="top"><img src="/img/rcomment.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total Followers" data-placement="top"><img src="/img/eye_arrow.png" /></a></th>
					<th><a rel="tooltip" data-original-title="Total Following" data-placement="top"><img src="/img/eye_arrow2.png" /></a></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->topFanList as $fan): ?>
					<tr>
					
						<td class="name"><a  class="username" data-id="<?=$fan['facebook_user_id']?>"><?=$fan['fan_name']?></a></td>
						<td class="points"><?=$fan['fan_exp']; ?></td>
						<td class="level"><?=$fan['fan_level']?></td>
						<td class="posts"><?=$fan['post_count']?></td>
						<td class="likes"><?=$fan['like_count']?></td>
						<td class="comments"><?=$fan['comment_count']?></td>
						<td class="rlikes"><?=$fan['got_like_count']?></td>
						<td class="rcomments"><?=$fan['got_comment_count']?></td>
						<td class="followers"><?=$fan['follower']?></td>
						<td class="followings"><?=$fan['following']?></td>															
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		
	
	</div>

</div>

