<?php switch ($this->color){?>
<?php case '1':?>
	<link rel="stylesheet" type="text/less" href="/css/previewstyle1.css" />
	<?php break;?>
	<?php case '2':?>
	<link rel="stylesheet" type="text/less" href="/css/previewstyle2.css" />
	<?php break;?>
<?php }?>

<div class="container" > 

<div id="wrapper">

<div id="header">
    
<div id="logo"></div>
        
</div><!--/end header -->
<div id="content">
<div class="user-profile">
<div class="tip"><a onclick="closeProfile()">X</a></div>
				<div class="profile-content"></div>
			</div>
			<div class="container">
		    	<div class="tabbable">
		    		<div class="tab-container">
						<ul class="nav nav-tabs" id="log-in-out">
						<li><a class="fancrank_login" onclick="loadPreviewNewsFeed();" >Login to FanCrank</a></li>
						</ul>
					</div>
        		
			   		<div class="preview-content">
	        			<div class="panel">
							<div class="row-fluid">
								<div class="span6">
									<div class="row box">
										<div class="title nopic">
											
											<div class="title-header nopic">What is Fancrank?</div>
											
										</div>
										<div id="whatisfancrank">
											<a class='fancrank_login' onclick="loadPreviewNewsFeed();"><img src="/img/whatisfancrank.jpg"/></a>
										</div>
									</div>
								</div>
								<div class="span6">
									<div class="top-fan" id="login">
										<div class="row box">
											<div class="title nopic">
												
												<div class="title-header nopic">
													Top Fans this Week
												</div>
												<div class="tip2">
													The following list of fans have earned the most points this week!  You can earn points by liking, commenting, and posting on this Facebook page.  Bonus points are awarded to you if others like your comments or reply to your posts!
												</div>
											</div>
												
											<?php $count = 0; ?> 
<?php foreach($this->top_fans as $top_fan):  ?>
<?php if ($count == 0){?>


<ul class="top-list first">
	<li>
		<div class="ranker first">
			<div class="rank first">
				<h1>
					<?= $count + 1 ?>
	</h1>
</div>

<div class="user">
	
	<div class="photo">
		<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face" width="35" height="35" src="https://graph.facebook.com/<?=$top_fan['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
		
<div class="name first">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
		<?=$top_fan['fan_first_name']?>
		</a>
	</div>
</div>

<div class="points">
	<h3>
		<?= $top_fan['number_of_posts'] ?>
				</h3>
				<span>Points</span>
			
			</div>
		</div>
	</li>

</ul>
<?php }else{ ?>
<?php if ($count == 1){?>
<ul id="top-fans-collapse" class="top-list">
<?php }?>
<li>
	<div class="ranker ">
		<div class="rank">
			<h1>
				<?= $count + 1 ?>
	</h1>
</div>
<div class="user">
	
		<div class="photo">
			<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face" width="35" height="35"
			src="https://graph.facebook.com/<?= $top_fan['facebook_user_id'] ?>/picture"
	onerror="ImgError(this);">
	</a>
</div>
<div class="name">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
		<?=$top_fan['fan_first_name'] ?>
			</a>
		</div>
</div>
<div class="points">
	<h3>
		<?= $top_fan['number_of_posts'] ?>
			</h3>
			<span>Points</span>
			
		</div>
	</div>
</li>

<?php }?>

<?php $count ++; ?>

<?php endforeach; ?>

<?php if ($count < 5){?>
<?php if ($count == 0){?>
<ul class="top-list <?= ($count == 0 ? ' first' : '') ?>">
<li>
	<div class="ranker first">
		<div class="rank first">
			<h1>
				<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
			<div class="photo"></div>
			<div class="name"></div>
		</div>
		<div class="points"></div>
	</div>
</li>
<?php $count++;?>
</ul>
<?php }?>


<?php for ( ;$count<5; $count++){ ?>

<?php if ($count == 1){?>
<ul  id="top-fans-collapse" class="top-list collapse in">		
<?php }?>
<li>
	<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
<h1>
	<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
			<div class="photo"></div>
			<div class="name"></div>
		</div>
		<div class="points"></div>
	</div>
</li>


<?}?>
<?}?>		
</ul>

<ul class="top-list bottom">
	<li>
		<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank">
	<? if (strlen($this->popularYou['my_rank'])== 1){?>
<h1>
	<?= $this->popularYou['my_rank']?>
</h1>
<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
<h2>
	<?= $this->popularYou['my_rank']?>
</h2>
<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
<h3>
	<?= $this->popularYou['my_rank']?>
</h3>
<?php }else{?>
<h1>*</h1>
<?php }?>
</div>
<div class="user">
	<div class="photo">
		<img class="face" width="35" height="35"
			src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
								onerror="ImgError(this);">
						</div>
						<div class="name">
							<a class="noclick">YOU</a>
						</div>
					</div>
					
					<div class="points">
						<h1><a class='fancrank_login' onclick="loadPreviewNewsFeed();" >LOGIN</a>
						</h1>
						<div class="seerank">TO SEE YOUR RANK!</div>
					</div>
				
				</div>
			</li>
		</ul>
				
	</div>

</div><!-- topfan -->
</div><!-- span -->
</div><!-- row -->


				<div class= "row-fluid">
<div class="span6">
	<div class="fan-favorite">
		
		<div class="row box">
			<div class="title  nopic">
			
				<div class="title-header nopic">
					Fan Favorites this Week 
				</div>
				<div class="tip2">
					This list of fans represents the people who have garnered the most activity from others on the page.  Other fans love talking to them!
				</div>
			</div>
			<?php $count = 0; ?>
<?php foreach($this->most_popular as $popular):  ?>
<?php if ($count == 0){?>

<ul class="top-list first">
	<li>
		<div class="ranker first">
			<div class="rank first">
				<h1>
					<?= $count + 1 ?>
	</h1>
</div>

<div class="user">
	<div class="photo">
		<a class="noclick"rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
<div class="name first">
	<a class="noclick"rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
		<?= $popular['fan_first_name'] ?>
		</a>
	</div>
</div>

<div class="points">
	<h3>
		<?= $popular['count'] ?>
				</h3>
				<span>Props</span>
			
			</div>
		</div>
	</li>

</ul>
<?php }else{ ?>
<?php if ($count == 1){?>
<ul id="fan-favorite-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker ">
		<div class="rank">
			<h1>
				<?= $count + 1 ?>
	</h1>
</div>
<div class="user">
	<div class="photo">
		<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $popular['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
<div class="name">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
	<?= $popular['fan_first_name'] ?>
		</a>
	</div>
</div>
<div class="points">
	<h3>
		<?= $popular['count'] ?>
			</h3>
			<span>Props</span>
		
		</div>
	</div>
</li>

<?php }?>

<?php $count ++; ?>

<?php endforeach; ?>

<?php if ($count < 5){?>
<?php if ($count == 0){?>
<ul class="top-list <?= ($count == 0 ? ' first' : '') ?>">
<li>
	<div class="ranker first">
		<div class="rank first">
			<h1>
				<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
			<div class="photo"></div>
			<div class="name"></div>
		</div>
		<div class="points"></div>
	</div>
</li>
<?php $count++;?>
</ul>
<?php }?>


<?php for ( ;$count<5; $count++){ ?>

<?php if ($count == 1){?>
<ul id="fan-favorite-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
<h1>
	<?= $count + 1 ?>
			</h1>
		</div>
	<div class="user">
		<div class="photo"></div>
		<div class="name"></div>
	</div>
		<div class="points"></div>
	</div>
</li>

<?}	?>
<?}	?>

</ul>
<ul class="top-list bottom">
	<li>
		<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank">
	<? if (strlen($this->popularYou['my_rank'])== 1){?>
<h1>
	<?= $this->popularYou['my_rank']?>
</h1>
<?php }elseif (strlen($this->popularYou['my_rank'])== 2) { ?>
<h2>
	<?= $this->popularYou['my_rank']?>
</h2>
<?php }elseif (strlen($this->popularYou['my_rank'])== 3) { ?>
<h3>
	<?= $this->popularYou['my_rank']?>
</h3>
<?php }else{?>
<h1>*</h1>
<?php }?>
</div>
<div class="user">
	<div class="photo">
		<img class="face" width="35" height="35"
			src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
									onerror="ImgError(this);">
							</div>
							<div class="name">
								<a class="noclick" >YOU</a>
							</div>
						</div>
						<div class="points">
								<h1><a class='fancrank_login' onclick="loadPreviewNewsFeed();">LOGIN</a>
								</h1>
								<div class="seerank">TO SEE YOUR RANK!</div>
							</div>	
					</div>
				</li>
			</ul>
	
		<button class="btn-more" id="fan-favorite-btn" data-toggle="collapse"
			data-target="#fan-favorite-collapse">+ More</button>

	</div>
	
</div><!-- fanfav -->
</div><!-- span -->
<div class="span6">
	<div class="top-talker">
		
		<div class="row box">
			<div class="title nopic">
		
				<div class="title-header nopic">
					Top Talkers this Week
					
				</div>
				<div class="tip2">
					These people have posted the most on the page.  Do they talk too much?  You decide!
				</div>
			</div>
			<?php $count = 0; ?>
<?php foreach($this->top_talker as $talker):  ?>
<?php if ($count == 0){?>

<ul class="top-list first">
	<li>
		<div class="ranker first">
			<div class="rank first">
				<h1>
					<?= $count + 1 ?>
	</h1>
</div>

<div class="user">
	<div class="photo">
		<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>		
<div class="name first">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
		<?= $talker['fan_first_name'] ?>
		</a>
	</div>
</div>

<div class="points">
	<h3>
		<?= $talker['number_of_posts'] ?>
				</h3>
				<span>Posts</span>
			
			</div>
		</div>
	</li>

</ul>
<?php }else{ ?>
<?php if ($count == 1){?>
<ul id="top-talker-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker ">
		<div class="rank">
			<h1>
				<?= $count + 1 ?>
	</h1>
</div>
<div class="user">
	<div class="photo">
		<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $talker['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
	
<div class="name">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
	<?= $talker['fan_first_name'] ?>
		</a>
	</div>
</div>
<div class="points">
	<h3>
		<?= $talker['number_of_posts'] ?>
			</h3>
			<span>Posts</span>
			
		</div>
	</div>
</li>

<?php }?>

<?php $count ++; ?>

<?php endforeach; ?>

<?php if ($count < 5){?>
<?php if ($count == 0){?>
<ul class="top-list <?= ($count == 0 ? ' first' : '') ?>">
<li>
	<div class="ranker first">
		<div class="rank first">
			<h1>
				<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
			<div class="photo"></div>
			<div class="name"></div>
		</div>
		<div class="points"></div>
	</div>
</li>
<?php $count++;?>
</ul>
<?php }?>


<?php for ( ;$count<5; $count++){ ?>

<?php if ($count == 1){?>
<ul id="top-talker-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
<h1>
	<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
		<div class="photo"></div>
		<div class="name"></div>
	</div>
		<div class="points"></div>
	</div>
</li>

<?}	?>
<?}	?>

</ul>
<ul class="top-list bottom">
	<li>
		<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank">
	<? if (strlen($this->talkerYou['my_rank'])== 1){?>
<h1>
	<?= $this->talkerYou['my_rank']?>
</h1>
<?php }elseif (strlen($this->talkerYou['my_rank'])== 2) { ?>
<h2>
	<?= $this->talkerYou['my_rank']?>
</h2>
<?php }elseif (strlen($this->talkerYou['my_rank'])== 3) { ?>
<h3>
	<?= $this->talkerYou['my_rank']?>
</h3>
<?php }else{?>
<h1>*</h1>
<?php }?>
</div>
<div class='user'>
	<div class="photo">
		<img class="face" width="35" height="35"
			src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
									onerror="ImgError(this);"> 
							</div>
							<div class="name">
								<a class="noclick">YOU</a>
							</div>
						</div>
						<div class="points">
								<h1><a class='fancrank_login' onclick="loadPreviewNewsFeed();">LOGIN</a>
								</h1>
								<div class="seerank">TO SEE YOUR RANK!</div>
							</div>	
					</div>
				</li>
			</ul>

		<button class="btn-more" id="top-talker-btn" data-toggle="collapse"
			data-target="#top-talker-collapse">+ More</button>

	</div>
	
</div><!-- toptalker -->
</div><!-- span -->
</div><!-- row -->


				<div class="row-fluid">
<div class="span6">
	<div class="top-clicker">
		
		<div class="row box">
			<div class="title nopic">
				<div class="title-header nopic">
					Top Clickers this Week
				</div>
				<div class="tip2">
					Like, like, and like!  These people have clicked Like the most!
				</div>
			</div>
			<?php $count = 0; ?>
<?php foreach($this->top_clicker as $clicker):  ?>
<?php if ($count == 0){?>

<ul class="top-list first">
	<li>
		<div class="ranker first">
			<div class="rank first">
				<h1>
					<?= $count + 1 ?>
	</h1>
</div>

<div class="user">
	<div class="photo">
		<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
<div class="name first">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
		<?= $clicker['fan_first_name'] ?>
		</a>
	</div>
</div>

<div class="points">
	<h3>
		<?= $clicker['number_of_likes'] ?>
				</h3>
				<span>Likes</span>

				
			</div>
		</div>
	</li>

</ul>
<?php }else{ ?>
<?php if ($count == 1){?>
<ul id="top-clicker-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker ">
		<div class="rank">
			<h1>
				<?= $count + 1 ?>
	</h1>
</div>
<div class="user">
	<div class="photo">
		<a class="noclick" rel="tooltip"  data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face" width="35" height="35"
			src="https://graph.facebook.com/<?= $clicker['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
<div class="name">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
	<?= $clicker['fan_first_name'] ?>
		</a>
	</div>
</div>
<div class="points">
	<h3>
		<?= $clicker['number_of_likes'] ?>
			</h3>
			<span>Likes</span>
		
			
		</div>
	</div>
</li>

<?php }?>

<?php $count ++; ?>

<?php endforeach; ?>

<?php if ($count < 5){?>
<?php if ($count == 0){?>
<ul class="top-list <?= ($count == 0 ? ' first' : '') ?>">
<li>
	<div class="ranker first">
		<div class="rank first">
			<h1>
				<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
			<div class="photo"></div>
			<div class="name"></div>
		</div>
		<div class="points"></div>
	</div>
</li>
<?php $count++;?>
</ul>
<?php }?>


<?php for ( ;$count<5; $count++){ ?>

<?php if ($count == 1){?>
<ul id="top-clicker-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
<h1>
	<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
		<div class="photo"></div>
		<div class="name"></div>
	</div>
		<div class="points"></div>
	</div>
</li>

<?}	?>
<?}	?>

</ul>
<ul class="top-list bottom">
	<li>
		<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank">
	<? if (strlen($this->clickerYou['my_rank'])== 1){?>
<h1>
	<?= $this->clickerYou['my_rank']?>
</h1>
<?php }elseif (strlen($this->clickerYou['my_rank'])== 2) { ?>
<h2>
	<?= $this->clickerYou['my_rank']?>
</h2>
<?php }elseif (strlen($this->clickerYou['my_rank'])== 3) { ?>
<h3>
	<?= $this->clickerYou['my_rank']?>
</h3>
<?php }else{?>
<h1>*</h1>
<?php }?>
</div>
<div class="user">
<div class="photo">
<img class="face" width="35" height="35"
		src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
								onerror="ImgError(this);">
						</div>
						<div class="name">
							<a class="noclick">YOU</a>
						</div>
						</div>
						<div class="points">
								<h1><a class='fancrank_login' onclick="loadPreviewNewsFeed();">LOGIN</a>
								</h1>
								<div class="seerank">TO SEE YOUR RANK!</div>
							</div>		
					</div>
				</li>
			</ul>

		<button class="btn-more" id="top-clicker-btn" data-toggle="collapse"
			data-target="#top-clicker-collapse">+ More</button>

	</div>
	
</div><!-- topclicker -->
</div>
<div class="span6">
	<div class="top-followed">
		
		<div class="row box">
			<div class="title nopic">
		
				<div class="title-header nopic">
					Top Followed
				</div>
				<div class="tip2">
					These people have got the most followers!  Talk about being popular!
				</div>
			</div>
			<?php $count = 0; ?>
<?php foreach($this->top_followed as $followed):  ?>
<?php if ($count == 0){?>

<ul class="top-list first">
	<li>
		<div class="ranker first">
			<div class="rank first">
				<h1>
					<?= $count + 1 ?>
	</h1>
</div>

<div class="user">
	<div class="photo">
		<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $followed['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>

<div class="name first">
	<a class="noclick" rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
		<?= $followed['fan_first_name'] ?>
		</a>
	</div>
</div>

<div class="points">
	<h3>
		<?= $followed['count'] ?>
				</h3>
				<span>Followers</span>
		

				
			</div>
		</div>
	</li>

</ul>
<?php }else{ ?>
<?php if ($count == 1){?>
<ul id="top-followed-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker ">
		<div class="rank">
			<h1>
				<?= $count + 1 ?>
	</h1>
</div>
<div class="user">
	<div class="photo">
		<a rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
			<img class="face"
			width="35" height="35"
			src="https://graph.facebook.com/<?= $followed['facebook_user_id'] ?>/picture"
		onerror="ImgError(this);">
	</a>
</div>
<div class="name">
	<a rel="tooltip" data-placement="right" title="Login to FanCrank to see this user's information">
	<?= $followed['fan_first_name']?>
		</a>
	</div>
</div>
<div class="points">
	<h3>
		<?= $followed['count'] ?>
			</h3>
			<span>Followers</span>
		

			
		
		</div>
	</div>
</li>

<?php }?>

<?php $count ++; ?>

<?php endforeach; ?>

<?php if ($count < 5){?>
<?php if ($count == 0){?>
<ul class="top-list <?= ($count == 0 ? ' first' : '') ?>">
<li>
	<div class="ranker first">
		<div class="rank first">
			<h1>
				<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
			<div class="photo"></div>
			<div class="name"></div>
		</div>
		<div class="points"></div>
	</div>
</li>
<?php $count++;?>
</ul>
<?php }?>


<?php for ( ;$count<5; $count++){ ?>

<?php if ($count == 1){?>
<ul id="top-followed-collapse" class="top-list collapse">
	<?php }?>
<li>
	<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank <?= ($count == 0 ? ' first' : '') ?>">
<h1>
	<?= $count + 1 ?>
			</h1>
		</div>
		<div class="user">
		<div class="photo"></div>
		<div class="name"></div>
	</div>
		<div class="points"></div>
	</div>
</li>

<?}	?>
<?}	?>

</ul>
<ul class="top-list bottom">
	<li>
		<div class="ranker <?= ($count == 0 ? ' first' : '') ?>">
<div class="rank">

	<? if (strlen($this->followedYou['my_rank'])== 1){?>
<h1>
	<?= $this->followedYou['my_rank']?>
</h1>
<?php }elseif (strlen($this->followedYou['my_rank'])== 2) { ?>
<h2>
	<?= $this->followedYou['my_rank']?>
</h2>
<?php }elseif (strlen($this->followedYou['my_rank'])== 3) { ?>
<h3>
	<?= $this->followedYou['my_rank']?>
</h3>
<?php }else{?>
<h1>*</h1>

<?php }?>
</div>
<div class="user">
<div class="photo">
	<img class="face" width="35" height="35"
		src="https://graph.facebook.com/<?= $this->user_id ?>/picture"
								onerror="ImgError(this);">
						</div>
						<div class="name">
							<a class="noclick"> YOU </a>
						</div>
						</div>
						<div class="points">
								<h1><a class='fancrank_login' onclick="loadPreviewNewsFeed();">LOGIN</a>
								</h1>
								<div class="seerank">TO SEE YOUR RANK!</div>
							</div>		
					</div>
				</li>
			</ul>

		<button class="btn-more" id="top-followed-btn" data-toggle="collapse"
			data-target="#top-followed-collapse">+ More</button>

	</div>
	
</div><!-- topfollowed -->
	</div>
</div><!-- row -->
</div><!-- panel -->
		        			</div>
		        			<div id="powered">
								<a href="http://www.fancrank.com" target=_new><img src="/img/fan-footer.png" /></a>
							</div>
		        		</div>
		        	</div>
        		</div>
        	</div>
         </div>
    
         <div class="light-box"></div>

		<br/>	
